### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by bergjet** [iobroker-community-adapters/ioBroker.ring#106]
Adapter 1.2.2
node.js 12.22.1
Raspberry 4
JS controller Installiert: 3.2.16

`

2021-05-09 10:37:20.517 - error: ring.0 (22017) Error: Could not get devices in getAllRingsDevices(). Error: Could not get all doorbell devices in getAllRingsDeviceObjects(). Error: Could not get device instance in method getDevices(). Error: Refresh token is not valid. Unable to authenticate with Ring servers. See https://github.com/dgreif/ring/wiki/Refresh-Tokens

`

**Comment by bergjet** [comment]
Löschen und neu installieren hat geholfen.

**Comment by Hini2001** [comment]
Bei diesem Fehler muss einfach der Token erneuert werden. Diese Nachricht taucht in regelmäßig unregelmäßigen Abständen auf.
Einfach den angegeben Link folgen und den Token erneuern. Adapter Neustarten und alles funktioniert wieder. :-D

**Comment by Parade76** [comment]
habe ich nun mehrfach gemacht, bringt leider nichts. Deinstalliert, neuen Token (sind ja nur 5 Zahlen) senden lassen.... bringt alles nichts. Weitere Vorschläge?

Danke

**Comment by theimo1221** [comment]
@Parade76 Bist du dir sicher mit deinem Token?!
Weil mein Token (und die anderen die ich bisher gesehen habe + Anleitung) sind eher so 30 Stellen.

Bist du dem Konsole Skript zur Erstellung gefolgt? `npx -p ring-client-api ring-auth-cli`

**Comment by Parade76** [comment]
@theimo1221 
oh, ich habe da scheinbar etwas falsch verstanden. ich habe als Token immer die Nachricht mit dem Zahlencode von Ring interpretiert. Wo finde ich die Anleitung? Danke

**Comment by theimo1221** [comment]
@Parade76 Auf der Github Startseite dieses Adapters:

"For getting the token please do following on your shell.

npx -p ring-client-api ring-auth-cli




# oder Unix 
cd /opt/iobroker/node_modules/iobroker.ring/
npm i ring-client-api

cd /opt/iobroker/node_modules/iobroker.ring/node_modules/ring-client-api
node ring-auth-cli

**Comment by Parade76** [comment]
Danke, hab es gefunden - vielen Dank
