### ISSUE TITLE
No URL

### ISSUE THREAD

**Issue by tiger1335** [iobroker-community-adapters/ioBroker.ring#114]
**Describe the bug**  
Ich habe den Adapter installiert, einen Token erstellt, die Geräte werden korrekt erkannt und die Stati/Informationen ausgelesen.
Es wird jedoch keine einzige URL angezeigt. Weder Snap, noch Livestream.

Ich habe den Adapter nochmal gelöscht und neu installiert, leider keine Verbesserung.
Es werden folgende Fehler ausgegeben:

ring.0 | 2021-05-26 19:34:31.948 | error | (1658) Error: Error setLivetream()): Error: ring.0 is not an object of type "meta"
-- | -- | -- | --
ring.0 | 2021-05-26 19:34:31.945 | error | (1658) Cannot write file doorbell_30173229/livestream*********.mp4: ring.0 is not an object of type "meta"

Hat jemand eine Idee?

Danke und LG

**Comment by theimo1221** [comment]
Hallo @tiger1335 
welche Version hast du installiert?

Versuch mal die neue v1.2.3

VG Thiemo
