### ISSUE TITLE
RING Adapter: Video vs Foto --> umkehren

### ISSUE THREAD

**Issue by Agria4800** [iobroker-community-adapters/ioBroker.ring#129]
Hallo, 
ist es möglich nach Bewegung erst das Foto aufzunehmen, danach das Video ?

Da ich mir in VIS Foto und Video anzeigen lasse, aber per Telegramm das Foto nur versendet wird, sehe ich in der Regel immer das gleiche Bild, da das Video vorang hat...

Ein weiter Wunsch wäre noch:
- der Speicherort / **Verzeichnis** für snapshots und clips zu trennen ?
- Live Stream per DP zu aktivieren um diesen in VIS sehen zu könen (ich weiß, ist nicht einfach)

Ansonsten tolle Arbeit, ich mag den Ring Adapter  :-)
Grüße
Agria4800

**Comment by Thomas-Doc** [comment]
Ja, erst Foto wäre wichtig. In der Regel ist auf dem Foto nichts mehr zu sehen, da nach Aufnahme des Videos der Auslöser längst nicht mehr zu sehen ist. Auf dem Video hingegen ist am Anfang die Person o.ä. natürlich drauf - Foto kommt aber zu spät.

vielleicht sollte man selbst wählen können, ob man Foto + Video will oder nur eines von beiden, und auch in welcher Reihenfolge. Müsste doch realisierbar sein.

**Comment by achi87** [comment]
Fände es auch super, wenn man die Reihenfolge bestimmen könnte oder auch immer zuerst der snap gemacht wird.
Als Workaround hole ich mir mit ffmpeg das erste Bild aus dem Video als Snapshot raus. Ist jetzt aber nicht erste Wahl die Lösung 😁
Insgesamt aber super Arbeit, der Adapter macht Spaß 😊

**Comment by theimo1221** [comment]
Sollte mit v2.0.0-beta.0 behoben sein
