### ISSUE TITLE
404 - Could not get devices in getAllRingsDevices()

### ISSUE THREAD

**Issue by nhet** [iobroker-community-adapters/ioBroker.ring#132]
Hallöchen zusammen,
ich bekomme die o.g. Fehlermeldung bekommen. Seit ca. gestern ( 27.07.2021) 
Den Token habe ich erneut. Ich setze die aktuelleste Version des Adapters ein.

**Comment by AFPass** [comment]
Den gleichen Fehler hab ich auch.

**Comment by DickenSerm** [comment]
Ich leider ebenfalls

**Comment by mark77-DE** [comment]
Bei mir auch.

**Comment by Bjoern2006** [comment]
Bei mir ebenfalls seit heute morgen...

**"ring.0 (XXXX) Error: Could not get devices in getAllRingsDevices(). Error: Could not get all doorbell devices in getAllRingsDeviceObjects(). Error: Could not get device instance in method getDevices(). HTTPError: Response code 404 (Not Found)"**

Versionen:
Node.js: v12.22.1
NPM: 7.19.1
Adapter: 1.2.2

**Comment by nhet** [comment]
Und nu? Was sagt denn @schmupu  dazu?

**Comment by denjo1982** [comment]
das liegt an der neuen authentifizierung die jetzt zb per sms funtioniert. der adapter müsste überarbeitet werden

**Comment by Bjoern2006** [comment]
> das liegt an der neuen authentifizierung die jetzt zb per sms funtioniert. der adapter müsste überarbeitet werden

Oder per Google Authenticator App.

**Comment by denjo1982** [comment]
ja egal wie er muss halt angepasst werden, oder???

**Comment by Bjoern2006** [comment]
> ja egal wie er muss halt angepasst werden, oder???

Vollkommen richtig!

**Comment by theimo1221** [comment]
Ich werde mich der Sache kurzfristig annehmen

**Comment by denjo1982** [comment]
kommt dann eine neue version 1.2.3 oder wie??
sorry für die frage bin kein profi?

**Comment by Bjoern2006** [comment]
> kommt dann eine neue version 1.2.3 oder wie??
> sorry für die frage bin kein profi?

Ich denke mal, weil die aktuelle neuste ist 1.2.2...

**Comment by theimo1221** [comment]
Nach einem Update auf `v1.2.3` sollte es wieder gehen.
Meldet euch bei Problemen gerne

**Comment by denjo1982** [comment]
läuft nicht er möchte immer noch den 2fa code

**Comment by Bjoern2006** [comment]
> Nach einem Update auf `v1.2.3` sollte es wieder gehen.
> Meldet euch bei Problemen gerne

Werde im Laufe des Tages updaten und berichten.

**Comment by theimo1221** [comment]
> läuft nicht er möchte immer noch den 2fa code

@denjo1982 hast du einen neuen Refresh Token erstellt und in den Einstellungen hinterlegt?

**Comment by denjo1982** [comment]
doch läuft, sorry

**Comment by nhet** [comment]
> Nach einem Update auf `v1.2.3` sollte es wieder gehen.
> Meldet euch bei Problemen gerne

Funktioniert super. Videos kommen wieder an 👌

**Comment by Bjoern2006** [comment]
> Nach einem Update auf `v1.2.3` sollte es wieder gehen.
> Meldet euch bei Problemen gerne

Funktioniert wieder einwandfrei - vielen Dank!
