### ISSUE TITLE
HTTPError: Response code 504 (Gateway Timeout)

### ISSUE THREAD

**Issue by Bjoern2006** [iobroker-community-adapters/ioBroker.ring#137]
ring.0 (XXXXX) Error: Error setHistory(): Error: Could noch get Hisotry for XXXXXXX in getHistory(id).HTTPError: Response code 504 (Gateway Timeout)

**Versions:**  
 - Adapter version: 1.2.3
 - JS-Controller version: 3.2.16
 - Node version: 12.22.1

**Additional context** 
Fehler tauucht seit heute Nachmittag sporadisch auf.
Am System und/oder an der RingDoorbell wurde nichts geändert.

**Comment by bergjet** [comment]
Selber Fehler hier.

**Comment by theimo1221** [comment]
Guten Tag zusammen,

Dieser Fehler besteht in der Ring Api Bibliothekdie wir verwenden: https://github.com/dgreif/ring/issues/697

Wir werden auf deren Team warten müssen...

Vg Thiemo

**Comment by theimo1221** [comment]
So, habe die neuste Ring Api installiert, sollte nun gehen...

Meldet euch bei Problemen gerne
