### ISSUE TITLE
Ffmpeg is not installed

### ISSUE THREAD

**Issue by kopierschnitte** [iobroker-community-adapters/ioBroker.ring#147]
**Describe the bug**  
The adapter tells me that it cannot create a LiveStream because FFmpeg isn't installed but if I invoke FFmpeg using CLI, it clearly verifies the installation:
```
ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

```

**Expected behavior**  
The adapter should find and use the installed FFmpeg binary.

**Screenshots & Logfiles**  
<html>
<body>

ring.0 | 2021-09-12 11:18:36.014 | error | executeImmediateGuarded resulted in Error: Error: Error setSanpshot()): Error: Could not create Snapshot for 59946817 in getSnapshot(). Error: Ffmpeg is not installed. See https://github.com/dgreif/ring/wiki/FFmpeg for directions.
-- | -- | -- | --
ring.0 | 2021-09-12 11:18:36.009 | error | Error creating LiveStream! Error: Ffmpeg is not installed. See https://github.com/dgreif/ring/wiki/FFmpeg for directions.

</body>
</html>

**Versions:**  
 - Adapter version: 1.2.6
 - JS-Controller version: 3.3.15
 - Node version: 12.22.6
 - Operating system: Linux iobroker 5.4.0-84-generic **Ubuntu** SMP

**Comment by theimo1221** [comment]
Sorry I`m not a linux expert so this guess might be totally wrong, but as written in ffmpeg output it was compiled for Ubuntu 9 while you mentioned using Ubuntu 5.

The other explanation I might have, is iobroker missing permissions to access that ffmpeg

**Comment by kopierschnitte** [comment]
Good idea. I tried to build ffmpeg frpm its sources and it seems to work now. I guess the distribution's build was missing some libraries.
