### ISSUE TITLE
Installation Ring Adapter 

### ISSUE THREAD

**Issue by eierfeile** [iobroker-community-adapters/ioBroker.ring#167]
**Describe the bug**  
Manuelle Installation im Ordner "node_modules" bei Adaptern is lt. Rafal Drozda nicht korrekt.

**To Reproduce**  
siehe Installationsanleitung v"Install & Configuration" on ring adapter

**Expected behavior**  
einfache und fehlerfreie Installation von ring adpater

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 1.2.6
 - JS-Controller version: 12.22.6
 -  - Node version: 6.14.15
 - Operating system: linux im Docker

**Additional context**  
In meinem Fall konnte ich den Adapter somit nicht installieren weil es dann Probleme mit den Bibliotheken gab.
Trotzdem an der Stelle 1000 Dank für die Erstellung und Wartung von Deinem Adapter!!!

**Comment by theimo1221** [comment]
@eierfeile ich glaube hier liegt ein Missverständnis vor:
Das was in der Anleitung ist, ist für das Ermitteln der ringtoken

**Comment by theimo1221** [comment]
> Ok das hab ich in der anleitung nicht so herausgelesen. Aber ich hab ohnehin kein anderen linux Rechner.

Den Token kannst du genauso in Windows erstellen (vor ausgesetzt du hast npm) und dann mit copy paste in iobroker einfügen.

**Comment by theimo1221** [comment]
Es wäre eine Methode zu deinem Ziel zu kommen, da du ja scheinbar keine andere Maschine mit den nötigen Vorraussetzungen des temporären Ermitteln eines Tokens hast.

Ja es ist gegenüber einer kurzen Ausführung mittels `npx` unschön, aber dennoch funktional.

**Comment by NormanIGB** [comment]
Muss mich da mal einhaken:
Hab es jetzt mehrfach so nach dieser Anleitung probiert, es kommt jedesmal:

Error: Failed to fetch oauth token from Ring. Verify that your email and password are correct. (error: error requesting 2fa service to send code)
    at RingRestClient.<anonymous> (/opt/iobroker/node_modules/iobroker.ring/node_modules/ring-client-api/lib/api/rest-client.js:173:23)
    at Generator.throw (<anonymous>)
    at rejected (/opt/iobroker/node_modules/iobroker.ring/node_modules/ring-client-api/lib/api/rest-client.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)


Hab es auch über Homebridge porbiert und über so ziemlich alle Anleitungen die man im Web finden kann, es funktioniert nicht.
Jedesmal die gleiche Fehlermeldung.
Kann das was mit der 2FA von Ring zu tun haben?

**Comment by NormanIGB** [comment]
Hat sich bei mir zumindest mittlerweile erledigt, meine Telefonnummer muss wohl gesperrt gewesen sein wegen zu vieler Anfragen über den IO-Adapter.

Ist nur etwas doof gewesen mit dieser Fehlermeldung hier, denn an den Zugangsdaten lag es nicht, konnte mich ja im RING-Konto ganz normal einloggen.

**Comment by eierfeile** [comment]
> Es wäre eine Methode zu deinem Ziel zu kommen, da du ja scheinbar keine andere Maschine mit den nötigen Vorraussetzungen des temporären Ermitteln eines Tokens hast.
> 
> Ja es ist gegenüber einer kurzen Ausführung mittels `npx` unschön, aber dennoch funktional.

Hi, sorry für die Verzögerung. Also ich bekomme jetzt das token. Aber wenn ich das token (ohne die 2 Anführungszeichen) in iobroker hinterlege und den Adapter starte, dann bricht er sofort ab. 
Meldung im iobroker-Log: Invalid Refresh token detected. Please check and/or create a fresh one following "https://github.com/dgreif/ring/wiki/Refresh-Tokens"

Passwort und Email lasse ich ja weiterhin eingetragen oder? In der verlinkten Anleitung steht man solle es weg lassen, homebridge sagt mir nichts und nutze ich meines Wissens nicht.


> Versuch es mal mit diesen `cd /opt/iobroker/node_modules/iobroker.ring/ npm i ring-client-api
> 
> cd /opt/iobroker/node_modules/iobroker.ring/node_modules/ring-client-api node ring-auth-cli`

Hi, sorry für die Verzögerung. Also ich bekomme jetzt das token. Hab es so gemacht wie du geschrieben hast. Aber wenn ich das token (ohne die 2 Anführungszeichen) in iobroker hinterlege und den Adapter starte, dann bricht er sofort ab. 
Meldung im iobroker-Log: Invalid Refresh token detected. Please check and/or create a fresh one following "https://github.com/dgreif/ring/wiki/Refresh-Tokens"

Passwort und Email lasse ich ja weiterhin eingetragen oder? In der verlinkten Anleitung steht man solle es weg lassen, homebridge sagt mir nichts und nutze ich meines Wissens nicht.

**Comment by eierfeile** [comment]
ok hab den richtigen Tip von jemand bekommen, der das gleiche Problem hatte. 
- Im Token sind 2-3 Leerzeichen. Diese müssen entfernt werden!
- Nachdem das token im Adapter eingefügt wurde, ist mail und passwort im adapter zu entfernen!

so hats bei mir geklappt! :-)
