### ISSUE TITLE
Snapshots/ Livestreams begrenzen

### ISSUE THREAD

**Issue by NormanIGB** [iobroker-community-adapters/ioBroker.ring#177]
Hallo zusammen, 

gibt es eine Möglichkeit, die Anzahl der aufgenommenen Streams und Bilder zu begrenzen?
Im Adapter selbst kann man ja schön ein Häkchen setzen "Lösche alte Livestreams" bzw "lösche alte Snapshots", aber wann werden die denn gelöscht?
Bislang wurde auf meinem Server nichts gelöscht, da läuft immer mehr ein....

**Comment by Yunkie** [comment]
Moin,

das Problem ist bereits gemeldet worden und in diesem Issue-Eintrag hinterlegt #96 

Da bei uns vor der Tür nicht so viel los ist, lösche ich die Streams und Bilder alle 3 Wochen vorsorglich von Hand.
Bei meinem Vater ist vor der Tür eine Menge mehr los. Der muss die Dateien alle 3 Tage löschen, da sonst die 32GB SD-Karte im Raspberry Pi schnell voll ist und den ioBroker lahm legt. Mein Vater erstellt sich zum löschen grade ein Skript das per Cron-Job ausgeführt wird. Das wäre ein Workaround, bis der Bug behoben ist.

**Comment by theimo1221** [comment]
Stale issue
