### ISSUE TITLE
Object "kind" do not get refreshed on ring

### ISSUE THREAD

**Issue by kevinlieser** [iobroker-community-adapters/ioBroker.ring#183]
When ringing the doorbell the object "ring.0.doorbell_xxx.kind" do sometimes not get refreshed.
Is there a time limit or something? 

**Versions:**  
 - Adapter version: latest
 - JS-Controller version: 3.3.18
 - Node version: 12.22.7
 - Operating system: Linux raspberrypi 5.10.17-v7l+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l GNU/Linux

**Comment by kevinlieser** [comment]
Is it possible that an active alexa skill is disturbing this? "getting" the ding event before the adapter gets it and so only sporadically is working? Disabled the alexa skill and worked the last 8 times.

**Comment by stilldazed25** [comment]
have same issue with latest build states wont change
