### ISSUE TITLE
Update stable version in repo to 1.0.6

### ISSUE THREAD

**Issue by GermanBluefox** [iobroker-community-adapters/ioBroker.ring#20]
# Think about update stable version to 1.0.6
**Version**: stable=**1.0.5** (154 days old) => latest=**1.0.6** (72 days old)
**Installs**: stable=**382** (57.88%), latest=**158** (23.94%), total=**660**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L1087)

**Comment by schmupu** [comment]
I will add the version 1.1.0 to stable in a few days
