### ISSUE TITLE
Rename get/setBinaryState methods to get/setForeignState

### ISSUE THREAD

**Issue by Apollon77** [iobroker-community-adapters/ioBroker.ring#200]
In js-controller 4.0 we decided to cleanup an inconsistent naming with get/setBinaryState methods that work like get/setForeignBinaryState.

Please adjust the methods used to use the right "Foreign" wording and use js-controller 4.0 as dependency!

In js-controller 4.1 we plan to adjust the methods without Foreign to really behave that way!

**Comment by theimo1221** [comment]
Fixed with v2.0.0-beta.0

**Comment by Apollon77** [comment]
Wow thats fast, thank you, please make sure to not update stable before controller 4 is in stable too :-))) If all is fine roughly 2 weeks, but will highly depend on beta feedback
