### ISSUE TITLE
V2.0.0 Beta 0 läßt sich nicht installieren

### ISSUE THREAD

**Issue by PalmManiac** [iobroker-community-adapters/ioBroker.ring#209]
Wenn ich versuche das Update zu installieren, scheint es fehlerfrei durchzulaufen, am Ende wird mir aber weiterhin die alte V1 angezeigt. Es gibt keine Fehler während der Installation. Alles was ausgegeben wird, ist das hier:

`host.ServerKuhnHome) | 2022-02-07 12:21:44.239 | info | host.Server(KuhnHome) iobroker exit 0
-- | -- | -- | --
host.ServerKuhnHome) | 2022-02-07 12:21:43.217 | info | host.Server(KuhnHome) iobroker upload [0] ring.admin /opt/iobroker/node_modules/iobroker.ring/admin/words.js words.js application/javascript
host.ServerKuhnHome) | 2022-02-07 12:21:43.213 | info | host.Server(KuhnHome) iobroker upload [1] ring.admin /opt/iobroker/node_modules/iobroker.ring/admin/ring.png ring.png image/png
host.ServerKuhnHome) | 2022-02-07 12:21:43.128 | info | host.Server(KuhnHome) iobroker upload [2] ring.admin /opt/iobroker/node_modules/iobroker.ring/admin/index_m.html index_m.html text/html
host.ServerKuhnHome) | 2022-02-07 12:21:43.030 | info | host.Server(KuhnHome) iobroker 157 packages are looking for funding run `npm fund` for details
host.ServerKuhnHome) | 2022-02-07 12:21:42.212 | info | host.Server(KuhnHome) iobroker + iobroker.ring@2.0.0-beta.0updated 1 package in 19.782s
host.ServerKuhnHome) | 2022-02-07 12:21:21.896 | info | host.Server(KuhnHome) iobroker NPM version: 6.14.16Installing iobroker.ring@2.0.0-beta.0... (System call)
host.ServerKuhnHome) | 2022-02-07 12:21:21.687 | info | host.Server(KuhnHome) iobroker Update ring from @1.2.8 to @2.0.0-beta.0
host.ServerKuhnHome) | 2022-02-07 12:21:20.095 | info | host.Server(KuhnHome) iobroker upgrade ring`

Getestet unter JS-Controller V3.3.16 und jetzt aktuell mit V4.0.4. NodeJS ist bei 14.19.0.

Habe ich etwas übersehen, vergessen zu installieren? Die alte Version läuft.

**Comment by theimo1221** [comment]
Moin @PalmManiac,

das mag an der falschen Versionsnummer in der `io-package.json` liegen (Vgl. #208)...
Es wird dir zwar die alte Versionsnummer angezeigt, aber im Untergrund sollte es dennoch schon die neue sein.

Werde ich mir heute Abend genauer anschauen.

Vielen Dank und Grüße

Thiemo

**Comment by PalmManiac** [comment]
Hallo @theimo1221 ,

kann man das irgendwie erkennen? Rein optisch sieht es noch so aus wie die V1, auch von den Datenpunkten her.
