### ISSUE TITLE
Javascript Fehler heap out of Memory nach Starten des Adapters und ab da regelmäßig

### ISSUE THREAD

**Issue by miriammichael** [iobroker-community-adapters/ioBroker.ring#211]
Hallo zusammen,

ich bekomme nach starten des Adapter regelmäige Javascript Fehlermeldungen

host.sh-server | 2022-02-13 21:54:01.124 | warn | instance system.adapter.ring.0 terminated due to SIGABRT
-- | -- | -- | --
host.sh-server | 2022-02-13 21:54:01.124 | error | Caught  by controller[0]: FATAL ERROR: Ineffective mark-compacts near heap  limit Allocation failed - JavaScript heap out of memory
host.sh-server | 2022-02-13 21:54:01.123 | error | Caught by controller[0]: <--- JS stacktrace --->
host.sh-server | 2022-02-13 21:54:01.123 | error | Caught  by controller[0]: [18515:0x5009da8]  5506909 ms: Mark-sweep 985.6  (1040.3) -> 979.2 (1041.0) MB, 2912.1 / 1.0 ms  (average mu = 0.288,  current mu = 0.309) task scavenge might not succeed
host.sh-server | 2022-02-13 21:54:01.123 | error | Caught  by controller[0]: [18515:0x5009da8]  5502693 ms: Mark-sweep 984.6  (1039.3) -> 978.2 (1040.3) MB, 3120.1 / 1.2 ms  (average mu = 0.268,  current mu = 0.299) task scavenge might not succeed
host.sh-server | 2022-02-13 21:54:01.122 | error | Caught  by controller[0]: [18515:0x5009da8]  5498244 ms: Mark-sweep 983.0  (1038.0) -> 977.1 (1039.3) MB, 3389.3 / 1.1 ms  (average mu = 0.236,  current mu = 0.161) task scavenge might not succeed
host.sh-server | 2022-02-13 21:54:01.117 | error | Caught by controller[0]: <--- Last few GCs --->

das es an Scripts liegt kann ich ausschließen. Der Fehler tritt nur auf wenn er Ring Adapter läuft

Versions:

    Adapter version: 1.2.8
    Node.js    v14.19.0
    NPM     6.14.16
    Operating system: Raspbian Buster

**Comment by theimo1221** [comment]
Stale issue
