### ISSUE TITLE
Ring Adapter Synology: EACCES permission denied

### ISSUE THREAD

**Issue by mandragora666** [iobroker-community-adapters/ioBroker.ring#217]
Hallo,

Ich hab aktuell ein Problem mit dem Speichern meiner Bilder und Videos vom Ring Adapter.
Hab den Adapter schon mal am Laufen gehabt und habe den ioBroker nun neu installiert.
Läuft alles unter Docker auf meiner Synology NAS

Nachdem ich den Ring Adapter installiert und den Pfad angegeben haben bekomm ich beim Starten diese Fehlermeldung.

EACCES permission denied..........................

Scheint als ob der Ring Adapter über Docker nicht in das gewünschte Verzeichnis schreiben darf0.
Irgendwie war das bei meiner alten Installation aber möglich.
Weiß leider nicht mehr was ich da gemacht habe.

Könntest du mir da eventuell behilflich sein.

Danke schon im Voraus
LG
mandragora

**Comment by Kurvenschreck** [comment]
Gleiches Problem, ich bekomme kein Zugriff auf mein NAS...  EACCES permission denied.......................... mkdir fehler. Ich habe die Rechte bereits komplett auf vollzugriff in meinem Qnap NAS Ordner gesetzt, aber bekomme jeweils den gleichen fehler.

**Comment by theimo1221** [comment]
Stale issue
