### ISSUE TITLE
Snapshot kann nicht erstellt werden

### ISSUE THREAD

**Issue by t1m02k16** [iobroker-community-adapters/ioBroker.ring#235]
Moin,
es ist mir nicht möglich einen Snapshot zu erstellen. 
Erstellter Ordner hat chmod777, Klingel wird angezeigt und funktioniert einwandfrei. 

`
ring.0 | 2022-04-03 18:28:26.134 | info | (4821) Ding Dong for Id ******* (on_demand, ringing)
-- | -- | -- | --
ring.0 | 2022-04-03 18:28:24.678 | error | (4821) Error within snapshotrequest: Error: Error setSanpshot()): Error: Could not create Snapshot for 115653720 in getSnapshot(). Error: Unable to get default network address
ring.0 | 2022-04-03 18:28:24.554 | info | (4821) Ding Dong for Id **********(on_demand, ringing)
ring.0 | 2022-04-03 18:28:23.414 | error | (4821) Error within snapshotrequest: Error: Error setSanpshot()): Error: Could not create Snapshot for 115653720 in getSnapshot(). Error: Unable to get default network address
ring.0 | 2022-04-03 18:27:50.427 | info | (4821) Starting Ring Device for Id ********
ring.0 | 2022-04-03 18:27:48.102 | info | (4821) Starting Adapter ring.0 in version 1.2.8
ring.0 | 2022-04-03 18:27:47.923 | info | (4821) starting. Version 1.2.8 in /opt/iobroker/node_modules/iobroker.ring, node: v12.22.11, js-controller: 4.0.21
ring.0 | 2022-04-03 18:27:46.723 | debug | (4821) Plugin sentry Initialize Plugin (enabled=true)
ring.0 | 2022-04-03 18:27:46.478 | debug | (4821) States connected to redis: 127.0.0.1:9000
ring.0 | 2022-04-03 18:27:46.419 | debug | (4821) States create User PubSub Client
ring.0 | 2022-04-03 18:27:46.414 | debug | (4821) States create System PubSub Client
ring.0 | 2022-04-03 18:27:46.371 | debug | (4821) Redis States: Use Redis connection: 127.0.0.1:9000
ring.0 | 2022-04-03 18:27:46.282 | debug | (4821) Objects connected to redis: 127.0.0.1:9001
ring.0 | 2022-04-03 18:27:46.252 | debug | (4821) Objects client initialize lua scripts
ring.0 | 2022-04-03 18:27:46.134 | debug | (4821) Objects create User PubSub Client
ring.0 | 2022-04-03 18:27:46.132 | debug | (4821) Objects create System PubSub Client
ring.0 | 2022-04-03 18:27:46.127 | debug | (4821) Objects client ready ... initialize now
ring.0 | 2022-04-03 19:28:26.134 | info | (4821) Ding Dong for Id 115653720 (on_demand, ringing)
`

![image](https://user-images.githubusercontent.com/19432480/161440364-4b38e248-3229-4502-b2b6-97aa6e5d41e8.png)

**Comment by actionbyte** [comment]
Ähnliches hier:
`<html><body>


ring.0 | 2022-04-19 06:36:07.974 | error | executeImmediateGuarded  resulted in Error: Error: Error setSnapshot()): Error: Could not create  Snapshot for 45011240 in getSnapshot(). Error: Snapshot for Kamera  Haustür (cocoa_camera - Stick Up Cam) failed to refresh after 70  attempts
-- | -- | -- | --
ring.0 | 2022-04-19 06:35:08.348 | info | Ding Dong for Id 45011240 (motion, ringing)


</body>
</html>`

Nach Installation der Beta 3 werden nun zus. keine Livestreams abgespeichert, was aber bei der Stable-Version noch ging (dort aber ebenfalls keine Snapshots).

**Comment by theimo1221** [comment]
@t1m02k16 und @actionbyte 
Bitte gerne (sofern für euch möglich) mit dem `V3` Rewrite neu prüfen, dürfte damit behoben sein.

**Comment by actionbyte** [comment]
@theimo1221 Mit der Beta 2.00 V3 hatte ich es getestet und die erzeugt zumindest Screenshots und AVIs.
Jetzt hatte ich heute aber auch ein leeres Backup-Verzeichnis, wie lange bleiben die alten Files da drin bis sie gelöscht werden?
Kann es sein das die Probleme beim Löschen auftreten?
Dennoch hatte ich jetzt meine node JS V14 auf V16.15.0 geupdatet um deine Beta 3.00 V4 zu installieren.
Damit bekomme ich den Adapter selber nun leider so rein gar nicht ans laufen.
Adapter wurde vom IOB wegen häufiger Neustarts automatisch deaktiviert.

`<html><body>


ring.0 | 2022-05-16 19:40:50.391 | warn | get state error: Connection is closed.
-- | -- | -- | --
ring.0 | 2022-05-16 19:40:50.390 | warn | get state error: Connection is closed.
ring.0 | 2022-05-16 19:40:50.388 | warn | get state error: Connection is closed.
ring.0 | 2022-05-16 19:40:50.384 | warn | Error Updating State cocoa_45011240.Info.battery_percentage to 0: DB closed
ring.0 | 2022-05-16 19:40:50.379 | warn | redis get ring.0.cocoa_130900175.Info.firmware, error - DB closed
ring.0 | 2022-05-16 19:40:50.378 | warn | redis get ring.0.cocoa_130900175.Info.latest_signal_category, error - DB closed
ring.0 | 2022-05-16 19:40:50.378 | warn | redis get ring.0.cocoa_130900175.Info.latest_signal_strength, error - DB closed
ring.0 | 2022-05-16 19:40:50.376 | warn | redis get ring.0.cocoa_130900175.Info.wifi_name, error - DB closed
ring.0 | 2022-05-16 19:40:50.376 | warn | redis get ring.0.cocoa_130900175.Info.battery_percentage_category, error - DB closed
ring.0 | 2022-05-16 19:40:50.374 | warn | get state error: Connection is closed.
ring.0 | 2022-05-16 19:40:49.962 | info | State value to set for "ring.0.cocoa_45011240.Info.id" has to be type "number" but received type "string"
ring.0 | 2022-05-16 19:40:49.958 | info | State value to set for "ring.0.cocoa_45011240.Info.id" has to be type "number" but received type "string"
ring.0 | 2022-05-16 19:40:49.955 | info | State value to set for "ring.0.cocoa_130900175.Info.id" has to be type "number" but received type "string"
ring.0 | 2022-05-16 19:40:49.950 | info | State value to set for "ring.0.cocoa_130900175.Info.id" has to be type "number" but received type "string"
ring.0 | 2022-05-16 19:40:49.859 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
ring.0 | 2022-05-16 19:40:49.857 | info | terminating
ring.0 | 2022-05-16 19:40:49.838 | error | Converting  circular structure to JSON    --> starting at object with  constructor 'Timeout'    \|     property '_idlePrev' -> object with  constructor 'TimersList'    --- property '_idleNext' closes the circle
ring.0 | 2022-05-16 19:40:49.838 | error | TypeError:  Converting circular structure to JSON    --> starting at object with  constructor 'Timeout'    \|     property '_idlePrev' -> object with  constructor 'TimersList'    --- property '_idleNext' closes the circle     at JSON.stringify (<anonymous>)    at Function.evaluateKind  (/opt/iobroker/node_modules/iobroker.ring/build/lib/ownRingDevice.js:105:68)     at Function.getFullId  (/opt/iobroker/node_modules/iobroker.ring/build/lib/ownRingDevice.js:72:24)     at RingApiClient.updateDev  (/opt/iobroker/node_modules/iobroker.ring/build/lib/ringApiClient.js:97:54)     at RingApiClient.refreshAll  (/opt/iobroker/node_modules/iobroker.ring/build/lib/ringApiClient.js:64:22)     at processTicksAndRejections  (node:internal/process/task_queues:96:5)    at async RingApiClient.init  (/opt/iobroker/node_modules/iobroker.ring/build/lib/ringApiClient.js:53:9)     at async RingAdapter.onReady  (/opt/iobroker/node_modules/iobroker.ring/build/main.js:80:9)
ring.0 | 2022-05-16 19:40:11.749 | info | State  value to set for "ring.0.cocoa_45011240.Info.id" has to be type  "number" but received type "string"     --> starting at object with  constructor 'Timeout'    \|     property '_idlePrev' -> object with  constructor 'TimersList'    --- property '_idleNext' closes the circle
ring.0 | 2022-05-16 19:40:11.747 | info | State value to set for "ring.0.cocoa_45011240.Info.id" has to be type "number" but received type "string"
ring.0 | 2022-05-16 19:40:11.603 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
ring.0 | 2022-05-16 19:40:11.601 | info | terminating
ring.0 | 2022-05-16 19:40:11.363 | error | Converting  circular structure to JSON    --> starting at object with  constructor 'Timeout'    \|     property '_idlePrev' -> object with  constructor 'TimersList'    --- property '_idleNext' closes the circle
ring.0 | 2022-05-16 19:40:11.362 | error | TypeError:  Converting circular structure to JSON    --> starting at object with  constructor 'Timeout'    \|     property '_idlePrev' -> object with  constructor 'TimersList'    --- property '_idleNext' closes the circle     at JSON.stringify (<anonymous>)    at Function.evaluateKind  (/opt/iobroker/node_modules/iobroker.ring/build/lib/ownRingDevice.js:105:68)     at Function.getFullId  (/opt/iobroker/node_modules/iobroker.ring/build/lib/ownRingDevice.js:72:24)     at RingApiClient.updateDev  (/opt/iobroker/node_modules/iobroker.ring/build/lib/ringApiClient.js:97:54)     at RingApiClient.refreshAll  (/opt/iobroker/node_modules/iobroker.ring/build/lib/ringApiClient.js:64:22)     at processTicksAndRejections  (node:internal/process/task_queues:96:5)    at async RingApiClient.init  (/opt/iobroker/node_modules/iobroker.ring/build/lib/ringApiClient.js:53:9)     at async RingAdapter.onReady  (/opt/iobroker/node_modules/iobroker.ring/build/main.js:80:9)
ring.0 | 2022-05-16 19:40:11.360 | error | unhandled  promise rejection: Converting circular structure to JSON    -->  starting at object with constructor 'Timeout'    \|     property  '_idlePrev' -> object with constructor 'TimersList'    --- property  '_idleNext' closes the circle
ring.0 | 2022-05-16 19:40:11.358 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
ring.0 | 2022-05-16 19:40:11.290 | error | Device with Type cocoa_floodlight not yet supported, please inform dev Team via Github
ring.0 | 2022-05-16 19:40:49.836 | error | unhandled promise rejection: Converting circular structure to JSON
ring.0 | 2022-05-16 19:40:49.835 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
ring.0 | 2022-05-16 19:40:49.771 | error | Device with Type cocoa_floodlight not yet supported, please inform dev Team via Github
ring.0 | 2022-05-16 19:40:47.953 | info | Initializing Api Client
ring.0 | 2022-05-16 19:40:47.882 | info | starting. Version 3.0.0-beta.4 in /opt/iobroker/node_modules/iobroker.ring, node: v16.15.0, js-controller: 4.0.23


</body>
</html>`

**Comment by theimo1221** [comment]
Nabend @actionbyte,

V3 kam noch nicht so gut mit deinem "besonderen" Flutlicht; bzw. präziser mit der Debug Ausgabe von z.B. unbekannten Geräten...

Mit `3.0.0-beta.7` sollte nicht nur das Problem behoben, sondern auch dein Flutlicht unterstützt sein.

Viele Grüße

Thiemo

**Comment by actionbyte** [comment]
@theimo1221 
Habe nach dem Versuch wieder die Stable V1.2.8 am laufen und wundere mich das nun alles wie am Schnürchen lüppt, alle Kameras zeichnen fröhlich Snapshots und Filme auf, auch die LampenCam.
Ich werde die nächsten Wochen nicht vor Ort sein um deine beta V7 testen zu können.
Trotzdem eine Frage und große Bitte:

Frage: Wann werden alte Snapshots und Livestreams gelöscht? Da sich eine Spinne vor der Linse 3 Tage bewegt hat ist mein lokales Verzeichnis nun mit 5 GB Filme und Fotos vollgelaufen.

Bitte: auch aus diesem Grund wäre es hervorragend wenn man die Dateien auf einem NAS abspeichern könnte und eben nicht lokal! Ebenso sehr praktisch wäre es, wenn es für jede Cam ein Unterverzeichnis geben würde!

Weitere Tests mit der Beta gerne mache ich gerne im Juni.

**Comment by theimo1221** [comment]
Guten Morgen @actionbyte,

die neue Version vergibt sofern nötig die passenden Rechte auf den neu erstellten Ordner, somit kann dies auch positiven Einfluss auf die alte Version haben.

Die neue Version löscht (sofern die Checkbox gesetzt ist) Dateien nachdem eine neue dieses Types für diese Kamera erhalten wurde.

> Bitte: auch aus diesem Grund wäre es hervorragend wenn man die Dateien auf einem NAS abspeichern könnte und eben nicht lokal! Ebenso sehr praktisch wäre es, wenn es für jede Cam ein Unterverzeichnis geben würde!

V3 legt Dateien pro Kamera jeweils in einen Ordner. Der angegebene Pfad (sofern er aufgelöst werden kann) kann theoretisch überall sein. Sprich auch ein Netzwerklaufwerk, Stick, etc..

Gute Reise

**Comment by actionbyte** [comment]
Hi @theimo1221 
danke für die schnelle Antwort! 

> Die neue Version löscht (sofern die Checkbox gesetzt ist) Dateien nachdem eine neue dieses Types für diese Kamera erhalten wurde.

Verstehe ich das richtig das dann immer nur ein File (Foto und Film) pro Kamera im Ordner verbleibt? 
Wäre für nachträgliche Beobachtungen nun gar nicht richtig für mich, eher löschen nach  X Tagen.

> Der angegebene Pfad (sofern er aufgelöst werden kann) kann theoretisch überall sein. Sprich auch ein Netzwerklaufwerk, Stick, etc..

Klasse! Aber wie ist der Pfad inkl. Berechtigungen anzugeben? User und PW?

BTW: Das ist hier schon offtopic und schade das ich die nächsten Tage keine Zeit zum Testen habe,
Weiteres später gerne per PM?!

**Comment by theimo1221** [comment]
Nabend @actionbyte,

Du kannst gerne über den ioBroker Discord Server direkt auf mich zugehen.

Bei der Option alte Löschen wird nur der neuste behalten.
Aber auch wenn man einen externen Pfad angibt, kann man trotzdem den letzten Screenshot/Livestream jeder kamera im respektiven binär statt abrufen sowie natürlich  über die url (bei aktivem web adapter).
Sprich wenn du einen externen Pfad mit passender Größe hast, dann solltest du das Löschen ausschalten können und einzig manuell ab und an "aufräumen".

Vg Thiemo
