### ISSUE TITLE
Auto-Renew refresh token 

### ISSUE THREAD

**Issue by kevinlieser** [iobroker-community-adapters/ioBroker.ring#236]
Is there a way to renew the refresh token automatically before it is invalid? Every few weeks (4/6/8?) the doorbell do not work in our house – thats the sign for me to renew the refresh token. Thats annoying.

Is there a solution for that to automatically renew this token?

**Comment by w0nk1** [comment]
I have to push this issue. I ran into the same problem every now an then. It is indeed very problematic. Is there any solution available soon?

**Comment by theimo1221** [comment]
Morning @w0nk1, Morning @kevinlieser,

This is properly handled in `v3.0.0-beta.11`
