### ISSUE TITLE
No delete of old snapshot and livestream

### ISSUE THREAD

**Issue by brunsheinz** [iobroker-community-adapters/ioBroker.ring#240]
**Describe the bug**  
Old snapshot and livestream files will not delete

**To Reproduce**  
1. Go to 'Instanzeinstellungen'
2. Click on 'Snapshot'

**Expected behavior**  
No delete of Files Snapshot on /mnt/usb0/Ringdoorbell

**Screenshots & Logfiles**  
![ring](https://user-images.githubusercontent.com/95573353/164645159-3555d5cd-3edc-401b-8949-0cae43e13682.jpg)

If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <1.2.8>
 - JS-Controller version: <14.19.1> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by theimo1221** [comment]
@brunsheinz If it would be okay for you please check again with `V3`, as that version has quite a different file handling.

**Comment by brunsheinz** [comment]
I installed version 3. and restarted Ring Adapter. Old files were not deleted. Then the USB stick was reformatted and set up with Ringdoorbell files. My backup is still too big. In /opt/iobroker/iobroker-data/files there is still a file of : 821.0 MiB [##########] /ring.0
When I run the adapter this file gets bigger every day.

**Comment by theimo1221** [comment]
Morning @brunsheinz,

The adapter deletes only that file listed in the device-respective `ring.0.doorbell_55xxx61.Snapshot.snapshot_file` state.
So in regards to old files (especially those created with earlier versions) you'd have to clear those folders manually once.

What is your configuration here?
![image](https://user-images.githubusercontent.com/20605452/168771373-5afee0e1-7ef7-4475-adaa-cd6359d25c06.png)

Additionally (if I understand your storage plan correct) does the user running ioBroker have sufficient permissions on the external drive to delete files?

Best Regards 

Thiemo

**Comment by brunsheinz** [comment]
Hi
Here my configuration:
I save the snapshots and live stream on the USB stick in the Raspberry Pi. The files could be deleted monthly without problems.
What bothers me is below
 /opt/iobroker/iobroker-data/files/ring.0 /..
    1.0 GiB [##########] /doorbell_98487415
    2.1 MiB [ ] _data.json
The files are not deleted and the backup is therefore larger every day. It also seems that the files are stored under /opt/iobroker/iobroker-data/files in addition to the USB stick
[]
![mcstream1](https://user-images.githubusercontent.com/95573353/169291999-10f507cb-93f6-432b-bb32-fd4981194b11.jpg)
(url)
[
![Screenshot (394)](https://user-images.githubusercontent.com/95573353/169292211-1e7c374c-3870-4f7f-82ca-2de1f5d651ad.jpg)
](url)
What happens if I delete the directory ..../ring.0

**Comment by brunsheinz** [comment]
Hi
So, I deleted all files in the /ring.0 directory. Let's see how the backup develops over the next few days

**Comment by theimo1221** [comment]
Stale issue
