### ISSUE TITLE
RING 3.0.0-beta.7: Email und Passwort können nicht eingegeben werden

### ISSUE THREAD

**Issue by michihorni** [iobroker-community-adapters/ioBroker.ring#254]
**Describe the bug**  
Die Emailadresse und Passwort können nicht eingegeben werden

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 3.0.0-beta.7
 - JS-Controller version: 4.0.23
 - Node version: 14.18.2
 - Operating system: Windows 10
![Unbenannt](https://user-images.githubusercontent.com/27429377/168837532-4f9b5cb3-65e5-4fb0-88c2-d314b562d63b.PNG)

**Additional context**

**Comment by theimo1221** [comment]
Guten Tag @michihorni 

Seid Ring die Token erzwingt (ermittlung mit `npx -p ring-client-api ring-auth-cli`) werden die Infos (email und passwort) nicht benötigt, bzw. helfen dem adapter nicht.

Zu eurer Sicherheit sind die Felder deshalb entfernt.

Vg Thiemo

**Comment by michihorni** [comment]
Hallo Thiemo

danke für den Hinweis, habe es dann mit den Two Face Auth versucht, so wie ich es mit der letzten bei mir installierten 2.0.0-beta.4 gemacht habe.

Die Rückmeldung habe ich dann im Adapter eingetragen und gespeichert. Der Adapter schaltet sich sofort wieder aus. Es gibt auch kein LOG Eintrag
 

Mit freundlichen Grüßen
Michael Horn

 
 

Gesendet: Dienstag, 17. Mai 2022 um 16:44 Uhr
Von: "Thiemo Hoffmann" ***@***.***>
An: "iobroker-community-adapters/ioBroker.ring" ***@***.***>
Cc: "michihorni" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [iobroker-community-adapters/ioBroker.ring] RING 3.0.0-beta.7: Email und Passwort können nicht eingegeben werden (Issue #254)


 

Guten Tag @michihorni

Seid Ring die Token erzwingt (ermittlung mit npx -p ring-client-api ring-auth-cli) werden die Infos (email und passwort) nicht benötigt, bzw. helfen dem adapter nicht.

Zu eurer Sicherheit sind die Felder deshalb entfernt.

Vg Thiemo

**Comment by theimo1221** [comment]
Nabend @michihorni,

Okay, das ist komisch....
Sofern der Token falsch wäre müsste eigentlich folgende Meldung im Log auftauchen:
`Invalid Refresh Token, please follow steps provided within Readme to generate a new one`

Ansonsten gerne unter Instanzen die Ring Instanz auf Logstufe `Debug` oder `Silly` stellen (ggf. vorher oben auf Expertenmodus drücken) und dann bei Protokoll eben auf Ring und bis Logstufe Silly filtern, eigentlich müsste da zumindest irgendwas stehen (der Adapter verabschiedet sich eigentlich nicht lautlos....)

Falls da steht, dass der Token nicht valide ist, könnte je nach von dir verwendeter Kommandozeile der Token Zeilenumbrüche oder außen rum Anführungszeichen haben, die müssten raus.

VG Thiemo

**Comment by michihorni** [comment]
Hallöchen

ich habe auch mal die LOG Stufen geändert. Beim Starten des Adapters blinkt er nur kurz grün auf und ist dann "AUS" also grau. Es kommt auch keine LOG Meldung.

Ich habe jetzt wieder die Version 2.0.0-beta.3 installiert. Die klappt. 
 

Mit freundlichen Grüßen
Michael Horn

 
 

Gesendet: Dienstag, 17. Mai 2022 um 18:30 Uhr
Von: "Thiemo Hoffmann" ***@***.***>
An: "iobroker-community-adapters/ioBroker.ring" ***@***.***>
Cc: "michihorni" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [iobroker-community-adapters/ioBroker.ring] RING 3.0.0-beta.7: Email und Passwort können nicht eingegeben werden (Issue #254)


 

Nabend @michihorni,

Okay, das ist komisch....
Sofern der Token falsch wäre müsste eigentlich folgende Meldung im Log auftauchen:
Invalid Refresh Token, please follow steps provided within Readme to generate a new one

Ansonsten gerne unter Instanzen die Ring Instanz auf Logstufe Debug oder Silly stellen (ggf. vorher oben auf Expertenmodus drücken) und dann bei Protokoll eben auf Ring und bis Logstufe Silly filtern, eigentlich müsste da zumindest irgendwas stehen (der Adapter verabschiedet sich eigentlich nicht lautlos....)

Falls da steht, dass der Token nicht valide ist, könnte je nach von dir verwendeter Kommandozeile der Token Zeilenumbrüche oder außen rum Anführungszeichen haben, die müssten raus.

VG Thiemo

**Comment by theimo1221** [comment]
Guten Abend @michihorni,

habe deine erste Nachricht nochmal genauer gelesen, du hast node.js v14 im Einsatz. 

[Die Ring Library unterstützt nur noch Node V16](https://github.com/dgreif/ring/releases/tag/v11.0.0)
Es kann sein, dass ioBroker die für diesen Adapter falsche node Version erkennt und dich deshalb den Adapter garnicht erst starten lässt.... Dementsprechend auch keine Log Nachrichten.

VG Thiemo

**Comment by michihorni** [comment]
Hallo ja ich habe Node 14, in der Zwischenzeit hatte ich mal einen Raspberry installiert und versucht den RING Adapter zu installieren, dort kam dan der Hinweis das Node 16 erforderlich ist.

Ist Node 16 stabil?
 

Mit freundlichen Grüßen
Michael Horn

 
 

Gesendet: Dienstag, 17. Mai 2022 um 21:25 Uhr
Von: "Thiemo Hoffmann" ***@***.***>
An: "iobroker-community-adapters/ioBroker.ring" ***@***.***>
Cc: "michihorni" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [iobroker-community-adapters/ioBroker.ring] RING 3.0.0-beta.7: Email und Passwort können nicht eingegeben werden (Issue #254)


 

Guten Abend @michihorni,

habe deine erste Nachricht nochmal genauer gelesen, du hast node.js v14 im Einsatz.

Die Ring Library unterstützt nur noch Node V16
Es kann sein, dass ioBroker die für diesen Adapter falsche node Version erkennt und dich deshalb den Adapter garnicht erst starten lässt.... Dementsprechend auch keine Log Nachrichten.

VG Thiemo

**Comment by theimo1221** [comment]
@michihorni :
<img width="776" alt="image" src="https://user-images.githubusercontent.com/20605452/168898088-c11a3b92-1863-4a0b-95f7-202aecacb6cf.png">


Node V16 ist die aktuell aktive Langzeitsupportversion, während der offizielle LTS für node 14 April nächsten Jahres ausläuft (V18 LTS startet aber auch erst im Oktober)

**Comment by michihorni** [comment]
Moin 

ich habe nun Node 16.15 installiert.

Leider lässt der Ring Adapter nicht installieren:

$ ./iobroker upgrade ring
Update ring from @2.0.0-beta.3 to @3.0.0-beta.8
ERROR: TypeError: Class extends value undefined is not a constructor or null    at Object.<anonymous> (C:\iobroker\SmartHome\nodejs\node_modules\npm\node_modules\socks-proxy-agent\dist\agent.js:114:44)    at Module._compile (node:internal/modules/cjs/loader:1105:14)    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)    at Module.load (node:internal/modules/cjs/loader:981:32)    at Function.Module._load (node:internal/modules/cjs/loader:822:12)    at Module.require (node:internal/modules/cjs/loader:1005:19)    at require (node:internal/modules/cjs/helpers:102:18)    at Object.<anonymous> (C:\iobroker\SmartHome\nodejs\node_modules\npm\node_modules\socks-proxy-agent\dist\index.js:5:33)    at Module._compile (node:internal/modules/cjs/loader:1105:14)    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)    at Module.load (node:internal/modules/cjs/loader:981:32)    at Function.Module._load (node:internal/modules/cjs/loader:822:12)    at Module.require (node:internal/modules/cjs/loader:1005:19)    at require (node:internal/modules/cjs/helpers:102:18)    at Object.<anonymous> (C:\iobroker\SmartHome\nodejs\node_modules\npm\node_modules\make-fetch-happen\lib\agent.js:171:25)    at Module._compile (node:internal/modules/cjs/loader:1105:14)TypeError: Class extends value undefined is not a constructor or null    at Object.<anonymous> (C:\iobroker\SmartHome\nodejs\node_modules\npm\node_modules\socks-proxy-agent\dist\agent.js:114:44)    at Module._compile (node:internal/modules/cjs/loader:1105:14)    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)    at Module.load (node:internal/modules/cjs/loader:981:32)    at Function.Module._load (node:internal/modules/cjs/loader:822:12)    at Module.require (node:internal/modules/cjs/loader:1005:19)    at require (node:internal/modules/cjs/helpers:102:18)    at Object.<anonymous> (C:\iobroker\SmartHome\nodejs\node_modules\npm\node_modules\socks-proxy-agent\dist\index.js:5:33)    at Module._compile (node:internal/modules/cjs/loader:1105:14)    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)    at Module.load (node:internal/modules/cjs/loader:981:32)    at Function.Module._load (node:internal/modules/cjs/loader:822:12)    at Module.require (node:internal/modules/cjs/loader:1005:19)    at require (node:internal/modules/cjs/helpers:102:18)    at Object.<anonymous> (C:\iobroker\SmartHome\nodejs\node_modules\npm\node_modules\make-fetch-happen\lib\agent.js:171:25)    at Module._compile (node:internal/modules/cjs/loader:1105:14)Error trying to check npm version: Command failed: npm -vTypeError: Class extends value undefined is not a constructor or null    at Object.<anonymous> (C:\iobroker\SmartHome\nodejs\node_modules\npm\node_modules\socks-proxy-agent\dist\agent.js:114:44)    at Module._compile (node:internal/modules/cjs/loader:1105:14)    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)    at Module.load (node:internal/modules/cjs/loader:981:32)    at Function.Module._load (node:internal/modules/cjs/loader:822:12)    at Module.require (node:internal/modules/cjs/loader:1005:19)    at require (node:internal/modules/cjs/helpers:102:18)    at Object.<anonymous> (C:\iobroker\SmartHome\nodejs\node_modules\npm\node_modules\socks-proxy-agent\dist\index.js:5:33)    at Module._compile (node:internal/modules/cjs/loader:1105:14)    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)    at Module.load (node:internal/modules/cjs/loader:981:32)    at Function.Module._load (node:internal/modules/cjs/loader:822:12)    at Module.require (node:internal/modules/cjs/loader:1005:19)    at require (node:internal/modules/cjs/helpers:102:18)    at Object.<anonymous> (C:\iobroker\SmartHome\nodejs\node_modules\npm\node_modules\make-fetch-happen\lib\agent.js:171:25)    at Module._compile (node:internal/modules/cjs/loader:1105:14)TypeError: Class extends value undefined is not a constructor or null    at Object.<anonymous> (C:\iobroker\SmartHome\nodejs\node_modules\npm\node_modules\socks-proxy-agent\dist\agent.js:114:44)    at Module._compile (node:internal/modules/cjs/loader:1105:14)    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)    at Module.load (node:internal/modules/cjs/loader:981:32)    at Function.Module._load (node:internal/modules/cjs/loader:822:12)    at Module.require (node:internal/modules/cjs/loader:1005:19)    at require (node:internal/modules/cjs/helpers:102:18)    at Object.<anonymous> (C:\iobroker\SmartHome\nodejs\node_modules\npm\node_modules\socks-proxy-agent\dist\index.js:5:33)    at Module._compile (node:internal/modules/cjs/loader:1105:14)    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)    at Module.load (node:internal/modules/cjs/loader:981:32)    at Function.Module._load (node:internal/modules/cjs/loader:822:12)    at Module.require (node:internal/modules/cjs/loader:1005:19)    at require (node:internal/modules/cjs/helpers:102:18)    at Object.<anonymous> (C:\iobroker\SmartHome\nodejs\node_modules\npm\node_modules\make-fetch-happen\lib\agent.js:171:25)    at Module._compile (node:internal/modules/cjs/loader:1105:14)!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!Aborting install because the npm version could not be checked!Please check that npm is installed correctly.Use "npm install -g ***@***.***" or "npm install -g ***@***.***" to install a supported version.You need to make sure to repeat this step after installing an update to NodeJS and/or npm!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
ERROR: process exited with code 30

 

 

Auch "npm install -g ***@***.***" klappt nicht mehr. Ich werde nun ein Backup einspielen

 

Mit freundlichen Grüßen
Michael Horn

 
 

Gesendet: Dienstag, 17. Mai 2022 um 21:25 Uhr
Von: "Thiemo Hoffmann" ***@***.***>
An: "iobroker-community-adapters/ioBroker.ring" ***@***.***>
Cc: "michihorni" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [iobroker-community-adapters/ioBroker.ring] RING 3.0.0-beta.7: Email und Passwort können nicht eingegeben werden (Issue #254)


 

Guten Abend @michihorni,

habe deine erste Nachricht nochmal genauer gelesen, du hast node.js v14 im Einsatz.

Die Ring Library unterstützt nur noch Node V16
Es kann sein, dass ioBroker die für diesen Adapter falsche node Version erkennt und dich deshalb den Adapter garnicht erst starten lässt.... Dementsprechend auch keine Log Nachrichten.

VG Thiemo

**Comment by theimo1221** [comment]
Mahlzeit @michihorni 

hast du vor dem update von node-js `iobroker stop` ausgeführt? Ein Upgrade von node-js während ioBroker läuft ist nicht so gut für das system.

**Comment by michihorni** [comment]
Na klar ;-)
 

Mit freundlichen Grüßen
Michael Horn

 
 

Gesendet: Mittwoch, 18. Mai 2022 um 13:10 Uhr
Von: "Thiemo Hoffmann" ***@***.***>
An: "iobroker-community-adapters/ioBroker.ring" ***@***.***>
Cc: "michihorni" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [iobroker-community-adapters/ioBroker.ring] RING 3.0.0-beta.7: Email und Passwort können nicht eingegeben werden (Issue #254)


 

Mahlzeit @michihorni

hast du vor dem update von node-js iobroker stop ausgeführt? Ein Upgrade von node-js während ioBroker läuft ist nicht so gut für das system.
