### ISSUE TITLE
Device with Type lpd_v4 not yet supported

### ISSUE THREAD

**Issue by Vijabei** [iobroker-community-adapters/ioBroker.ring#261]
```
ring.0 | 2022-05-24 21:13:46.868 | error | Device with Type lpd_v4 not yet supported, please inform dev Team via Github
ring.0 | 2022-05-24 21:13:46.855 | error | Device with Type lpd_v4 not yet supported, please inform dev Team via Github
ring.0 | 2022-05-24 21:13:44.495 | info | Initializing Api Client
ring.0 | 2022-05-24 21:13:44.432 | info | starting. Version 3.0.0-beta.9 in /opt/iobroker/node_modules/iobroker.ring, node: v16.15.0, js-controller: 4.0.23
```

Joa, da steht, ich soll's melden ;-)

Nach dem Update auf node16 und der dann erfolgten Anmeldung alles gut. Kann das der Grund sein, warum keine Videos und Snapshots gespeichert werden?

Grüße
Vija

**Comment by theimo1221** [comment]
Nabend @Vijabei,

Gerne mit der neusten Version probieren, es müsste nun gehen, außer die haben softwareseitig an der Doorbell grundlegendes gegenüber der lpd_v2 geändert.
Sofern dass der Fall wäre bitte bei dem Gerät einmal die Lognachricht nach einem Druck auf den Debug_Request State bei dem Gerät hier anhängen.

VG Thiemo

**Comment by Vijabei** [comment]
Nabend @theimo1221,

auf den ersten Blick scheint es zu funktionieren. Ein Testvideo ist erstellt durch "Bewegung erkannt".
Ich bin noch am Anfang, IO-Broker und dieses Projekt kennenzulernen. Mal sehen, was da noch kommt ;-)

VG
Vija
