### ISSUE TITLE
Device with Type doorbell_graham_cracker not yet supported

### ISSUE THREAD

**Issue by miggel88** [iobroker-community-adapters/ioBroker.ring#262]
I am using the Ring Doorbell wired and get this failure when installing the new v3.0.0-beta.11
Had no problems with this Device in v.2

**Comment by theimo1221** [comment]
Hello @miggel88,

this should be resolved with https://github.com/iobroker-community-adapters/ioBroker.ring/releases/tag/v3.0.0-beta.12

Best regards 

Thiemo

**Comment by miggel88** [comment]
Thank you for the quick support, its working now!
