### ISSUE TITLE
Nach Update auf Version 3.x und Neuaufbau der Objekte fehlen die Infos zu Batteriestatus und die URL-Variablen

### ISSUE THREAD

**Issue by evazoe1410** [iobroker-community-adapters/ioBroker.ring#263]
**Describe the bug**  

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by evazoe1410** [comment]
Die vor Adapter-Version 3.x gerätespezifischen Infos (Batteriezustand, Snapshot_URL, Livestream_URL) werden aktuell direkt unter ring.0 mit leeren Werten geschrieben, bei den aktiven Geräten fehlen die Objekte.

**Comment by theimo1221** [comment]
Nabend @evazoe1410,

In V3 sind die Sachen nun korrekter in jeweiligen Ordner, z.B. `ring.0.doorbell_xx.Info.battery_percentage`.

VG Thiemo

**Comment by evazoe1410** [comment]
Hallo,
vielen Dank für die schnelle Rückmeldung.
Bei mir ist es nach dem Update auf 3.x eben nicht mehr so. Die Ordner z.B. Info sind zwar erstellt, haben aber keine Objekte.
mfG

**Comment by theimo1221** [comment]
Es scheint als hätte sich ein Fehlerteufel im letzten Update eingeschlichen, was sich aber wohl primär auf Neuinstallationen von V3 auswirkt....

**Comment by evazoe1410** [comment]
ich habe nach Update des NodeJS auf 16.x auch ein Update des Adapter gemacht, keine Neu-Installation.

**Comment by evazoe1410** [comment]
finde aber die Entwicklung überaus positiv, denn so wie es aussieht wurde die DNS-Last deutlich reduziert und auch die jetzt funktionierende Löschung der Snapshot-Dateien sind wichtige Schritte.

**Comment by theimo1221** [comment]
So, mit `3.0.0-beta.12` dürfte das Problem behoben sein....

Danke für die Meldung @evazoe1410 und melde dich gerne bei weiteren Auffälligkeiten.
