### ISSUE TITLE
Snapshots werden nicht aktualisiert, nur bei Neustart der Instanz

### ISSUE THREAD

**Issue by evazoe1410** [iobroker-community-adapters/ioBroker.ring#269]
nach Update auf Version 3.x Beta12 ist die Objektstruktur wieder in Ordnung. Die Livestreams werden wohl auch bei Bewegung und Aufzeichnung aktualisiert. Snapshots werden alle bei einem Neustart der Instanz aktualisiert, dann aber nicht mehr. Ist das so gewollt, muss man das selbst über einen Request auslösen ?

**Comment by theimo1221** [comment]
Nabend @evazoe1410,

In V3 gibt es 3 Situationen in denen Livestreams&Snapshots getätigt werden:

1. Beim Adapterstart
2. Auf Anfrage im request State
3. Bei Events (Bewegung, Mensch-Erkannt, Ding), dann zuerst den Livestream anschließend den Snapshot

Ich kann aber bestätigen, dass aktuell scheinbar Punkt 3 nicht richtig greift....

Werde ich mir genauer anschauen

**Comment by theimo1221** [comment]
@evazoe1410 Gerne mit der neusten Version erneut versuchen.

Ich hatte bei mir eben sogar das Phänomen, dass der api token zwar noch gültig ist, aber keine Notifications mehr gemeldet werden, dies ließ sich nur durch eine Neuerstellung des Token beheben.
