### ISSUE TITLE
npm version lässt sich nicht installieren

### ISSUE THREAD

**Issue by denjo1982** [iobroker-community-adapters/ioBroker.ring#272]
die npm version lässt sich nicht installieren nur die stable version

**Comment by theimo1221** [comment]
Moin @denjo1982 

Hast du node v16 auf deinem System?

Vg Thiemo

**Comment by denjo1982** [comment]
ja

**Comment by theimo1221** [comment]
Ohne irgendeine Fehlermeldung oder nähere Infos kann ich schwer sagen woran es liegt...
