### ISSUE TITLE
Snapshot kann nicht erstellt werden

### ISSUE THREAD

**Issue by EisTee94** [iobroker-community-adapters/ioBroker.ring#282]
Hallo Freunde, vielen Dank fürs weiterentwickeln und basteln. 
Leider meldet mir die Log immer wieder "Device xy ("Name"): Could not create snapshot"
In den Objekten sehe ich, dass der DP "moment" aktualisiert wird. Der DP "snapshot_file" jedoch nicht.

So richtig was spannendes packt die Log nach vielen Versuchen nicht aus. Es wird schlichtweg gar nichts geloggt.

`<html><body>

ring.0 | 2022-06-17 21:17:18.796 | info | Device 136786295 ("Haustür"): Could not create snapshot
-- | -- | -- | --
ring.0 | 2022-06-17 21:17:18.711 | info | Device 136786295 ("Haustür"): Could not create snapshot
ring.0 | 2022-06-17 21:17:18.709 | info | Couldn't get Snapshot from api.

</body>
</html>`

**Comment by theimo1221** [comment]
Hallo @EisTee94,

Stell gerne einmal die Logstufe auf Debug oder silly, dann dürfte die Fehlermeldung eigentlich etwas ausführlicher sein.

Vg Thiemo

**Comment by EisTee94** [comment]
Hallo @theimo1221 
ich hab ein wenig rumprobiert. scheint wohn ein Rechte Fehler gewesen zu sein. Jetzt wird auf die Request sauber ein Bild erstellt. Funktioniert einwandfrei ! 

Vielen Dank :)
