### ISSUE TITLE
Version 3.0.4 reagiert nicht

### ISSUE THREAD

**Issue by denjo1982** [iobroker-community-adapters/ioBroker.ring#283]
Die Version 3.0.4 und 3.0.3 reagieren nicht damit meine ich der Adapter ist grün aber wenn es zb klingelt passiert einfach gar nix.
Auch im Log steht nix
Version 3.0.1 läuft tadellos.

Node.js v16.15.1
js controller 4.0.23
npm 8.11

**Comment by erniecs** [comment]
Das selbe Problem habe ich auch

**Comment by theimo1221** [comment]
Duplikat zu #284
