### ISSUE TITLE
Kein Datenpunkt für "Klingeln"

### ISSUE THREAD

**Issue by EisTee94** [iobroker-community-adapters/ioBroker.ring#284]
Ich nochmal, eigentlich möchte ich die Issues hier wirklich nicht vollspammen, 
aber ich finde keinen Datenpunkt, in dem mir das Betätigen der Klingel angezeigt wird.

Kann mir da vielleicht jemand ganz kurz helfen...
anbei nen Screenshot meiner Objects:
![grafik](https://user-images.githubusercontent.com/91722497/174479421-e88bf3b5-14e7-428c-959d-bc8789caa7cc.png)

**Comment by theimo1221** [comment]
Hallo @EisTee94,
Der Datenpunkt wird erst angelegt, wenn das erste Mal ein solches Event ausgelöst wird, anschließend sollte es unter Events zu finden sein.

Vg Thiemo

**Comment by EisTee94** [comment]
Seltsam - genau das hab ich vermutet, bin dann extra zur Tür und hab geklingelt. Angelegt wurde leider nichts. 
Unter History/Kind wurde auch auf Ding gesetzt und ein entsprechender Clip wurde erzeugt und hinterlegt.

Nur der DP in Events wurde nicht angelegt.

**Comment by theimo1221** [comment]
Hast du ggf. in der App manche Benachrichtigungen deaktiviert? Das beeinflusst zum Teil auch die Informationen, die dieser Adapter erhält.

Ansonsten versuch mal einen frischen Token zu generieren.

**Comment by EisTee94** [comment]
Deaktiviert sind nur die Benachrichtigungen für Bewegung. 2 Fam Haus - das ding würde ständig bimmeln :'D

ich versuche das sofort nochmal durchzuspielen, und berichte ob sich was geändert hat.

Danke für deine Mühe.

**Comment by theimo1221** [comment]
Die ringapi Bibliothek von dgreif lässt in Bezug auf Events folgende zu:
- Bewegung
- Klingel
- Benachrichtigung

Wir reagieren auf alle 3 separat, vgl. in deinem Screenshot Motion=false zusätzlich gibt es noch den Punkt doorbellPressed und mehrere Punkte für die Benachrichtigung.

Es gab in dem repository der Ring-Bibliothek bereits gewisse Diskussionen über fehlende Reaktionen wenn die Benachrichtigung in der App aus ist.

**Comment by EisTee94** [comment]
Versuch: Alle Benachrichtungen sind an. Chrime ist NICHT stumm.
Token frisch erzeugt. Nach klingeln an der Tür weiterhin NUR DP motion.

In Histroy wird weiterhin der Created at / URL / Kind aktualisiert und läuft.

**Comment by theimo1221** [comment]
Die Historie aktualisiert sich separat. 
Zum Teil hilft es auch auf der Ring Website alle anderen ioBroker Instanzen zu entfernen, weil Ring sonst zum Teil durcheinander kommt.

**Comment by EisTee94** [comment]
Bei meinen Test wurde mir die Benachrichtung über Ring " Bewegeung" geschickt. Aber der DP Motion hat sich nicht aktualisiert.

**Comment by theimo1221** [comment]
Okay, also erhält deine ioBroker Instanz gar keine Events... auch das liegt leider eher an ring.

Hier hat es zuletzt geholfen den adapter zu stoppen, alle verknüpften iobroker instanzen auf der ring website zu löschen und dann mit einem frischen Token den adapter wieder zu starten.

**Comment by EisTee94** [comment]
ich werde die tage das projekt nochmal komplett neu angehen.
Die gesamte Instanz / Adapter deinstallieren - auf Ring alle Clients löschen und dann nochmal neu in Ruhe einpflegen.
Ich berichte hier. Vielleicht liegt der fehler ja irgendwo im detail.

Vielen vielen Dank für deine Mühe..

**Comment by theimo1221** [comment]
Hier so sollte der Log (mit Level Debug) bei Events aussehen:
![image](https://user-images.githubusercontent.com/20605452/174486108-596d30be-3b2b-432f-a179-ca7b20bef741.png)

**Comment by philipp1987** [comment]
Hey @theimo1221 , habe heute die neue Ring-Adapter Version auf ioBroker installiert und zuerst auch im Event-Ordner, außer "motion", keine Datenpunkte gehabt. Jetzt hab ich sämtliche Clients auf der Ring Homepage gelöscht, in ioBroker den Ring-Adapter deinstalliert und anschließen den gesamten Ordnerbaum gelöscht. Nach einer Neuinstallation des Adapters, einrichten und 1x klingeln kamen die entsprechenden Datenpunkte im Eventordner (created_at, doorbell, message, motion und type) Leider wird keiner dieser Datenpunkte bei nochmaligen betätigen der Klingel aktualisiert. Ich werde es nachher nochmal probieren aber erstmal ist das komisch. Wurde aus "state" = "type" und aus "ringing" = "ding"?

**Comment by EisTee94** [comment]
Hallo @theimo1221 
Hallo @philipp1987 

Ich hab den Weg von @philipp1987 mal nachgebaut. 
- Instanz & Adapter löschen
- alle Clients von der Website entfernen
- Adapter auf Version 3.0.1 installieren
- neuer Token
- Klingeln
et viola - Datenpunkte werden erstellt und aktualisieren sich bei motion oder ring! 

Fazit in V 3.0.1 funktioniert das! Update habe ich bisher nich getestet.

Bezug auf den EDIT von @philipp1987 : Bei mir ändert der DP Doorbell dauerhaft auf True und setzt sich erst bei Motion wieder zurück.

VG

**Comment by theimo1221** [comment]
@erniecs Die Ring-Api hat noch keine eventbasierte Erkennung/Überwachung des Location Modes.
Dementsprechend können wir nur alle x Minuten abfragen, was der aktuelle Location Mode ist --> Daher nicht Live Aktualisierung in ioBroker

**Comment by erniecs** [comment]
Der Location Mode, ist nicht so wichtig, aber warum die Bewegungserkennung und das Klingeln nicht erkannt werden.
Zudem habe ich vom ioBroker die Meldung bekommen, dass der Ring Adapter immer wieder abstürzt und sich neu startet und er auf Grund dessen deaktiviert wid.

**Comment by theimo1221** [comment]
@erniecs Die Meldung mit den Abstürzen kommt auch wenn initial z.B. ein falscher/ungültiger Api-Key angegeben ist. Das liegt dann nicht am Adapter selbst.

Gleichermaßen ist für die Bewegungserkennung mehreres nötig:

1. Ring muss das Event an das verknüpfte Gerät (in unserem Falle die Api Bibliothek https://github.com/dgreif/ring )
2. Die Bibliothek muss das Event passend verarbeiten und an den vorgesehenen Stellen "weiterreichen"
3. Dieser Adapter muss entsprechend reagieren.

Sofern 2. das Event meldet wird direkt eine passende Lognachricht ausgelöst, dies ist auch nicht abhängig von irgendwelchen Sonnenständen, Mondphasen oder Zufällen. Sobald da etwas kommt wird es von diesem Adapter auch verarbeitet.

Meist scheitert es irgendwo zwischen Ring und der API. Z.B. weil Ring denkt, dass die App (sogesehen ist der ioBroker Adapter aus Ring Sicht auch wie deren App) gar nicht aktiv ist, bereits mit Benachrichtigungen voll ist, ....
Es könnte sogar sein, dass Ring teilweise manche besonders ressourcenintensive Apps blockiert (unser Adapter beansprucht deren Server mehr als deren eigenen Apps).

Meines Wissens nach hilft nur die verknüpften Geräte zu entfernen und einen neuen Api Key zu generieren, anschließend muss man hoffen, dass Ring diese Instanz als eine "gute" anerkennt.
Ich hatte die beschriebenen Probleme mit einer Instanz bei mir auch und nun läuft sie seit einiger Zeit (mehrere Wochen) ohne Probleme und hat (wegen Gartenarbeiten) an manchen Tagen dreistellige Eventmengen verarbeitet

**Comment by erniecs** [comment]
Das ist mir soweit alles klar, der Adapter lief auch einwandfrei (bis ich auf V3 upgedatet habe). Ich habe allerdings direkt auf 3.0.4 upgedatet. Da ich gelesen hab in der 3.0.1 würde es noch funktionieren habe ich den Adapter gelöscht und wollte die 3.0.1 installieren. Wenn ich das mache installiert er mir den Adapter aber unter Instanzen ist nichts zu finden. Also habe ich wieder die 3.0.4 drauf gemacht und jeweils auch immer schön auf der Ring Webseite vor der Anmeldung schön das Gerät gelöscht. Den Datenpunkt Motion legt er zwar an wird aber nicht aktualisiert und den Punkt für´s Klingeln macht er gar nicht.
Ich logg mich mal neu an und schau mal was dann passiert.

**Comment by erniecs** [comment]
Viel Dank für deine Infos, ich werde das Ganze jetzt nochmal beobachten. Wenn ich das aber richtig verstehe, liegt das ganze Problem an der Ring Api ?
Ich glaube ich muss mir da mal ne Alternative zur Ring überlegen, da man den Videostream ja auch nicht vernünftig abgreifen kann.

**Comment by theimo1221** [comment]
### **Disclaimer folgendes ist persönliche Vermutung/Meinung** 
Der Backend Code von Ring selbst ist nicht zugänglich, aber wenn ich die wäre würde ich aus folgenden Gründen Api Zugriffe zum Teil einschränken wollen:
1. Weniger Gewinn mit `Ring-Protect Abos`
2. Mehr Serverbelastung

Über die Website kann man kaum/schwer alle Videos runterladen, sprich der 180 Tage Speicher wird attraktiver. Aber dieser Punkt ist hinfällig wenn du ein Programm hast was wie dieser Adapter alles direkt runterlädt.

Normale Ring App Benutzer werden nicht alle paar Minuten bei Ring neue Daten anfordern, sondern die App eher sporadisch ab und an öffnen, bzw. wenn eine Benachrichtigung kommt.
Insbesondere der alte Ring Adapter hat aber permanent Daten abgefragt. Sofern das einzelne Nutzer machen passiert nichts. Machen es genug Menschen, dann kann es sein, dass es Ring auffällt und ggf. Gegenmaßnahmen gegen "übermäßige" Beanspruchung des Servers getroffen werden. Dies könnte dann z.B. ein "Blacklisten" von IP's oder API-Keys sein, welches sich z.B. darin äußert, dass keine Benachrichtigungen an diese Instanz geschickt werden.


Sofern sich hier aber kein Entwickler von Ring meldet, werden wir dies aber vermutlich nicht bestätigen/nachweisen können.

GGf. spielt es auch eine Rolle, ob man ein Abonement hat.

**Comment by denjo82** [comment]
Also, ich habe genau das gleiche Problem. Bei Version 3.0.4 bzw 3.0.5 ändert sich der Datenpunkt nicht wenn es klingelt, version 3.0.1 läuft tadellos. Ich habe auch schon alles ausprobiert ohne erfolg.

**Comment by McWoolf** [comment]
Scheint leider so zu sein, dass die Ring-API keine Aktionen mehr weiterleitet.
Schade eigentlich.

**Comment by philipp1987** [comment]
> Scheint leider so zu sein, dass die Ring-API keine Aktionen mehr weiterleitet. Schade eigentlich.

Installier dir mal, über den Experten-Modus die Version 3.0.1. Bei der funktioniert es bei mir noch 😉

**Comment by McWoolf** [comment]
Danke jetzt funktionierts wieder.

**Comment by denjo1982** [comment]
ich verstehe leider nicht warum jede version nicht funktioniert die außer 3.0.1, egal welche neue version raus kommt keine funktioniert

**Comment by tccflash** [comment]
Also ich hab jetzt auch alles rauf und runter probiert. Ich muss meinen Vorrednern recht geben. Nur in Version 3.0.1 funktioniert alles, so wie es soll. In den Versionen danach wird bei mir ebenso weder der „Ding“ Datenpunkt angelegt, noch wird Motion automatisiert übertragen bzw. erkannt.  
Was dort jedoch ab und an mal, jedoch auch nicht zuverlässig, funktioniert ist das manuelle triggers des snapshots. 

Hab leider auch keine Ahnung, an was das liegen könnte. 

Hab die Instanz kplt neu angelegt, alle Verbindungen gelöscht und einen neuen Token erstellt. Jedoch funktionierte es echt er’s wieder nachdem ich auf 3.0.1 zurück bin.

**Comment by denjo1982** [comment]
gibt wohl  keine lösung oder????

**Comment by erniecs** [comment]
> gibt es wohl keine lösung oder????

Wie dein Vorgänger schreibt, 3.0.1 installieren und es funktioniert

**Comment by theimo1221** [comment]
It might be a bug in the ring api library as stated here https://github.com/dgreif/ring/issues/1025

As soon as there is a fix in their library I'll updated the dependency.

**Comment by applewatchdev** [comment]
War gerade von der 3-beta auf 3.1.2 dann hat sich nichts mehr aktualisiert, nun auf die 3.0.1 zurück und es klappt wieder. Sonst nichts geändert, keine neuen Tokens, keine Geräte entfernt oder sonst was.

**Comment by theimo1221** [comment]
https://github.com/iobroker-community-adapters/ioBroker.ring/blob/master/README.md#i-dont-recieve-events-snapshots-and-videos-on-motion-or-detected-person
