### ISSUE TITLE
keine Snapshots mehr in Version 3.04

### ISSUE THREAD

**Issue by sebaboehm** [iobroker-community-adapters/ioBroker.ring#291]
Seit dem Update auf 3.04 werden in den meisten Fällen keine Snapshots mehr bei Ereignissen gespeichert:

<img width="996" alt="image" src="https://user-images.githubusercontent.com/62656360/175569198-c7511f79-645f-49d4-a15a-281d22543998.png">

Dies funktioniert nur noch sporadisch.

Zudem werden, wenn Snapshot und Livestream gespeichert werden, nur noch von jedem eins gespeichert.
Alte Snapshots werden anscheinend sofort mit dem neuen überschrieben.

**Comment by theimo1221** [comment]
Nabend @sebaboehm,

Das "von jedem nur eins" ist abhängig von der Einstellung.

Die "Fehlermeldung" ist normal wenn gerade ein Livestream aufgezeichnet wird (es geht nicht beides zeitgleich). Dann wird im Nachgang der auslösende Screenshot nochmal angefordert.
Das müsste man aber mindestens an der Zeitpunkten beim Snapshot Objekt sehen.

VG Thiemo

**Comment by sebaboehm** [comment]
Hi Thiemo,

ich verstehe die Antwort leider nicht.
Wie stelle ich das ein das mehrere gespeichert werden? Bisher war es immer so, das ich da teilweise hunderte gespeichert hatte obwohl ich automatisch löschen eingestellt hatte.

Ich bin auch der Meinung, das bisher beides gespeichrt wurde.
Den Snapshot anfordern funktioniert aber nicht?

Wie ist dieser Satz gemeint "Das müsste man aber mindestens an der Zeitpunkten beim Snapshot Objekt sehen." ?
Welches Objekt? Es wird ja nichts gespeichert :-/

Übrigens funktioniert auch die Verknüpfung an der linken Seite nicht, die ich seit der neuen Version habe:

<img width="433" alt="image" src="https://user-images.githubusercontent.com/62656360/175787078-64c441a6-027e-4ee2-ada5-d19f4a9fab5a.png">

Danke und Gruß
sebaboehm

**Comment by theimo1221** [comment]
Nabend @sebaboehm 

## Zum Thema "Nur neuste bleibt bestehen"
<img width="1247" alt="image" src="https://user-images.githubusercontent.com/20605452/175789061-165e247b-695a-44bb-9910-ab4588a670c1.png">

Diese beiden Felder sind aktuell standardmäßig aktiv, da diverse Systeme an den Ring-Datei-Mengen früher oder später voll liefen.
Wenn man selbständig auf sein System achtet, kann man diese Option aber natürlich deaktiviert.

## Verknüpfung linke Seite
Dies steht leider noch aus, hier ist geplant irgendwann ein Dashboard zu machen wie es in der Ring App ist.


## Snapshot anfordern geht nicht
Hier würde ich dich bitten mehreres zu prüfen
1. Hat ioBroker die passenden Schreib-Rechte in dem von dir eingestelltem Speicher-Ordner der Snapshots?
2. Welcher Grund kommt, wenn du die Logstufe auf Debug änderst?

**Comment by sebaboehm** [comment]
Hi Thiemo,

nachdem ich eben "delete old snapshots" deaktiviert habe, funktionierte es auf einmal. 
Wenn ich es wieder einschalte, kommt folgender Fehler (debug):

<img width="1129" alt="image" src="https://user-images.githubusercontent.com/62656360/175800275-379da360-5ab3-4511-94cb-881f9c6e4449.png">

Schreibrechte auf den Ordner sind vorhanden.

**Comment by sebaboehm** [comment]
leider scheint das doch falsch zu sein. ich habe "delete old snapshots" ausgeschaltet, aber es kommt trotzdem der Fehler. Es scheint irgendwie nur sporadisch zu funktionieren:

<img width="1102" alt="image" src="https://user-images.githubusercontent.com/62656360/175800738-9b822229-42ea-49e7-8f3e-91bfa195318a.png">

**Comment by McWoolf** [comment]
Ich habe das selbe Problem.

**Comment by theimo1221** [comment]
> Hi Thiemo,
> 
> nachdem ich eben "delete old snapshots" deaktiviert habe, funktionierte es auf einmal. Wenn ich es wieder einschalte, kommt folgender Fehler (debug):
> 
> <img alt="image" width="1129" src="https://user-images.githubusercontent.com/62656360/175800275-379da360-5ab3-4511-94cb-881f9c6e4449.png">
> 
> Schreibrechte auf den Ordner sind vorhanden.

@sebaboehm Gemäß der Meldung, dass er es innerhalb von 15s nicht schafft, denke ich, dass hier eher ein Verbindungsproblem vorliegt.

**Comment by sebaboehm** [comment]
Also demnach gibt es manchmal ein Verbindungsproblem, und manchmal nicht?
Bevor ich auf 3.04 geupdatet (zusammen mit Update auf Node 16.15.1) habe, wurden alle Snapshots einwandfrei erstellt.
Daher gehe ich nicht von einem Verbindungsproblem aus.

**Comment by theimo1221** [comment]
@sebaboehm Ich habe deinen Screenshot nochmal genauer angeschaut.
Ein paar Sekunden nach der Fehlermeldung kam die Meldung, dass der Livestream aufgenommen wurde.

Die Ring Kameras können nicht beides zugleich; sprich während einer Video aufnahme gehen keine Snapshots, anschließend schon.
Sprich wenn du (nahezu) zeitgleich ein Video und einen Snapshot anforderst wird das scheitern.

**Comment by sebaboehm** [comment]
@theimo1221 das verstehe ich. die Frage ist halt nur, warum habe ich mit der alten Version niemals einen Fehler bekommen, jetzt aber doch?

**Comment by theimo1221** [comment]
Ist das ein automatischer Snapshot oder einer den du auslößt?

**Comment by sebaboehm** [comment]
ja, ich mache da nichts manuell

**Comment by theimo1221** [comment]
@sebaboehm Da es normal ist, dass während eines Livestreams oder Zugriff mittels App der Snapshot nicht angelegt werden kann, habe ich die Lognachrichten in `v3.0.5` dahingehend angepasst, sodass nun jene fehlschlagenden Snapshots während einer Eventbehandlung nicht als Fehler tituliert sind.

Falls dennoch weiterhin die Meldungen kommen, liegt in deinem Fall noch ein weiterer Fehler vor.

**Comment by sebaboehm** [comment]
@theimo1221 
Ich verstehe ehrlich gesagt nicht so richtig was du meinst. Bedeutet das, der Fehler kommt jetzt erst in Version 3.0.5 und wurde vorher einfach nur nicht geloggt? 

Welcher Fehler könnte es sein? Hier hat ja noch jemand geschrieben der das gleiche Problem hat.

**Comment by theimo1221** [comment]
@sebaboehm 
Das gewünschte Eventverhalten ist eigentlich wie folgt:
1. Event wird ausgelöst
2. Kamera soll versuchen schnell einen Snapshot zu machen (z.B. für Push Nachricht)
3. Kamera soll 20s aufzeichnen
4. Falls wir in 2. den Snapshot nicht geschafft haben nun nachträglich über die Ding-ID nachladen.

In vielen Situationen wird Schritt 2 fehlschlagen, dass liegt aber wie gesagt an Einschränkungen von Ring (entweder aufzeichnen oder Snapshot, beides zugleich geht nicht)

**Comment by McWoolf** [comment]
Also Leute irgendwas ist da komisch, bei mir wird nur sporadisch was aufgezeichnet.
Aber in den seltensten Fällen nur.
Vor dem update musste ich alte händisch löschen, sonst lief mir die Festplatte voll und jetzt nur mehr alle paar Tage ein snapshot

**Comment by McWoolf** [comment]
![image](https://user-images.githubusercontent.com/73942255/178235236-079eb8c4-a7e4-41ec-a8f9-5b88cb312c60.png)

**Comment by McWoolf** [comment]
`<html>
<body>


2022-07-11 00:33:14.002 - debug: ring.0 (2332) Device 82516918 ("Haustür"): Recieved Update
2022-07-11 00:33:14.002 - debug: ring.0 (2332) Device 82516918 ("Haustür"): Update Snapshot Object
2022-07-11 00:33:14.518 - debug: ring.0 (2332) Device 82516918 ("Haustür"): Update Health Callback
2022-07-11 00:34:41.746 - debug: ring.0 (2332) Refresh Ring Connection
2022-07-11 00:34:41.746 - debug: ring.0 (2332) Retrieve Locations
2022-07-11 00:34:41.746 - debug: ring.0 (2332) As the configured refresh token hasn't changed the state one will be used
2022-07-11 00:34:42.084 - info: ring.0 (2332) Recieved new Refresh Token. Will use the new one until the token in config gets changed
2022-07-11 00:34:43.010 - debug: ring.0 (2332) Recieved 1 Locations
2022-07-11 00:34:43.010 - debug: ring.0 (2332) Location 8c6b6afe-a7e8-44e1-8d03-dbb8cc76b624 ("Zu Hause"): Recieved Location Connection Status Change to false
2022-07-11 00:34:43.011 - debug: ring.0 (2332) Process Location Zu Hause
2022-07-11 00:34:43.012 - debug: ring.0 (2332) Recieved 0 Devices in Location Zu Hause
2022-07-11 00:34:43.012 - debug: ring.0 (2332) Location has 1 Cameras
2022-07-11 00:34:43.012 - debug: ring.0 (2332) Device 82516918 ("Haustür"): Recieved Update
2022-07-11 00:34:43.012 - debug: ring.0 (2332) Device 82516918 ("Haustür"): Update Snapshot Object
2022-07-11 00:34:43.012 - debug: ring.0 (2332) Refresh complete
2022-07-11 00:34:43.439 - debug: ring.0 (2332) Device 82516918 ("Haustür"): Update Health Callback
2022-07-11 00:34:43.968 - debug: ring.0 (2332) Device 82516918 ("Haustür"): Recieved Update


</body>
</html>`

**Comment by McWoolf** [comment]
das hat mein debug ausgegeben.

**Comment by theimo1221** [comment]
@McWoolf dein Logauszug beinhaltet keine Fehler dieses Adapters. Dass einzig was er veranschaulicht, ist dass kein Event beim iobroker Adapter ankam.
Die erste Reaktion auf ein Klingeln ist das Schreiben dieser Lognachricht:
[    this.debug(`Recieved Ding Event (${value})`);](https://github.com/iobroker-community-adapters/ioBroker.ring/blob/77d715cf3c16d3c059594f829bb9f152e2485d9d/src/lib/ownRingDevice.ts#L669)

Kommt diese Nachricht nicht, dann hatte dieser Adapter auch keine Chance auf ein Event zu reagieren

**Comment by sebaboehm** [comment]
so, nach längerem Testen nun mein Fazit:
Snapshots werden zu 99% Prozent keine mehr gespeichert. Der Adapter ist damit leider nicht mehr wirklich funktional und für mich persönlich kaum noch brauchbar.

Schade das so ein gut funktionierender Adapter mit einem Update unbrauchbar gemacht wird.

**Comment by McWoolf** [comment]
Was ich bemerkt habe, der Adapter bekommt eine Bewegung gar nicht mehr mit, denn wenn du von Hand die Speicherung anstößt, wird auch gespeichert. Also entweder hat hier Ring etwas umgebaut oder was weiß ich. Finde es auch schade, dass hier keiner eine Lösung hat.

**Comment by theimo1221** [comment]
> Schade das so ein gut funktionierender Adapter mit einem Update unbrauchbar gemacht wird.

@sebaboehm hier sind 11 GB an Aufnahmen und Livestreams die etwas anderes behaupten.
<img width="471" alt="image" src="https://user-images.githubusercontent.com/20605452/182702915-93b368da-231b-4186-9659-d0a5008636d1.png">

Sprich pauschal zu sagen, der Adapter geht nicht mehr ist so nicht ganz korrekt.



Wie gesagt, auch ich hatte mit einer vorherigen Version einen Zeitpunkt wo mein API-Token wohl seitens Ring als "unwürdig" markiert wurde und bei mir keine Bewegungsevents mehr ankamen. 
Bei mir hat da geholfen alle API-Tokens in der Ring Website zu löschen und einen frischen Token zu generieren.

**Comment by McWoolf** [comment]
Oke das wäre ein Ansatz, aber jetzt habe ich die Website durchgesehen und da finde ich nichts wo ich meine Token löschen kann. Wie hast du das gemacht?

**Comment by theimo1221** [comment]
![image](https://user-images.githubusercontent.com/20605452/182780847-ea67275f-bce1-496f-8da7-b9064d32374f.png)
Rechts oben Hover über Konto und dann Kontrollzentrum

**Comment by McWoolf** [comment]
Leider hilft selbst ein neuer Token nichts, der Adapter reagiert nicht. 
Vielleicht noch einen anderen Vorschlag?

**Comment by theimo1221** [comment]
https://github.com/iobroker-community-adapters/ioBroker.ring/issues/284#issuecomment-1177210144

**Comment by theimo1221** [comment]
https://github.com/iobroker-community-adapters/ioBroker.ring/blob/master/README.md#i-dont-recieve-events-snapshots-and-videos-on-motion-or-detected-person
