### ISSUE TITLE
Ring Dorbell 4 wird vom adapter nicht unterstüzt 

### ISSUE THREAD

**Issue by motugozu** [iobroker-community-adapters/ioBroker.ring#294]
ist es geplant das es support für die ring dorbell 4 gibt

Im Log wird diese meldung ausgegeben 

Device with Type doorbell_oyster not yet supported, please inform dev Team via Github

**Comment by theimo1221** [comment]
Moin @motugozu 

Müsste mit der `v3.0.5` nun gehen 

VG Thiemo
