### ISSUE TITLE
File tab_m.html not found

### ISSUE THREAD

**Issue by Tscheurgen** [iobroker-community-adapters/ioBroker.ring#302]
Hello all!

I've updated to version 3.0.4 and activated the adapter again.
everything seems to work fine, except the adapter page/tab.
There I receive "File tab_m.html not found".
Is this the reason because there is not adapter tab or do I miss something?

![image](https://user-images.githubusercontent.com/94912591/177980941-54a5818d-1567-42bf-b5b2-00b37387d1c6.png)

- Adapter Version 3.0.4
- js-controller Version 4.0.23
- Node Version 16.15.1
- OS: Raspbian GNU/Linux 10 (buster)

Thank you!
Kind regards
Jürgen

**Comment by stonytec** [comment]
Hi!
Same here,

- Adapter Version 3.0.5
- Node.js: v16.16.0
- NPM: 8.11.0
- OS: PVE Container Ubuntu 22.04

Thanks and best regards!
Martni

**Comment by theimo1221** [comment]
Hi,

that was just a placeholder, I plan on implementing a dashboard like in ring App.

Best regards 
Thiemo

**Comment by stonytec** [comment]
Hi,
thanks for the update. Looking forward :-)
Keep up the good work!
Best Regards!
Martin

**Comment by mcm1957** [comment]
further prcessing with https://github.com/iobroker-community-adapters/ioBroker.ring/issues/432
