### ISSUE TITLE
NodeJS 18

### ISSUE THREAD

**Issue by HeGa59** [iobroker-community-adapters/ioBroker.ring#307]
Error on install ring at Nodejs 18:

$ iobroker url iobroker.ring --host ioBroker --debug

install iobroker.ring

Installing iobroker.ring... (System call)

npm ERR! code EBADENGINE

host.ioBroker Cannot install iobroker.ring: 1

ERROR: Process exited with code 25

**Comment by theimo1221** [comment]
Hello @HeGa59,

Before we can allow Node 18, Ring Api Client has to update: 
https://github.com/dgreif/ring/blob/866fcbcdf12561d3d5dd512aa1d4f73134c25490/package.json#L100

Feel free to open an issue there

Best Regards

Thiemo

**Comment by theimo1221** [comment]
https://github.com/dgreif/ring/issues/1048#issuecomment-1264675424
