### ISSUE TITLE
Adapter erkennt generierten Token nicht - Fehlermeldung 

### ISSUE THREAD

**Issue by niiccooo1** [iobroker-community-adapters/ioBroker.ring#314]
**Describe the bug**  
Nachdem der Token über die Konsole erfolgreich erstellt und in der Instanzeinstellung eingetragen wurde taucht folgenden Fehlermeldung auf:

<html>
<body>

ring.0 | 2022-07-21 08:10:01.017 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
ring.0 | 2022-07-21 08:10:01.015 | info | terminating
ring.0 | 2022-07-21 08:10:01.005 | error | locs is not iterable
ring.0 | 2022-07-21 08:10:01.005 | error | TypeError: locs is not iterable at RingApiClient.retrieveLocations (/opt/iobroker/node_modules/iobroker.ring/build/lib/ringApiClient.js:110:27) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async RingApiClient.refreshAll (/opt/iobroker/node_modules/iobroker.ring/build/lib/ringApiClient.js:67:9) at async RingApiClient.init (/opt/iobroker/node_modules/iobroker.ring/build/lib/ringApiClient.js:54:9) at async RingAdapter.onReady (/opt/iobroker/node_modules/iobroker.ring/build/main.js:80:9)
ring.0 | 2022-07-21 08:10:01.005 | error | unhandled promise rejection: locs is not iterable
ring.0 | 2022-07-21 08:10:01.004 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
ring.0 | 2022-07-21 08:10:00.999 | error | Api Call failed
ring.0 | 2022-07-21 08:10:00.555 | info | Recieved new Refresh Token. Will use the new one until the token in config gets changed
ring.0 | 2022-07-21 08:10:00.181 | info | Initializing Api Client
ring.0 | 2022-07-21 08:10:00.141 | info | starting. Version 3.0.4 in /opt/iobroker/node_modules/iobroker.ring, node: v16.16.0, js-controller: 4.0.23

</body>
</html>

**Versions:**  
 - Adapter version: v3.0.4
 - JS-Controller version: 4.0.23
 - Node version: v16.16.0
 - Operating system: Raspberry OS Bullseye - Pi 4 2 GB

**Additional context**  
Zusätzliche Information: Aktuell befindet sich noch kein registrietes Ring Gerät im Account.

**Comment by theimo1221** [comment]
Nabend @niiccooo1,

naja, die Fehlermeldung sagt etwas anderes: 
`locs is not iterable`
`ring.0 | 2022-07-21 08:10:01.005 | error | TypeError: locs is not iterable at RingApiClient.retrieveLocations`

Ohne jegliche "Locations" (Ring schließt Geräte eines Standorts zusammen), macht dieser Adapter keinen Sinn, da dann weder Daten abgerufen noch Geräte gesteuert werden könne.

VG Thiemo
