### ISSUE TITLE
Adapter bricht beim Start ab

### ISSUE THREAD

**Issue by sunshower2** [iobroker-community-adapters/ioBroker.ring#319]
nach Installation von Version 3.0.5 bricht diese beim Start immer mit folgender Fehlermeldung ab:

2022-07-26 10:30:48.343  - info: host.1iobroker instance system.adapter.ring.0 started with pid 69262
2022-07-26 10:30:54.719  - info: ring.0 (69262) starting. Version 3.0.5 in /opt/iobroker/node_modules/iobroker.ring, node: v16.16.0, js-controller: 4.0.23
2022-07-26 10:30:54.780  - info: ring.0 (69262) Initializing Api Client
2022-07-26 10:30:55.151  - error: ring.0 (69262) Api Call failed
2022-07-26 10:30:55.159  - error: ring.0 (69262) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-07-26 10:30:55.163  - error: ring.0 (69262) unhandled promise rejection: locs is not iterable
2022-07-26 10:30:55.164  - error: ring.0 (69262) TypeError: locs is not iterable
    at RingApiClient.retrieveLocations (/opt/iobroker/node_modules/iobroker.ring/build/lib/ringApiClient.js:110:27)
    at async RingApiClient.refreshAll (/opt/iobroker/node_modules/iobroker.ring/build/lib/ringApiClient.js:67:9)
    at async RingApiClient.init (/opt/iobroker/node_modules/iobroker.ring/build/lib/ringApiClient.js:54:9)
    at async RingAdapter.onReady (/opt/iobroker/node_modules/iobroker.ring/build/main.js:80:9)
2022-07-26 10:30:55.166  - error: ring.0 (69262) locs is not iterable
2022-07-26 10:30:55.178  - info: ring.0 (69262) terminating
2022-07-26 10:30:55.180  - warn: ring.0 (69262) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-07-26 10:30:55.873  - error: host.1iobroker instance system.adapter.ring.0 terminated with code 6 (UNCAUGHT_EXCEPTION).

Auf welcher Seite des Bildschirms sitzt das Problem  ? :-)

**Comment by theimo1221** [comment]
Hallo @sunshower2,

Kann es sein, dass du kein Gerät hast?

Vg Thiemo

**Comment by sunshower2** [comment]
Hallo Thiemo,Nein, die Ring-App zeigt mir auch die Klingel an, allerdings ist sie gerade offline, kann das das Problem sein?TschüssT.Am 26.07.2022 um 13:59 schrieb Thiemo Hoffmann ***@***.***>:﻿
Hallo @sunshower2,
Kann es sein, dass du kein Gerät hast?
Vg Thiemo

**Comment by dbuehl** [comment]
Hallo Thiemo,

ich denke, ich habe hier dasselbe Problem:
Der Adapter (3.0.4 von npm installiert) startet kurz und verabschiedet sich dann sofort wieder:

host.ioBroker | 2022-07-31 21:35:20.453 | error | instance system.adapter.ring.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
ring.0 | 2022-07-31 21:35:19.858 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
ring.0 | 2022-07-31 21:35:19.856 | info | terminating
ring.0 | 2022-07-31 21:35:19.838 | error | locs is not iterable
ring.0 | 2022-07-31 21:35:19.837 | error | TypeError: locs is not iterable at RingApiClient.retrieveLocations (/opt/iobroker/node_modules/iobroker.ring/build/lib/ringApiClient.js:110:27) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async RingApiClient.refreshAll (/opt/iobroker/node_modules/iobroker.ring/build/lib/ringApiClient.js:67:9) at async RingApiClient.init (/opt/iobroker/node_modules/iobroker.ring/build/lib/ringApiClient.js:54:9) at async RingAdapter.onReady (/opt/iobroker/node_modules/iobroker.ring/build/main.js:80:9)
ring.0 | 2022-07-31 21:35:19.836 | error | unhandled promise rejection: locs is not iterable
ring.0 | 2022-07-31 21:35:19.836 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
ring.0 | 2022-07-31 21:35:19.832 | error | Api Call failed
ring.0 | 2022-07-31 21:35:19.422 | info | Initializing Api Client
ring.0 | 2022-07-31 21:35:19.387 | info | starting. Version 3.0.4 in /opt/iobroker/node_modules/iobroker.ring, node: v16.16.0, js-controller: 4.0.15

Das Fehlerprotokoll zum ring Adapter sieht für mich genauso aus wie bei sunshower2.
Ich bin aber sicher, dass ich bei der Einrichtung meines ring-Kontos einen Standort ("daheim") mit gültiger Adresse über den Assistenten der ring App eingerichtet habe, das ring Gerät (eine Ring Video Doorbell Wired) ist mit dem Standort verknüpft und online; ich kann sie über die App und über das ring Webinterface sehen und bedienen.

Gibt es besondere Anforderungen an den Standort hinsichtlich seiner Benennung oder ist die Ring Video Doorbell Wired nicht mit dem Adapter kompatibel? Oder was sonst mache ich falsch?

Danke und Grüße
Daniel

**Comment by theimo1221** [comment]
Nabend @dbuehl,

schalte mal bitte das Logging auf Debug:
<img width="534" alt="image" src="https://user-images.githubusercontent.com/20605452/182046037-50ccbe86-fc75-47ab-9d52-92f8ddbd0c48.png">

Damit dürfte dann neben der von dir aufgeführten Meldung ("ring.0 | 2022-07-31 21:35:19.832 | error | Api Call failed") auch der Grund ausgegeben werden.
Das er nicht die Locations abarbeiten kann ist ein Folgefehler daraus, scheinbar kann der Adapter bei euch generell die Daten nicht abrufen, jedoch davor sich passend anmelden

VG Thiemo

**Comment by dbuehl** [comment]
Hallo Thiemo,

anbei dasselbe Logging mit Debug-Meldungen:

host.ioBroker | 2022-08-01 06:34:30.506 | error | instance system.adapter.ring.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
ring.0 | 2022-08-01 06:34:29.911 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
ring.0 | 2022-08-01 06:34:29.910 | info | terminating
ring.0 | 2022-08-01 06:34:29.889 | error | locs is not iterable
ring.0 | 2022-08-01 06:34:29.889 | error | TypeError: locs is not iterable at RingApiClient.retrieveLocations (/opt/iobroker/node_modules/iobroker.ring/build/lib/ringApiClient.js:110:27) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async RingApiClient.refreshAll (/opt/iobroker/node_modules/iobroker.ring/build/lib/ringApiClient.js:67:9) at async RingApiClient.init (/opt/iobroker/node_modules/iobroker.ring/build/lib/ringApiClient.js:54:9) at async RingAdapter.onReady (/opt/iobroker/node_modules/iobroker.ring/build/main.js:80:9)
ring.0 | 2022-08-01 06:34:29.888 | error | unhandled promise rejection: locs is not iterable
ring.0 | 2022-08-01 06:34:29.887 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
ring.0 | 2022-08-01 06:34:29.885 | debug | Recieved undefined Locations
ring.0 | 2022-08-01 06:34:29.885 | debug | Call Stack: Error at RingApiClient.handleApiError (/opt/iobroker/node_modules/iobroker.ring/build/lib/ringApiClient.js:118:50) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async RingApiClient.retrieveLocations (/opt/iobroker/node_modules/iobroker.ring/build/lib/ringApiClient.js:107:22) at async RingApiClient.refreshAll (/opt/iobroker/node_modules/iobroker.ring/build/lib/ringApiClient.js:67:9) at async RingApiClient.init (/opt/iobroker/node_modules/iobroker.ring/build/lib/ringApiClient.js:54:9) at async RingAdapter.onReady (/opt/iobroker/node_modules/iobroker.ring/build/main.js:80:9)
ring.0 | 2022-08-01 06:34:29.884 | debug | Failure reason:Error: Refresh token is not valid. Unable to authenticate with Ring servers. See https://github.com/dgreif/ring/wiki/Refresh-Tokens
ring.0 | 2022-08-01 06:34:29.883 | error | Api Call failed
ring.0 | 2022-08-01 06:34:29.569 | debug | Retrieve Locations
ring.0 | 2022-08-01 06:34:29.568 | debug | Refresh Ring Connection
ring.0 | 2022-08-01 06:34:29.567 | info | Initializing Api Client
ring.0 | 2022-08-01 06:34:29.565 | debug | New Config Path: "/opt/iobroker/iobroker-data/files/ring.0"
ring.0 | 2022-08-01 06:34:29.564 | debug | Configured Path: ""
ring.0 | 2022-08-01 06:34:29.533 | info | starting. Version 3.0.4 in /opt/iobroker/node_modules/iobroker.ring, node: v16.16.0, js-controller: 4.0.15

Den Grund für das Problem beschreibt der Adapter um 06:34:29.884 Uhr - Token ungültig. Das Token habe ich mit dem Befehl `npx -p ring-client-api ring-auth-cli` generiert. Aber auch der Link auf https://github.com/dgreif/ring/wiki/Refresh-Tokens hat mich nicht wirklich weiter gebracht. Habe den Adapter schon mehrfach (wegen dieses Problems) deinstalliert und wieder neu installiert. Mir ist dabei aufgefallen, dass das Token jedes Mal ein anderes ist - ist das normal?

Ansonsten ist vielleicht noch zu erwähnen, dass meine ioBroker Instanz auf einer Synology NAS in einem Docker-Container läuft, alles andere tut aber, wie es soll. Selbstverständlich habe ich das Token an der Shell innerhalb des Containers generiert. Ich habe nur den String innerhalb der Anführungszeichen bei Login übernommen.

Danke und Grüße
Daniel

**Comment by sunshower2** [comment]
Hallo zusammen,
Hmm, ich habe mir jetzt folgendermassen geholfen: Version 2.00 installiert, Dort kam dann die Meldung invalid token. Den token neu mit npx -p ring-client-api ring-auth-cli
generiert, und in Version 2.00 eingetragen. Anschliessend die Version 3 installiert und den token auch dort eingetragen. Jetzt funktioniert es zumindest bei mir.

Tschüss
T.

**Comment by dbuehl** [comment]
Hallo sunshower2,

das würde aber doch bedeuten, dass die V2 mit demselben (habe ich das richtig verstanden?) Token anders umgeht als die V3. Oder hast du nach dem Update auf V3 das Token neu erzeugt? Bitte beschreib doch mal genau, was du gemacht hast, dann würde ich das bei mir mal nachstellen. Woher hast Du die V2.00?

Thiemo würde es sicher auch helfen, das unterschiedliche Verhalten der V3 gegenüber der V2 nachzuvollziehen.

Danke und Grüße
Daniel

**Comment by sunshower2** [comment]
Hallo Daniel,
Zumindest scheint die Fehlermeldung eindeutiger zu sein.

Ich habe hier mehrere iobroker- Instanzen, auf einer hatte ich noch die ring V2.0 (beta).
Hier hatte ich zuerst das token eingetragen, das ich auf der V3.0 generiert hatte. Und mit dem er sich ja bei der V3.0 teilweise (?) anmelden konnte.
Anders als bei der V3.0 hat di 2.0 aber sofort gestoppt mit dem Hinweis, das das token nicht richtig ist. Also habe ich (auf dem Rechner mit der V2.0) das token neu generiert und in die V2.0 eingetragen. Das hat sofort funktioniert.
Dann das token aus der Version 2.0 kopiert und in die 3.0 eingetragen. Auch das hat funktioniert.
Von daher scheint Thiemo mit seiner Annahme Recht gehabt zu haben, dass der token die Probleme verursacht hat, ich weiss allerdings nicht, wieso die V3 anders als die V2 nicht sofort bei der Tokenüberprüfung abgebrochen hat und erst den Hinweis mit der fehlenden location ausgespuckt hat.
Das token scheint übrigens rechnerunabhängig zu sein, da ich es auch auf der Synology in der Homebridge eingegeben habe :-).

Das token hatte ich generiert mit npx -p ring-client-api ring-auth-cli

tschüß

T.

**Comment by theimo1221** [comment]
@dbuehl Das Token ist nach einmaliger Verwendung eigentlich quasi abgelaufen, da bei jedem Login ein neues für den nächsten Login generiert wird.
Dies macht die V3 auch über den Token State.

**Comment by sunshower2** [comment]
Hmm, jetzt wird’s aber wirklich interessant: Was heisst „quasi?“ Ich habe das Token innerhalb von 5 Minuten auf 3 verschiedenen Rechnern genutzt, alle 3 kamen mit dem Token klar und haben die Daten ausgelesen. Und tun das auch fleissig noch. Allerdings habe ich beim ersten Mal zwischen Generierung des Tokens und Eingabe im Adapter deutlich mehr Zeit verstreichen lassen, kann es sein, dass das Token einfach nur abgelaufen war?

**Comment by theimo1221** [comment]
@sunshower2 Ring hat in dem Sinne ja keine offiziell Dokumentierte API (vgl. [readme](https://github.com/dgreif/ring ) und die Bibliothenk die wir nutzen hat extra eine [Sektion wie die neuen Tokens zu handeln sind](https://github.com/dgreif/ring#refresh-token).

Es gibt keine offizielle Aussage was unter 
> they expire shortly after use
zu verstehen ist.

Dieser Adapter respektiert den jeweils beim Login neuen Token und nutzt ihn für den nächsten login.

**Comment by michihorni** [comment]
Hallöchen ich hatte auch das selbe Problem wie oben beschrieben. 
Aktuell klappt wieder alles. 
Was war passiert? 
Ich hatte den Admin ursprünglich mal in V6.2.6 installiert und dann über die angebotenen Updates bis zu 6.2.13 installiert. Gestern ist mir dann aufgefallen, dass der RING Adapter oben genannte Fehlermeldung produzierte. Ich habe aktuell wieder den Admin auf 6.2.6 gebracht und nun läuft der RING Adapter wieder fehlerfrei. Zufall ?
Gruß
Michael

**Comment by theimo1221** [comment]
Hallo @michihorni,
bei mir läuft auch die 6.2.13 inkl. Ring-Adapter ohne jegliche Probleme, ich wüsste aber auch nicht, was dabei das Problem sein sollte, wird also eher Zufall sein.

Vg Thiemo

**Comment by dbuehl** [comment]
Hallo zusammen,

die Tatsache, dass dieses Issue geschlossen wurde deutet darauf hin, dass es irgendeine Lösung für das Problem gibt, leider ist mir diese nicht ersichtlich. Den einzig konkreten Hinweis, dass das über `npx -p ring-client-api ring-auth-cli ` generierte Token nur für kurze Zeit gültig ist, habe ich beherzigt und das neu generierte Token binnen Sekunden in den Adapter eingetragen und gespeichert habe - mit dem bekannten Ergebnis "Failure reason:Error: Refresh token is not valid. Unable to authenticate with Ring servers. See https://github.com/dgreif/ring/wiki/Refresh-Tokens".

Ich kann auch die Versionsnummern von michihorni (Admin Version 6.2.6 oder 6.2.13) nicht nachvollziehen. Bei mir läuft der Admin Adapter (wenn der denn gemeint ist) in Version 5.3.8 (aktuelle stable). Kann es etwa daran liegen?

Thiemo, wenn Du dazu bereit wärst, können wir auch mal gemeinsam bei mir drüber schauen, ob du etwas offensichtliches siehst, was mir verborgen bleibt.

Danke und Grüße
Daniel

**Comment by dbuehl** [comment]
Nabend @theimo1221,

läuft die Kommunikation mit den ring-Servern unverschlüsselt über Port 80? Ich habe bei meiner Synology NAS, die den ioBroker im Docker Container ausführt, den port 80 auf 8880 umgeleitet,
`sudo iptables -I INPUT 1 -p tcp --dport 80 -j ACCEPT`
`sudo iptables -A PREROUTING -t nat -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 8880`
um einen Portkonflikt mir dem Webserver auf derselben Synology aufzulösen. Wird das das Problem sein?

Grüße
Daniel

**Comment by theimo1221** [comment]
Nabend @dbuehl,

https://github.com/dgreif/ring/blob/866fcbcdf12561d3d5dd512aa1d4f73134c25490/api/rest-client.ts#L32

Ist https also nicht Port 80.

VG Thiemo

**Comment by dbuehl** [comment]
Hallo Thiemo,

habe mir die Logsdes Adapters und dein Changelog nochmal genauer angesehen. 

Der Adapter v3.0.3 und v3.0.4 meckert ja immer irgendetwas mit den Locations an, auch wenn er die Debug-Meldung schmeißt, dass das refresh-Token nicht gültig sei. 
Du hast mit v3.0.3 den Standortmodus implementiert, was auch immer das ist. 

Ich habe also mal spaßeshalber die v3.0.1 drüber installiert und siehe da - der Adapter startet normal durch und akzeptiert das Token.
Bin noch immer bei v3.0.1 und froh, dass es jetzt mal läuft. 

Vielleicht hilft dir diese Erkenntnis der der Fehlersuche ja weiter.

Grüße
Daniel
