### ISSUE TITLE
Dependency blocks installation

### ISSUE THREAD

**Issue by Jey-Cee** [iobroker-community-adapters/ioBroker.ring#345]
**Describe the bug**  
The dependency ring-client-api seems not compatible with nodejs 18 (maybe?).
Installation on ioBroker running with nodejs 18 fails. 
Installation of **any** adapter fails if the ring adapter was installed before updating nodejs to 18.

**To Reproduce**  
1. Install ioBroker with nodejs 16
2. Install Ring adapter
3. Upgrade nodejs to 18
4. Try to install any other adapter

**Expected behavior**  
Not blocking any other installation.

**Screenshots & Logfiles**  
```
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: ring-client-api@11.0.7
npm ERR! notsup Not compatible with your version of node/npm: ring-client-api@11.0.7
npm ERR! notsup Required: {"homebridge":">=1.4.0","node":"^16"}
npm ERR! notsup Actual:   {"npm":"8.18.0","node":"v18.8.0"}
```

**Versions:**  
 - Adapter version: 3.1.1
 - JS-Controller version: 4.0.23
 - Node version: 18.8.0
 - Operating system: Raspbian

**Additional context**  
Some weird thing: After removing the engine homebridge from the package.json on ring-client-api, installation was working again.

**Comment by theimo1221** [comment]
resolved with `3.1.3`
