### ISSUE TITLE
Keine Funktion!

### ISSUE THREAD

**Issue by Lightyear5595** [iobroker-community-adapters/ioBroker.ring#360]
Moin,

die Instanz lief immer gut, doch jetzt war die Instanz grün, doch es wurden keine Datenpunkte aktualisiert.
Habe einen neuen Token erzeugt und eingetragen, doch es passiert nichts mit den Datenpunkten.
Wo ist das Problem?

Alle Adapter sind aktuell und Updates sind gemacht

LG

**Comment by FeLiiix** [comment]
Version 3.0.1 funktioniert bei mir ohne Probleme.
Ab Version 3.0.4 aktualisieren sich die Events Objekte nicht. Die Umschaltung des locationMode funktioniert allerdings.

**Comment by Sunshez** [comment]
Same Problem.


`javascript.0 | 2022-09-30 19:44:10.161 | error | at Object.<anonymous> (script.js.Ring-Telegram-Eingang:25:55)
javascript.0 | 2022-09-30 19:44:10.158 | error | script.js.Ring-Telegram-Eingang: TypeError: Cannot read properties of undefined (reading 'val')
javascript.0 | 2022-09-30 19:44:10.153 | error | script.js.Ring-Telegram-Eingang: Please disable that setting or use "getState" with a callback, e.g.: getState("ring.0.doorbell_98239800.Events.type", (err, state) => { ... });`

**Comment by Lightyear5595** [comment]
Down auf Vers.: 3.0.1 brachte die Lösung

**Comment by KaRehm** [comment]
Thanks i try the Solution
