### ISSUE TITLE
Missing Ring Event as datapoint

### ISSUE THREAD

**Issue by Wondermusic** [iobroker-community-adapters/ioBroker.ring#373]
**Describe the bug**  
There is no Event "Ding", just Motion

**To Reproduce**  
1. Go to Objects View -> doorbell_xxxxxx -> Events
2. See missing Ding or Ring. There is just the Event motion

**Screenshots & Logfiles**  
![Unbenannt](https://user-images.githubusercontent.com/1394038/195009287-b6e94b9b-b348-40fc-ab1d-d70c0c7b8799.png)

**Versions:**  
 - Adapter version: 3.1.3
 - JS-Controller version: 4.0.23
 - Node version: 16.16.0
 - Operating system: Ubuntu 22.04

**Comment by Voggl93** [comment]
I do have a similar issue. 
There is only a motion event and for some reason its not responding to motion; there is no status change when motion should be detected. A Snapshot is created but the sensor.motion datapoint is not responding. 

Does someone have a solution?

**Comment by theimo1221** [comment]
@Voggl93 could you change log level to debug and look out for `Recieved Motion Event xxx`. If it does show up then the state should change as well. If the message doesn't occurs the adapter doesn't get the needed Event from Ring Api.

Best regards
Thiemo

**Comment by Voggl93** [comment]
I've changed the loglevel of iobroker to debug but there is no message like Received Motion Event xxx. 
If i push the button it registers an the datapoint kind is changed to ding but there is also no message in the log.

The only message i get from the ring adapter is something like "Recieved new Refresh Token. Will use the new one until the token in config gets changed"

**Comment by theimo1221** [comment]
@Voggl93 just to prevent a miss understanding, did you change the log level of your ring instance to debug or just the iobroker level?

**Comment by Voggl93** [comment]
Yeah did that but seems that i've missed with the Mouse. So it was still on Info. Changed it this morning and when I left the House for work there is no Motion Event xxx. 
I've attached a Screenshot where it should have been.
I've left the House at 5:53am according to the Ring Video

**Comment by Voggl93** [comment]
Ah yeah Here comes the screenshot
![Screenshot_2022-10-13-06-44-32-745_com android chrome](https://user-images.githubusercontent.com/97192022/195504060-274fff61-38c9-4e0e-ad85-f2c70bae896e.jpg)

**Comment by theimo1221** [comment]
@Voggl93 except 5:26:41.586 you have no motion event, and even that one might be the initial "no motion". Did you move in front of the camera to trigger a motion event?

Additionally in the ring app, are alerts for motion on? If not that's the reason the ring api client doesn't receive the event thus not giving the adapter the needed info.

**Comment by Voggl93** [comment]
Yes i did move in Front of the camera but not at 5.26am.

So i've enabled the movement detection but the notification was disabled. Now enabled i do get notification from my Ring App b
In my Smartphone but theres nothing triggering in the Adapter.

**Comment by Wondermusic** [comment]
Sorry for the late reply, haven't got a mail about the answers.

This is all I get, after changing the loglevel of the ring- Adapter to debug:

```
2022-10-14 08:50:39.350 - debug: ring.0 (7867) Device 81034201 ("Haustür"): Recieved Update
2022-10-14 08:50:39.354 - debug: ring.0 (7867) Device 81034201 ("Haustür"): Update Snapshot Object
2022-10-14 08:50:39.803 - debug: ring.0 (7867) Device 81034201 ("Haustür"): Update Health Callback
2022-10-14 08:52:39.766 - debug: ring.0 (7867) Device 81034201 ("Haustür"): Recieved Update
2022-10-14 08:52:39.771 - debug: ring.0 (7867) Device 81034201 ("Haustür"): Update Snapshot Object
2022-10-14 08:52:40.238 - debug: ring.0 (7867) Device 81034201 ("Haustür"): Update Health Callback
```

Motion is not neccessary for me, but the ring event.

**Comment by theimo1221** [comment]
@Voggl93 could you try removing all iobroker tokens on the ring website and generate a new one?

**Comment by Voggl93** [comment]
Yes i can do that. 
Will give you an updated maybe this evening or tomorrow.

**Comment by Voggl93** [comment]
Still no luck. I've deleted every authorised Client on my ring account and then reauthorised my smartphone an iobroker.
Adapter is green but no event triggering

**Comment by Wondermusic** [comment]
@theimo1221 
same thing here with my problem. I did the same as Voggl93. Still no ding event visible.

**Comment by exaware** [comment]
I also have the same problem. The ding datapoint missing and the motion datapoint works only one time after restart of the ring adapter. I also removed all iobroker token and generate new one. Notifications are all activated.

**Comment by theimo1221** [comment]
I'm sorry, but it is working for me with 6 devices without any issues.

**Comment by theimo1221** [comment]
Hello @exaware,

first things first: I don't have a ring doorbell but I have 4 Stickups and 3 Floodlights in my account, so while I can't explicitly test doorbell events I do can test normal camera events.

To recieve events the following steps need to happen (compare FAQ):

- This adapter has to create an instance of [Ring Api Client](https://github.com/dgreif/ring) including correct authentication data
- [Ring Api Client](https://github.com/dgreif/ring) has to successfully connect to rings server
- [Ring Api Client](https://github.com/dgreif/ring) has to successfully subscribe to events
- This adapter has to subscribe to the events from [Ring Api Client](https://github.com/dgreif/ring) 

Now when a event occurs the chain is as following:

1. Ring Camera must inform Ring server
2. Ring has to decide whether this is an event which needs a push notification
3. The connection between [Ring Api Client](https://github.com/dgreif/ring) instance and ring must still exist
4. Ring has to decide whether the [Ring Api Client](https://github.com/dgreif/ring) is a valid push target
5. The [Ring Api Client](https://github.com/dgreif/ring) must react on the event
6. The [Ring Api Client](https://github.com/dgreif/ring) has to trigger the suscribed event from this adapter
7. The adapter has to react on the triggered event


Now we can check for some cases:

- Point 1 and 2: As you guys get events on your phones these are correct
- Point 3: As you guys report it even shortly after start this can't be the reason. Additionally every 2 hours the connection is terminated and reinitialized
- Point 4: This is not in my hands and as there is no official documentation this could rely on different factors (existing subscription, amount of cameras, amount of events, ....)
- Point 5 and 6: Not in my hands also
- Point 7: As soon as the event is triggered it get's logged `Recieved Motion Event` at debug level. As even this doesn't occur for some users one of the previous points has to fail.

Additionally my logic isn't written like if it's not my ip or stars don't align then don't react on events. So as atleast some users do get events correctly I don't see any options on my side for now.

**Comment by exaware** [comment]
I don't have a Protect-Abo. Do I need also enable "Smart Alerts" for motion notification?

**Comment by theimo1221** [comment]
> I don't have a Protect-Abo. Do I need also enable "Smart Alerts" for motion notification?

I'm neither an employee of ring nor do I have any source stating on which factors ring decides whether you are worthy to recieve notifactions or not (compare https://github.com/iobroker-community-adapters/ioBroker.ring/issues/284#issuecomment-1177271779). So while it might help having a `Protect-Abo` it might not be a deciding factor at all.

In June my iobroker on my main server was "blacklisted" as well (recieving no events) while it was working for other users. For me the problem resolved after removing all `authorized client devices` on the ring website, waiting one day with adapter turned off and the starting with a freshly generated token.

**Comment by exaware** [comment]
I removed all clients more times. But I didn't wait a day. That's agood Idea, maybe ring saves also the IP to black list.

**Comment by exaware** [comment]
I tried version 3.0.1 as like described in this in Thread [(#284)](https://github.com/iobroker-community-adapters/ioBroker.ring/issues/284#issuecomment-1177271779). Version 3.0.1 works fine for me. I also tried a newer version like 3.0.3 and the newest version 3.1.3, but it didn't work. By the way, I have the Ring Doorbell Wired.

**Comment by theimo1221** [comment]
> I tried version 3.0.1

That one has a much older version of ring api client library and without recent security patches so use at own risk

**Comment by exaware** [comment]
What would be the alternative? The newest ring adapter with a more secure ring api which is not working?
If someone can fix the problem with the newest ring api, I am ready to test it.

**Comment by theimo1221** [comment]
> What would be the alternative? The newest ring adapter with a more secure ring api which is not working? If someone can fix the problem with the newest ring api, I am ready to test it.

Compare it to driving, I'd rather not use my car at all if there are some security issues with it, than saying "nah I can't get it fixed now, so I can continue driving"

**Comment by FeLiiix** [comment]
> wenn ich alles neu installiere version 3.1.3 und neuen token erstelle und auch nur iobroker bei ring angemledet, fuktioniert es einmal, danach nicht mehr. deswegen sie alle versionen über 3.0.1 unbrauchbar und defekt oder sowas.

same behavior.. 

version 3.0.1 works.

**Comment by Ceel84** [comment]
Same problem
3.0.1 works

**Comment by Captain-patty** [comment]
Where do I get 3.0.1 now, the oldest I can choose under "install speciic version is 3.0.3!?

**Comment by Wondermusic** [comment]
> Where do I get 3.0.1 now, the oldest I can choose under "install speciic version is 3.0.3!?

type in console:    iobroker upgrade ring@3.0.1

**Comment by Wondermusic** [comment]
> Thank you @Wondermusic. Unfortunately no improvement. The ring.0.doorbell.(ID).state is not there anymore. Why the hell? :(
 
The datapoint has another name: 

<img width="541" alt="doorbell-event" src="https://user-images.githubusercontent.com/1394038/202638566-79b2a34b-5882-480b-a61f-164621208bc0.png">
The datapoint has another name:

**Comment by Captain-patty** [comment]
But all I have is this

![image](https://user-images.githubusercontent.com/85673809/202640375-1beb6312-a35a-4c90-8338-0e247c704e12.png)

**Comment by Wondermusic** [comment]
Delete the whole object tree and restart the adapter.
I think I did the same after downgrade to 3.0.1, but I'm not sure...

**Comment by Captain-patty** [comment]
<img width="1672" alt="image" src="https://user-images.githubusercontent.com/85673809/202666306-b1d03fe1-eb2e-48db-9065-b1830a2e8712.png">



Now it is completely broke. No more states in the tree.

**Comment by Wondermusic** [comment]
Huh... OK?! I didn't had that problem. 
What if you delete the whole adapter and try to reinstall with: 
iobroker install ring@3.0.1

Problem is - I don't know what this issue is. I'm just a user, not a programmer. On my side it worked with the upgrade routine i mentioned above.
Otherwise maybe @theimo1221 can help you with this problem.

**Comment by Wondermusic** [comment]
I've tested now Version 3.1.9, but still the same issue. There is no ring event and under events there is again only the motion event visible.

**Comment by denjo82** [comment]
Es ist leider so das bei den neueren Versionen also alles was höher ist wie 3.0.1 es nur einmal funktioniert mit frischen token, danach nicht mehr. Außer man macht wieder ein frischen token. Es funktioniert nur 3.0.1, verstehe nur nicht warum und warum nichts geändert wird?

**Comment by Captain-patty** [comment]
I guess the the problem is, like @theimo1221 said, he has nor Ring, only cams and they are working. It#s a pitty, since it has been ok previously and was one for all time destroyed by an update. :(

**Comment by denjo82** [comment]
Hat der Entwickler nur Kameras oder wie?

**Comment by denjo82** [comment]
Okay, danke für die info. Dann lasst uns mal sammeln für den Entwickler damit das ein Ende hat. Wäre froh wenn der Adapter vernünftig weiter entwickelt wird.

**Comment by Wondermusic** [comment]
Gute Idee - die kleine ist grad als Black Friday Angebot drin -> 40,-.
@theimo1221 Ist das ok für Dich? 5 Tage Zeit zum antworten... ;-) Danach kostet die wieder 60,-

**Comment by denjo82** [comment]
Zusammen schmeißen sagte ich aber nicht das ich alleine bezahle. 5€ würde ich dazu geben

**Comment by exaware** [comment]
Würde mich auch mit 5€ beteiligen

**Comment by muehle79** [comment]
Ich wäre auch mit 5€ dabei

**Comment by Wondermusic** [comment]
> Zusammen schmeißen sagte ich aber nicht das ich alleine bezahle. 5€ würde ich dazu geben

So wars auch nicht gemeint -> *Lach*
Wäre natürlich auch mit 5 dabei!

**Comment by Wondermusic** [comment]
For our English speaking users...

We are asking to collect for a Ring Doorbell for Theimo1221, so he can include their functions in future Versions of his ring adapter. 
Someones here who wants also donate some bucks? :-)

**Comment by brunsheinz** [comment]
Ich wäre auch mit 5 € dabei , wohin ? über Paypal?

**Comment by Wondermusic** [comment]
> Ich wäre auch mit 5 € dabei , wohin ? über Paypal?

Danke für die Spendenbereitschaft. :-) Aber immer ruhig mit den jungen Hühnern... *lach*
Wir warten mal 2-3 Tage und schauen wie viele sich beteiligen wollen und ob @theimo1221  überhaupt damit einverstanden ist.
Der Black Friday Verkauf geht ja noch 5 Tage...

Momentan hätten wir 25,- Euro zusammen.

**Comment by alex-meyus** [comment]
Dabei. +5 Euro

**Comment by Loctit3** [comment]
Dabei +5€

**Comment by theimo1221** [comment]
Good Morning Guys,

While this is very kind of you it does come with some expectations on your side.
Yes a ring doorbell would help me looking further into this and I definitely would, but there are two worst case scenarios for you guys:
- the events firing properly in my instance, which would bring us back to square 1.
- it could result in me confirming that the API we use ( https://github.com/dgreif/ring ) does not trigger the event properly (be it an issue of them or even higher up the chain ring themselves), so I could only open an issue there.

But I'm eager to try it, so I'll even fill up the missing amount from my side to buy it🙂

This is the paypal fundraiser link to contribute:
https://www.paypal.com/pools/c/8PgROKsJau

Best regards 

Thiemo

**Comment by denjo82** [comment]
So ich hab jetzt 10€ gespendet, bedeutet wenn alle mit machen sind die 40€ erreicht

**Comment by exaware** [comment]
I think, before Thilo buying a Ring Bell, everyone should write their Ring Bell Version. Maybe only a specific variant of Ring Bell has this problem. I make the beginning. I have:

Video Doorbell Wired

**Comment by Loctit3** [comment]
Ring Video Doorbell (2. Generation)

**Comment by denjo82** [comment]
Doorbell pro

**Comment by muehle79** [comment]
Doorbell (3.Generation)

**Comment by theimo1221** [comment]
> Ring Video Doorbell (2. Generation)

As this has a battery as well (easier development at desk) I added 20€ as well

**Comment by Ceel84** [comment]
Ring wired

**Comment by alex-meyus** [comment]
Ring wired

**Comment by Ceel84** [comment]
I donate 5€

**Comment by Wondermusic** [comment]
Doorbell Wired

**Comment by heikowe** [comment]
Ring Video Doorbell (4.Generation)

**Comment by denjo1982** [comment]
kann es jemand bestätigen das die 3.0.1 version sich nicht mehr starten lässt, die neue version 3.1.9 funktioniert leider auch nur einmal. dann muss man den key wieder erneuern

**Comment by Voggl93** [comment]
3.0.1 läuft bei mir ohne Probleme.

**Comment by denjo1982** [comment]
welches node.js hast du drauf??

**Comment by Voggl93** [comment]
Aktuell 16.18.0

**Comment by denjo1982** [comment]
NPM 8.19.2
js: 4.0.23
Node.js: v16.18.1

bekomme ihn nicht zum laufen

**Comment by heikowe** [comment]
ja, 3.0.1 (und auch neuere) scheinen nicht mit node 16.x zu laufen. Und dafür die node version downgraden ist natürlich auch nicht so schön

**Comment by denjo1982** [comment]
ich musste gestern mein system neu aufsetzten und vorher lief er perfekt. wundert mich alles irgendwie

**Comment by heikowe** [comment]
> 

hattest du vorher eine node Version < 16 ? und welche hast Du jetzt?
Also bei mir laufen alle Versionen vom ring adapter bis auf die aktuellste **nicht** mit node 16

**Comment by denjo1982** [comment]
ja hatte ich, mein system halte ich immer aktuell

**Comment by Voggl93** [comment]
Also ich habe
Node.js 16.18.0
Npm 8.19.2

Und 3.0.1 läuft problemlos

**Comment by heikowe** [comment]
Node.JS 16.18.1
NPM 8.19.2

Bei der Adapter Version 3.0.1 (und allen weiteren bis auf die neueste) erhalte ich diesen Fehler:

`

host.iobroker | 2022-11-30 11:25:59.696 | error | instance system.adapter.ring.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.iobroker | 2022-11-30 11:25:59.696 | error | Caught by controller[0]: code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
host.iobroker | 2022-11-30 11:25:59.696 | error | Caught by controller[0]: at require (node:internal/modules/cjs/helpers:103:18)
host.iobroker | 2022-11-30 11:25:59.696 | error | Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1057:19)
host.iobroker | 2022-11-30 11:25:59.695 | error | Caught by controller[0]: at Function.Module._resolveFilename (node:internal/modules/cjs/loader:971:27)
host.iobroker | 2022-11-30 11:25:59.695 | error | Caught by controller[0]: at resolveExports (node:internal/modules/cjs/loader:522:36)
host.iobroker | 2022-11-30 11:25:59.695 | error | Caught by controller[0]: at throwExportsNotFound (node:internal/modules/esm/resolve:365:9)
host.iobroker | 2022-11-30 11:25:59.696 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.ring/build/lib/ringApiClient.js:7:15) {
host.iobroker | 2022-11-30 11:25:59.696 | error | Caught by controller[0]: }
host.iobroker | 2022-11-30 11:25:59.695 | error | Caught by controller[0]: at new NodeError (node:internal/errors:387:5)
host.iobroker | 2022-11-30 11:25:59.695 | error | Caught by controller[0]: at packageExportsResolve (node:internal/modules/esm/resolve:649:3)
host.iobroker | 2022-11-30 11:25:59.695 | error | Caught by controller[0]: at Function.Module._findPath (node:internal/modules/cjs/loader:562:31)
host.iobroker | 2022-11-30 11:25:59.695 | error | Caught by controller[0]: at Function.Module._load (node:internal/modules/cjs/loader:833:27)

`

**Comment by denjo1982** [comment]
welchen js-controller habt ihr drauf?

**Comment by Captain-patty** [comment]
Bei mir läuft gar keine Version, nicht einmal die 3.0.1. Bei mir taucht der State "ring" einfach nicht mehr auf. :(

**Comment by denjo1982** [comment]
ja leider bringt der adapter mir jetzt nix mehr, mal hoffen das durch die spende bald mal was passiert

**Comment by denjo1982** [comment]
also leute da der adapter nicht mehr wirklich brauchbar für mich ist hab ich ein wenig rum probiert.
wenn ihr eure doorbell in einen samsung smart things konto verknüft und den dazu gehörigen adapter installiert gibt es einen punkt (status.button.button.timestamp) der sich aktualisiert beim klingeln. für mich reicht das erst mal.

**Comment by heikowe** [comment]
> also leute da der adapter nicht mehr wirklich brauchbar für mich ist hab ich ein wenig rum probiert. wenn ihr eure doorbell in einen samsung smart things konto verknüft und den dazu gehörigen adapter installiert gibt es einen punkt (status.button.button.timestamp) der sich aktualisiert beim klingeln. für mich reicht das erst mal.

was ähnliches habe ich mir eigentlich bei Alexa gedacht da dort die Integration ja ziemlich gut ist... Aber habe beim alexa2 Adapter noch keinen entsprechenden Datenpunkt für ring gefunden.

**Comment by denjo1982** [comment]
mit dem alexa2 adapter gibt es zur zeit ja auch viele probleme, aber die idee hatte ich auch und auch nix gefunden. dann hatte ich die idee

**Comment by theimo1221** [comment]
Some deletes, as this is an issue thread about ring adapter and not a forum about other adapter

Thanks to you guys I recieved my doorbell. And what should I say, I get Doorbell Events:

<img width="1656" alt="image" src="https://user-images.githubusercontent.com/20605452/205337937-09f9304f-606e-483c-9c81-f39c8140d544.png">

With 3.2.1 I made a slight change to order of setting `doorbell` state and starting the recording and increased the log depth.

So with Loglevel Debug you should get a debug message like:
```
Device xxxxx ("Arbeitszimmer"): Recieved Doorbell Event ({ ding: { streaming_protocol: 'ring_media_server', created_at: '2022-12-02T16:20:21.539Z', e2ee_method: 0, location_id: 'xxxxxx', device_name: 'Arbeitszimmer', doorbot_id: xxxx, e2ee_enabled: false, streaming_data_hash: 'sh-v1|tGE9I-9ZpynQdmZC1WcNwC..`
```

**Comment by denjo1982** [comment]
how do I install the 3.2.1???

**Comment by theimo1221** [comment]
> how do I install the 3.2.1???

Either by changing npm version or by install from github option

**Comment by theimo1221** [comment]
@Wondermusic, @muehle79, @Loctit3, @brunsheinz, @exaware Does 3.2.1 work on your instances?

**Comment by exaware** [comment]
After installing version 3.2.1 the events update only one time, same like at version 3.1.3. Motion, doorbell, snapshot and livestream work one time.

**Comment by theimo1221** [comment]
I just went into my office and pressed the doorbell button and got the state and event immediatly again....

<img width="1656" alt="image" src="https://user-images.githubusercontent.com/20605452/205350094-f82b8704-cb6f-4f2b-9505-fd09e798e3bc.png">

**Comment by Loctit3** [comment]
3.2.1 instant connection
first trys with doorbell press event worked perfect

**Comment by theimo1221** [comment]
I have another idea what the issue might be:

@denjo1982 and @exaware what is your iobroker hostname?
https://github.com/iobroker-community-adapters/ioBroker.ring/blob/master/src/lib/ringApiClient.ts#L40-L46

As mine is definitly unique due to own domain `iobroker.xxxxxx.com`

**Comment by csicom** [comment]
Hi, unfortunately no change in events in 3.2.1. I'm experimenting myself in the JavaScript adapter. This approach works for me with a Doorbell 3:

`const { PushNotificationAction, RingApi } = require('ring-client-api'),
//  { readFile, writeFile } = require('fs'),
  { promisify } = require('util')
       
async function example() {
    ringApi = new RingApi({
    refreshToken: getState('javascript.0.Ring.Refresh_Token').val,
    cameraDingsPollingSeconds: 2,
    debug: true,
    }),

    locations = await ringApi.getLocations(),
    allCameras = await ringApi.getCameras()
  

    console.log(
        `Found ${locations.length} location(s) with ${allCameras.length} camera(s).`
    )

    ringApi.onRefreshTokenUpdated.subscribe(
        async ({ newRefreshToken, oldRefreshToken }) => {
            console.log('Refresh Token Updated: ' + newRefreshToken)

            // If you are implementing a project that use `ring-client-api`, you should subscribe to onRefreshTokenUpdated and update your config each time it fires an event
            // Here is an example using a .env file for configuration
            if (!oldRefreshToken) {
//                console.log('Use old Refresh Token ...')
                return
            }
//console.log(newRefreshToken + '_________________' + oldRefreshToken)
 //               console.log('Refresh Token Updated: ', newRefreshToken)
           const currentConfig = getState('javascript.0.Ring.Refresh_Token').val,
                updatedConfig = currentConfig
                .toString()
                .replace(oldRefreshToken, newRefreshToken)
                 setState('javascript.0.Ring.Refresh_Token', updatedConfig); 
        })
//Ab hier Code
    camera = allCameras[0]
    camera.onNewNotification.subscribe((notification) => {
//        console.log(notification)
        const event =
          notification.action === PushNotificationAction.Motion
            ? 'Motion detected'
            : notification.action === PushNotificationAction.Ding
            ? 'Doorbell pressed'
            : `Video started (${notification.action})`
        
        console.log(
          `${event} on ${camera.name} camera. Ding id ${
            notification.ding.id}
          .  Received at ${new Date()}`
        ) 
           
    })

 }

example() 
`

Then get the saved snapshot via the image_uuid in the notification object

**Comment by exaware** [comment]
My iobroker hostname is **VM-IOBROKER**

**Comment by denjo1982** [comment]
it works for me but only once with a large delay

**Comment by exaware** [comment]
I tried with another hostname, same behavior.

**Comment by theimo1221** [comment]
@denjo1982 @exaware 
Could you guys give me some info about your setup
- Ring Protect Abo active?
- Smartphone: iPhone or Android?
- Ring Notifications Turned on?
- Fresh Refresh Token before adapter installation?
- Do you have other cameras and recieve motion events on them?
- Is your ring account connect to any other services?
- Doorbell Settings:
![image](https://user-images.githubusercontent.com/20605452/205371093-1eb6914b-a016-416f-8098-4cc4b77e5a3e.png)

**Comment by Voggl93** [comment]
So it seems @theimo1221 it has something to do with the Hostname.
I've installed 3.2.1 and it didn't work. Updated/Changed the Hostname and now events are triggering. Ding and Motion are working. I've tested this 3 times in a row now an everytime somethig triggered.

**Comment by exaware** [comment]
My iobroker running into a Proxmox VM. Now I have changed the hostname of the VM and the hostname of iobroker. I didn't know that iobroker has a own hostname, really crazy. Now it's working with 3.2.1.

My old iobroker hostname was **ioBroker**. Here is the place I changed the hostname of iobroker:
![image](https://user-images.githubusercontent.com/55593493/205378586-b52559c6-bc28-4d7b-9734-93dfb73462d6.png)

**Comment by Voggl93** [comment]
@exaware same for me. Proxmox VM and old Hostname was standard ioBroker. Now everything is running as it should

**Comment by heikowe** [comment]
But why is the default Hostname "iobroker" not working with the Ring Adapter? Would be great to get a fixed new Version working with all Hostnames.

**Comment by theimo1221** [comment]
> But why is the default Hostname "iobroker" not working with the Ring Adapter? Would be great to get a fixed new Version working with all Hostnames.

In my opinion there might be an easy reason for this:

The API want's a systemID to have a better identification for the counterpart accessing it (e.g. the installed ring app with a random id on a specific phone).
If now some hundred systems register with the same system id 'iobroker.ring' it is easy for them to block all of us.

I'll take a look on how to give every system a unique/random id to mitigate this as well

**Comment by denjo82** [comment]
How was that with the 3.0.1 version, it worked wonderfully there?

**Comment by Wondermusic** [comment]
@theimo1221 
Sorry, I am on a business trip. I'll try as fast as I can.

Ring Protect Abo active?
Yes

Smartphone: iPhone or Android?
Android

Ring Notifications Turned on?
Yes

Fresh Refresh Token before adapter installation?
Last Time when I changed to 3.1.9? No, after Inst.

Do you have other cameras and recieve motion events on them?
No

Is your ring account connect to any other services?
No

Doorbell Settings:

![Screenshot_20221203_074509_Ring](https://user-images.githubusercontent.com/1394038/205428594-19b9bf70-acd6-4e91-adc8-05b28521d94a.jpg)

**Comment by denjo1982** [comment]
so ich habe jetzt die neue version getestet und bei mir läuft es tadellos auch nicht nur einmal top

**Comment by exaware** [comment]
For me the version 3.2.2 works fine with iobroker hostname "ioBroker". 
@theimo1221 thank you for your work.

**Comment by Captain-patty** [comment]
Mine has obviously still no f*cking idea that it even is a ring :D

![ring](https://user-images.githubusercontent.com/85673809/205491103-71a1bbb2-0fd9-4adc-8e9d-476b411ae0b1.jpg)

**Comment by Captain-patty** [comment]
Or do I need the subscription? That would rather explain why it worked then and doesn't now. Because in the beginning you have some weeks free. I am pretty sure the Wifi signal was better, when it was active, also.

**Comment by MarioSander** [comment]
Hey Leute

wie habt ihr das mit dem Livestream gelöst?
wenn es klingelt soll auf der VIS der Livestream gezeigt werden, bei mir kommt aber irgendwie immer das letzte Video nicht der eigentliche Livestream.

**Comment by denjo1982** [comment]
Das geht nicht

**Comment by MeisterHeinz** [comment]
Dear @theimo1221 
unfortunately I have the same problem: No ring event, only a motion event. I have adapter version 5.0.0-alpha.0
I also changed my hostname from iobroker to a unique hostname, reinstalled everything but there is only one event: motion.
btw, I have  a subscription, so the reason is not the free plan.

**Comment by eumats** [comment]
Hallo,

ich habe leider das gleiche Problem (nur motion unter events).

Versions:

Adapter version: 5.0.10
JS-Controller version: 5.0.16
Node version: 18.17.1
Operating system: Debian GNU/Linux 11 (bullseye)

**Comment by MicMak24** [comment]
same here, just 'motion' under events nothing else :(

**Comment by undeat** [comment]
Interessant, dass das hier die Diskusion 2023 ohne Erfolg geendet hat und jetzt vor zwei 2 Tage sich wieder jemand mit dem gleichen Problem meldet. Ich habe das Problem auch.

Ich habe versucht das hier etwas nachzuvollziehen, was geschrieben wurde. Für diesen Adapter gab es schon lange kein Update mehr. Wenn ich das aber richtig sehe, ist der die ring-client-api Teil des Adapters und eigentlich verantwortlich für die Funktion und das erfassen der Events. Für diese ring-client-api gibt es auch noch regelmäßig updates. Ich vermute, dass die Lösung wäre, dass man die Version der ring-client.-api im ring.doorbell Adapter von IoBroker austauscht. Leider weiß ich nicht wie. 

unter iobroker\node_modules\ring-client-api scheinen die Dateien zu liegen. Leider sind die Dateien, die ich von Github runterladen kann ganz anders. Vielleicht kann da ja jemand helfen.

**Comment by theimo1221** [comment]
Das neuste Update von uns ist von vor 20 Tagen (6.2.1) ist nur noch keine "stable" Version

**Comment by undeat** [comment]
Oh da habe ich euch wohl unrecht getan. War war der Meinung das ich die 6.2.1 drauf hatte und die nicht ging. Außerdem hab ich extra die beta Repository aktiviert und auch kein Update für den Ring gefunden. Als ich jetzt gerade nachgeschaut habe, war die 5.1.0. drauf und ich konnte mit beta auf 6.2.1 updaten und auch das Ring Event ist wieder da. 

Vielleicht müsste man die nicht mehr funktionierenden Versionen auch aus der Stable raus nehmen, wenn das geht, damit es gar nicht erst zu diesen Verwirrungen kommt. Vielen Dank jedenfalls.
