### ISSUE TITLE
Adapter lässt sich nicht starten

### ISSUE THREAD

**Issue by Matzebhv** [iobroker-community-adapters/ioBroker.ring#375]
Moin,
auf einem gestern frisch aufgesetzten System lässt sich der Adapter nicht starten.

`starting. Version 3.1.3 in /opt/iobroker/node_modules/iobroker.ring, node: v16.17.1, js-controller: 4.0.23
Initializing Api Client
Api Call failed
Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
unhandled promise rejection: locs is not iterable
TypeError: locs is not iterable at RingApiClient.retrieveLocations (/opt/iobroker/node_modules/iobroker.ring/build/lib/ringApiClient.js:110:27) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async RingApiClient.refreshAll (/opt/iobroker/node_modules/iobroker.ring/build/lib/ringApiClient.js:67:9) at async RingApiClient.init (/opt/iobroker/node_modules/iobroker.ring/build/lib/ringApiClient.js:54:9) at async RingAdapter.onReady (/opt/iobroker/node_modules/iobroker.ring/build/main.js:80:9)
locs is not iterable
terminating
`

Hat da jemand eine Idee zu?
Gruß
Matze

**Comment by theimo1221** [comment]
Nabend

Hast du zumindest 1 Gerät in deinem Ring Account?

Wenn nein, dann erst den Adapter starten wenn ein Gerät da ist

Vg Thiemo

**Comment by Matzebhv** [comment]
Da sind 2 Geräte drin. Ein umschalten auf debug hat folgendes ergeben: 

Failure reason: Error: Refresh token is not valid. Unable to authenticate with Ring servers. See https://github.com/dgreif/ring/wiki/Refresh-Tokens

Auch ein neuer Token funktioniert nicht.
Gruß
Matze

**Comment by Matzebhv** [comment]
Was ich jetzt probiert habe:
Alle Token auf ring.com entfernen und neuen Token erzeugen -> leider ohne Ergebnis
Downgrade auf 3.0.1 -> funktioniert auch nicht. Adapter wirft die folgenden Meldungen:
`starting. Version 3.0.1 in /opt/iobroker/node_modules/iobroker.ring, node: v16.17.1, js-controller: 4.0.23
Initializing Api Client
Api Call failed
Failure reason: Error: Refresh token is not valid. Unable to authenticate with Ring servers. See https://github.com/dgreif/ring/wiki/Refresh-Tokens
Terminated (ADAPTER_REQUESTED_TERMINATION): We couldn't find any locations in your Ring Account

Seltsam ist, auf ring.com taucht der iOBroker nach dem Startversuch als Authorisiert auf. Jetzt habe ich allerdings keine rechte Idee mehr.

Gruß
Matze
`

**Comment by Matzebhv** [comment]
O.k., in einem anderen Issue bin ich drüber gestolpert. Der Token besteht aus dem String zwischen den Anführungszeichen und darf die selbigen nicht mit enthalten.
Ich würde vorschlagen, das in der Doku besser hervorzuheben. Trotzdem Danke für Deine Bemühungen.

Gruß
Matze
