### ISSUE TITLE
Adapter crashes (locs is not iterable)

### ISSUE THREAD

**Issue by kopierschnitte** [iobroker-community-adapters/ioBroker.ring#376]
**Describe the bug**  
After several days (or sometimes hours), the adapter crashes many times in a row and iobroker shuts it down due to too many failures. It happens without any user or script interaction.

**Expected behavior**  
Either locate and fix the cause or implement a delay so that problems on the API endpoint won't cause a deactivation of the instance.

**Screenshots & Logfiles**  
`<html>
<body>

host.iobroker | 2022-10-16 00:51:15.840 | error | instance system.adapter.ring.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
ring.0 | 2022-10-16 00:51:15.165 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
ring.0 | 2022-10-16 00:51:15.155 | error | locs is not iterable
ring.0 | 2022-10-16 00:51:15.154 | error | TypeError: locs is not iterable at RingApiClient.retrieveLocations (/opt/iobroker/node_modules/iobroker.ring/build/lib/ringApiClient.js:110:27) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async RingApiClient.refreshAll (/opt/iobroker/node_modules/iobroker.ring/build/lib/ringApiClient.js:67:9) at async RingApiClient.init (/opt/iobroker/node_modules/iobroker.ring/build/lib/ringApiClient.js:54:9) at async RingAdapter.onReady (/opt/iobroker/node_modules/iobroker.ring/build/main.js:80:9)
ring.0 | 2022-10-16 00:51:15.153 | error | unhandled promise rejection: locs is not iterable
ring.0 | 2022-10-16 00:51:15.153 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
ring.0 | 2022-10-16 00:51:15.147 | error | Api Call failed
host.iobroker | 2022-10-16 00:51:10.898 | error | instance system.adapter.ring.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
ring.0 | 2022-10-16 00:51:10.284 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason

</body>
</html>`

**Versions:**  
 - Adapter version: 3.1.3
 - JS-Controller version: 6.2.23
 - Node version: 16.17.1
 - Operating system: Ubuntu

**Additional context**  
I'm using three stick up cameras and one v1 doorbell.

**Comment by joe4github** [comment]
exactly the same issue.
npm@8.15.0
node@16.17.1

Operating system: rasbian (debian bullseye)
iobroker in docker container: iobroker/iobroker:v7.0.0-arm32v7

iobroker.info:
Plattform: docker
Betriebssystem: linux
Architektur: arm
CPUs: 4
Geschwindigkeit: 600 MHz
Modell: ARMv7 Processor rev 4 (v7l)
RAM: 922.1 MB
System-Betriebszeit: 15:33:26
Node.js: v16.17.0
time: 1665910944466
timeOffset: -120
Adapter-Anzahl: 443
NPM: 8.15.0
Datenträgergröße: 58.2 GB
Freier Festplattenspeicher: 47.0 GB
Betriebszeit: 15:19:18
Aktive Instanzen: 9
Pfad: /opt/iobroker/

**Comment by theimo1221** [comment]
Might be due to https://github.com/dgreif/ring/issues/1071

I changed the code, to retry reconnecting after 5 Minutes in case the initial connection on adapter start was successful
