### ISSUE TITLE
Keine Neue Bilder oder Streams

### ISSUE THREAD

**Issue by derdoerk** [iobroker-community-adapters/ioBroker.ring#380]
Hallo, 

ich habe seit geraumer Zeit das Problem, dass der Adapter keine neuen Bilder oder Videos mehr erzeugt. Egal ob ich das ganze manuell anfrage oder durch Bewegung oder ähnliches an den Kameras. 

![image](https://user-images.githubusercontent.com/79893009/197375680-fd548c0e-fa1a-446c-ab8a-24093098dc0e.png)

Habt ihr eine Idee, was die Ursache ist. Der IObroker ist auf aktuellem Stand. 

Gruß
Dirk

**Comment by theimo1221** [comment]
Nabend @derdoerk,

hat iobroker in dem benötigtem Pfad weiterhin die passenden Rechte?

VG Thiemo

**Comment by Schneggn** [comment]
Hi, ich habe das gleiche Problem. Es hat bis Juni alles super funktioniert, dann kein Snap und kein Video und keine Klingelauswertung mehr. Habe schon neu installiert und neues Token generiert. 
Von der Rechtevergabe in Linux habe ich allerdings keine Ahnung. Kann jemand ein Screenshot einstellen, womit man vergleichen kann wie es aussehen müsste?

Vielen Dank

**Comment by brunsheinz** [comment]
Hallo , Auch ich habe das gleiche Problem , keine Streams und Snapshot mehr seit 15. Juni, habe auch kein Abo .Habe alles schon neu installiert ohne Erfolg. Adapter  zeigt  keine Fehler . Über Alexa Funktion O.K.
Im Protokoll werden keine Meldungen diesbezüglich angezeigt
Gruß
Heinz
