### ISSUE TITLE
Keine Bewegungserkennung bei der Doorbell

### ISSUE THREAD

**Issue by Hini2001** [iobroker-community-adapters/ioBroker.ring#386]
Moin.

Habe heute Node.JS und NPM meines IoBroker (Raspberry Pi 4B) geupdated. Und konnte dadurch den Ring Adapter von 1.2.8 auf 3.1.3 updaten.
Ich habe also jetzt folgende "Grundkonfig":
JS-Controller:  4.0.23
Node.JS: 16.18.0
NPM: 8.19.2
Ring-Adapter: 3.1.3

im Betrieb:
1x Ring Video Doorbell 2 (unter Info und kind als "doorbell_v4" aufgelistet ?!)
1x Ring StickUp Cam Outdoor (unter Info und kind als "cocoa_camera" aufgelistet)

Seit dem Update ändert sich der status bei der Doorbell unter motion nicht mehr und somit bekomme ich auch keine Bewegungsbenachrichtungen über den Iobroker mehr. Bei der StickUp Cam funktioniert dies hingegen Problem los.
Bei einem druck auf die klingel wird der Datenpunkt "doorbell" kurz auf True gesetzt und unter message die korrekte Nachricht angezeigt. Also funktioniert NUR die Bewegungserkennung NICHT mehr.
Beim Adapter 1.2.8 habe ich den Datenpunkt ring.0.doorbell????????.kind nach "ding" oder "motion" ausgelesen und mir eine entsprechende Nachricht via Telegramm zukommen lassen. Dieser Datenpunkt steht nur dauerhaft auf "on_demand". Und ich müsste ja nun einfach den Datenpunkt ring.0.doorbell???????.Events.type nach "ding" oder "motion" auslesen. Aber dieser sich einfach nicht Ändert und KEINE Bewegung erkannt wird... weiß ich nun nicht mehr weiter.
In der Ring App wird die Bewegung erkannt und angezeigt. (Lasse mich nur da nicht durch die App Benachrichtigen).

UPDATE: Auch ein Update auf die Version 3.1.5 hat keinen Erfolg gebracht. Vielleicht kannst du mir helfen?
Ansonsten VIELEN DANK für die Weiterentwicklung des Adapters!!!!

MfG
Hini2001

**Comment by Hini2001** [comment]
UPDATE:
Habe alle ring-api-cli's und iobroker.ring auf der ring homepage gelöscht. einen neuen Token geniert und den Adapter neu gestartet. Im DEBUG-LogLevel.
Jetzt geht auch die Bewegungserkennung der StickUpCam nicht mehr. :-(

Und im Log stehen dazu diese Fehler:

```
ring.0 | 2022-10-28 10:41:19.537 | debug | Reason: "Error: Not found with response: {"status":404,"error":"Not Found"}"
ring.0 | 2022-10-28 10:41:19.536 | info | Failed subscribing to Motion Events for Einfahrt

ring.0 | 2022-10-28 10:41:19.505 | debug | Reason: "Error: Not found with response: {"status":404,"error":"Not Found"}"
ring.0 | 2022-10-28 10:41:19.504 | info | Failed subscribing to Motion Events for Haustür
```

**Comment by theimo1221** [comment]
Hallo @Hini2001,

> Lasse mich nur da nicht durch die App Benachrichtigen

Zumindest gemäß einiger issues in der ring client api ist die getroffene benachrichtigungseinstellung in der app auch beeinflussen für den Adapter.

Viele Grüße

Thiemo

**Comment by Hini2001** [comment]
Hey @theimo1221
Habe die Benachrichtigungen jetzt aktiviert in der App.
Aber die Bewegungsmeldungen sind seeeeehr sporadisch. Und auch nervig, dass die App auch benachrichtigt. Unter 1.2.8 ging das tatsächlich problemlos. Auch ohne Benachrichtigung.

**Comment by theimo1221** [comment]
> @erniecs die v1 und v2 haben jeweils alle x Sekunden alle Daten von Ring angefordert und gar nicht auf Events reagiert. Sprich es war reine Glückssache, ob du im Idealfall direkt nach dem Event abfragst oder erst 20s später.
> 
> Unabhängig davon ist es auch sowohl für die ioBroker Instanz als auch für die Ringserver eine unnötige Belastung. Warum sollte man alle 5s den ganzen LKW anfordern, wenn die geänderten Sachen (sofern überhaupt etwas passiert ist) auch in einen Briefumschlag passen?

**Comment by Hini2001** [comment]
@theimo1221
Hmmm... Okee. Das wusste ich so nicht. Die Benachrichtigung per Telegramm kam IMMER Instant nach erkennen der Bewegung.
Jetzt allerdings alleine heute 5 Bewegungsmeldungen der App und KEINE via Telegramm. Gestern 10 per App und 2 via Telegramm.
Ich prüfe mal weiter, vielleicht hab ich noch irgendwo einen Haken drin.

**Comment by cptnmolo** [comment]
@Hini2001 konntest du für dich das Problem beheben? Ich habe eine ähnliche Situation mit den sporadischen Bewegungserkennungen seit der Umstellung auf 3.1.3. Weiterhin habe ich das Problem wenn eine Bewegung als Video aufgenommen wird, jedoch ist das Video komplett schwarz. Und das passiert relativ häufig. Was kann die Ursache dafür sein?

**Comment by Hini2001** [comment]
Hey. Ja ich hatte das ganze über einen Umweg realisiert und das lief super.
Ich habe das via Blockly folgendermaßen gelöst gehabt:
![image](https://user-images.githubusercontent.com/58652465/208233641-bf0b4167-0474-4da8-8866-b366bd6235e3.png)

Warum gelöst gehabt?
Seit dem Update auf die Version 3.2.2 bekomme ich jetzt immer nicht nur EINE Nachricht über eine Bewegung, sondern 7 oder 8. Und der Datenpunkt "motion" steht einfach zu lange auf TRUE, um den auszulesen. Ich hoffe, dass das wieder rückgängig gemacht wird und/oder der "motion" status wird schneller wieder auf false gesetzt. oder das man das selber festlegen kann, das wäre natürlich am besten.

**Comment by cptnmolo** [comment]
@Hini2001 : danke für die Blockly Option, werde ich mal ausprobieren.

Ich habe insgesamt 4 Cams, eine DOOR wired und drei Stickup wired Outdoor. Für die Outdoor Cams habe ich keinen Abo, so dass ich mir die Aufnahmen, bei Motion, über den IOB auf das Telegram hab schicken lassen. Funktionierte bis zum Umstieg auf die 3.X.X, nun sieht das folgendermaßen aus:

<img width="583" alt="Bildschirmfoto 2022-12-17 um 22 16 53" src="https://user-images.githubusercontent.com/101291577/208266291-6bb6bcb4-f572-46fa-9648-12a9ad1c554d.png">

Alle *.mp4 Dateien ohne Vorschaubild sind leider nur "Audio"aufnahmen. Mal klappt das, mal nicht. E ist leider zu sporadisch um irgend was einzugrenzen. Wohingegen die Screenshots bei Motion ganz ohne Defekte gesetzt werden.
In der Ring ist mir auch soweit alles ok.
