### ISSUE TITLE
keine Datenpunkte und änderung??

### ISSUE THREAD

**Issue by denjo1982** [iobroker-community-adapters/ioBroker.ring#389]
bei allen versionen die höher wie 3.0.1 sind, werden keine datenpunkte aktuallisiert. ich habe den token neu gemacht, ich habe auch alle geräte aus dem Ring konto einmal gelöscht und die push benachrichtigungen sind auch aktiviert. bei version 3.0.1 funktioniert alles tadellos.

**Comment by theimo1221** [comment]
Duplikat vgl. #284 und #373
