### ISSUE TITLE
API Key kann nicht erstellt werden

### ISSUE THREAD

**Issue by kapsreiter** [iobroker-community-adapters/ioBroker.ring#40]
Hallo Leute

Ich kann mit beiden Befehlen den API Code nicht erzeugen oder auslesen

anbei was ich für Fehlermeldungen bekomme

evtl- könnte mir jemand helfen

lg
tom

<img width="497" alt="Bildschirmfoto 2020-08-23 um 14 02 06" src="https://user-images.githubusercontent.com/69691562/90977955-26d42780-e54a-11ea-97be-0c2ee34efaa5.png">
<img width="497" alt="Bildschirmfoto 2020-08-23 um 14 03 18" src="https://user-images.githubusercontent.com/69691562/90977956-28055480-e54a-11ea-96f1-7c1d68d8d330.png">

<img width="1097" alt="Bildschirmfoto 2020-08-23 um 13 53 27" src="https://user-images.githubusercontent.com/69691562/90977951-23d93700-e54a-11ea-8a2d-ae1a5605f5e5.png">
<img width="1097" alt="Bildschirmfoto 2020-08-23 um 13 55 14" src="https://user-images.githubusercontent.com/69691562/90977954-263b9100-e54a-11ea-9860-96c29fd59627.png">

**Comment by oneill2612** [comment]
wie hat es geklappt ? 
Ich habe gerade das gleiche problem mit der Refreshtoken (Two Face Auth)

**Comment by oneill2612** [comment]
code bekommen 

über Konsole

cd /opt/iobroker/node_modules/iobroker.ring/
dann:
npm i ring-client-api

dann:

cd /opt/iobroker/node_modules/iobroker.ring/node_modules/ring-client-api
node ring-auth-cli
1

**Comment by yavuz007** [comment]
Hallo,
habe das gleiche wie bei oneil2612 gemacht:

C:\iobroker\node_modules\iobroker.ring\node_modules>cd ring-client-api

C:\iobroker\node_modules\iobroker.ring\node_modules\ring-client-api>node ring-auth-cli
This CLI will provide you with a refresh token which you can use to configure ring-client-api and homebridge-ring.
Email: EMAIL
Password: MEINPASSWORT
Error: Failed to fetch oauth token from Ring. You have requested too many 2fa codes.  Ring limits 2fa to 10 codes within 10 minutes.  Please try again in 10 minutes. (error: error requesting 2fa service to send code)
    at RingRestClient.<anonymous> (C:\iobroker\node_modules\iobroker.ring\node_modules\ring-client-api\lib\api\rest-client.js:145:23)
    at Generator.throw (<anonymous>)
    at rejected (C:\iobroker\node_modules\iobroker.ring\node_modules\ring-client-api\lib\api\rest-client.js:25:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

C:\iobroker\node_modules\iobroker.ring\node_modules\ring-client-api>

ich werd verrückt sitze stundenlang und es klappt nicht, habe auch 20min gewartet no chance :( 
bitte helft mir

VG
Yavuz
