### ISSUE TITLE
Installation Ring Adapter:  Cannot install 

### ISSUE THREAD

**Issue by GermanSheepDog** [iobroker-community-adapters/ioBroker.ring#402]
Hallo *,
vielen Dank für den Adapter, den ich leider nicht installieren kann.

Ich nutze eine VM mit ubuntu auf meinem QNAP und starte die Installation im Terminal:

`ich@ubuntu:/opt/iobroker$ iobroker install ring`
`NPM version: 6.14.17`
`Installing iobroker.ring@3.1.3... (System call)`
`host.ubuntu Cannot install iobroker.ring@3.1.3: 1`
`ich@ubuntu:/opt/iobroker$ `
`ich@ubuntu:/opt/iobroker$ uname -a`
`Linux ubuntu 5.4.0-131-generic #147-Ubuntu SMP Fri Oct 14 17:07:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
`ich@ubuntu:/opt/iobroker$`
 
Gibt es eine Idee, wo ich suchen müsste?

**Comment by Grothesk242** [comment]
Installieral mit --debug Option.

**Comment by GermanSheepDog** [comment]
Vielen Dank. Die Debug-Option gibt einen sehr guten Hinweis:

`ich@ubuntu:/opt/iobroker$ iobroker install ring --debug`
`NPM version: 6.14.17`
`Installing iobroker.ring@3.1.3... (System call)`
`npm ERR! code ENOTSUP`
`npm ERR! notsup Unsupported engine for iobroker.ring@3.1.3: wanted: {"node":">=16"} (current: {"node":"14.20.1","npm":"6.14.17"})`
`npm ERR! notsup Not compatible with your version of node/npm: iobroker.ring@3.1.3`
`npm ERR! notsup Not compatible with your version of node/npm: iobroker.ring@3.1.3`
`npm ERR! notsup Required: {"node":">=16"}`
`npm ERR! notsup Actual:   {"npm":"6.14.17","node":"14.20.1"}`

`npm ERR! A complete log of this run can be found in:`
`npm ERR!     /home/iobroker/.npm/_logs/2022-11-20T13_23_19_973Z-debug.log`
`host.ubuntu Cannot install iobroker.ring@3.1.3: 1`
`ich@ubuntu:/opt/iobroker$`#

Ich muss Node auf 16.x updaten!

**Comment by Grothesk242** [comment]
Ja, die v16 ist ja auch schon geraume Zeit die für den ioBroker vorgesehene
Version.
Hätte also schon längst aktualisiert sein sollen.

GermanSheepDog ***@***.***> schrieb am So., 20. Nov. 2022,
14:28:

**Comment by GermanSheepDog** [comment]
Nach dem Update auf node v16.18.1 lässt sich der Adapter installieren. DANKE!
