### ISSUE TITLE
V3.1.9 ist installierbar, aber nicht als Instanz sichtbar

### ISSUE THREAD

**Issue by GermanSheepDog** [iobroker-community-adapters/ioBroker.ring#404]
Ich kann die v3.1.9 von ring installieren und sehe den Adapter in der Adapterübersicht. In der Instanzen-Übersicht fehlt der Adapter dann allerdings. Dies ist unter ubuntu und raspberry gleich. Im Log des raspberry finde ich:
`ring.0 | 2022-11-21 17:20:09.139 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
-- | -- | -- | --`
`ring.0 | 2022-11-21 17:20:09.134 | info | terminating`
`ring.0 | 2022-11-21 17:20:09.132 | info | Closing Adapter`
`ring.0 | 2022-11-21 17:20:09.080 | info | Got terminate signal TERMINATE_YOURSELF`

@alex-meyus und @theimo1221 : Könnt Ihr die Ring Instanz sehen?

_Originally posted by @GermanSheepDog in https://github.com/iobroker-community-adapters/ioBroker.ring/issues/395#issuecomment-1322336116_

**Comment by theimo1221** [comment]
@GermanSheepDog Hast du versucht mit dem + eine Instanz anzulegen?

Bei mir läuft meine bestehende Instanz und auch weitere Instanzen kann ich hinzufügen.
