### ISSUE TITLE
Binary states will be deprecated with js-controller 5.0 - Migrate to Files

### ISSUE THREAD

**Issue by Apollon77** [iobroker-community-adapters/ioBroker.ring#419]
Hello,

with js-controller 5.0 we will deprecate the usage of binary States because "Files" will basically do the same with a better support and less issues. A version after 5.0 the binary States will be removed.

Please Migrate to Files instead.

On questions please use  https://github.com/ioBroker/ioBroker.js-controller/issues/2048

Thank you for your support

**Comment by mcm1957** [comment]
@theimo1221 
Please consider processing this issue with urgent priority as js-controller 5 is already at beta state!

**Comment by Apollon77** [comment]
deprecation means that it is still available ... might just log info messages .. soooo there is a bit of time till controller really removed binary states

**Comment by mcm1957** [comment]
Sorry for incorrect statement.

**Comment by theimo1221** [comment]
With 5.0.0 alpha this is resolved,
Will close on final release

**Comment by foxriver76** [comment]
So this seems fixed according to @theimo1221
