### ISSUE TITLE
Error: spawn ffmpeg ENOENT / Fehler beim 

### ISSUE THREAD

**Issue by SoerenKaiser99** [iobroker-community-adapters/ioBroker.ring#43]
Moin Thorsten,

vielen Dank für den Adapter. Ich habe ein kleines Problem. Wenn der Adapter bzw. die viedeo doorbell 2 selbstständig eine Bewegung erkennt hagel es Fehler beim im Bezug auf ffmpeg. 

Löse ich das ganze aus iobroker via snapshotrequest aus läuft es ohne Probleme mit Ausnahme ders Verweises von WriteFile das dies in zukünftigen Versionen nicht mehr funktionieren wird. 

Die Logs sende ich dir gleich per Mail zu.

Viele Grüße 
Sören

**Comment by Flyor** [comment]
Bei mir geht leider beides nicht - Sobald ich auf Snapshot drücke, startet der Adapter mit dem ENOENT Fehler neu und berichtet, dass er nach 40 versuchen abgebrochen hat. Die Kamera ist verbunden und der Token ist korrekt.

**Comment by schmupu** [comment]
Bitte ffmpeg installieren und dann nochmals testen. Siehe  Anleitung

**Comment by Flyor** [comment]
> Bitte ffmpeg installieren und dann nochmals testen. Siehe Anleitung

Ist installiert und funktioniert auch (in Verbindung mit anderen Adaptern).

**Comment by Andyexe** [comment]
Hallo schmupu,

bei mir kommt auch der Fehler
![Screenshot 2020-11-08 084612](https://user-images.githubusercontent.com/68147299/98459849-0efe5e00-219f-11eb-844e-fed190e560fc.png)

Grüße
Andy

**Comment by schmupu** [comment]
see documentation. 

> Unfortunately the snapshot and livestream function does not work properly. Unfortunately I have no influence on it. Please consider this before you create an issue.

I am sorry I can not do something. Sometimes it works, sometimes not.
