### ISSUE TITLE
Keine Möglichkeit ein Backup mit Backitup zu machen, wenn der Ring Adapter installiert ist.

### ISSUE THREAD

**Issue by Blacky1966** [iobroker-community-adapters/ioBroker.ring#433]
Error Meldung:
_____________________________
Started iobroker ...
[DEBUG] [iobroker] - host.raspberrypi 10190 states saved

[DEBUG] [iobroker] - host.raspberrypi 13560 objects saved

[ERROR] [iobroker] - 
<--- Last few GCs --->

[28366:0x5289f28]    29027 ms: Mark-sweep 927.2 (1042.8) -> 926.5 (1042.8) MB, 99.1 / 0.0 ms  (average mu = 0.901, current mu = 0.809) allocation failure scavenge might not succeed
[28366:0x5289f28]    29305 ms: Mark-sweep 934.2 (1042.8) -> 933.5 (1058.8) MB, 250.4 / 0.0 ms  (average mu = 0.729, current mu = 0.099) allocation failure scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory

[DEBUG] [iobroker] - done
[DEBUG] [javascripts] - Created javascript_tmp directory: "/opt/iobroker/backups/tmpScripts"
[DEBUG] [javascripts] - found Script: Telegram
[DEBUG] [javascripts] - found Script: Fenster_Abfrage
[DEBUG] [javascripts] - found Script: Klingeln_unterdrücken
[DEBUG] [javascripts] - found Script: Routinen_&_Wecker_über_Vis_einstellen
[DEBUG] [javascripts] - found Script: Geklingelt_Schule_Bild_senden
[DEBUG] [javascripts] - found Script: Geklingelt_Zuhause_Bild_senden1
[DEBUG] [javascripts] - Try deleting the Javascript tmp directory: "/opt/iobroker/backups/tmpScripts"
[DEBUG] [javascripts] - Javascript tmp directory "/opt/iobroker/backups/tmpScripts" successfully deleted
[DEBUG] [javascripts] - Backup created: /opt/iobroker/backups/javascripts_2023_01_05-10_02_29_backupiobroker.tar.gz
[DEBUG] [javascripts] - done
[ERROR] [googledrive] - Google Drive: File "/opt/iobroker/backups/iobroker_2023_01_05-10_01_58_backupiobroker.tar.gz" not found
[DEBUG] [googledrive] - Google Drive: Copy javascripts_2023_01_05-10_02_29_backupiobroker.tar.gz...
[DEBUG] [googledrive] - done
[DEBUG] [clean] - done
[DEBUG] [historyHTML] - new history html values created
[DEBUG] [historyHTML] - done
[DEBUG] [historyJSON] - new history json values created
[DEBUG] [historyJSON] - done
[EXIT] 0

**Versions:**  
 Plattform linux
Betriebssystem linux
Architektur arm
CPUs 4 Geschwindigkeit
1800 MHz
Modell ARMv7 Processor rev 3 (v7l)
RAM 7.71 GB
Node.js v16.19.0
timeOffset -60
Anzahl der Adapter 450
NPM 8.19.3
Datenträgergröße 58.23 GB
freier Festplattenspeicher 49.93 GB
Aktive Instanzen 14
Weg /opt/iobroker/
Hostname
raspberrypi

**Comment by gitknd** [comment]
Das kann ich tatsächlich bestätigen, Ich habe den Adapter vor ein paar Tagen installiert und bekomme Backitup Fehler. Das Erstellen des iobroker Backuparchivs findet nicht statt. Sobald ich den Ring Adapter deinstalliere klappt es wieder einwandfrei.
Mit Ring Adapter fehlt im Backup Protokoll die Zeile
[DEBUG] [iobroker] - Backup created: /opt/iobroker/backups/iobroker_xxxx_xx_xx-xx_xx_xx_backupiobroker.tar.gz

Insofern gibt es im weiteren Sicherungsverlauf auch Fehler.

**Comment by gitknd** [comment]
> Insofern gibt es im weiteren Sicherungsverlauf auch Fehler. Bei mir wird über Webdav gesichert und IOBroker läuft unter Docker auf einem Synology. Alle Adapter sind up-to-date

Seit gestern funktioniert das Backup ohne Fehler. Ich habe gestern nur in der RING App (!) die Bewegungsbenachrichtigung bei allen 2 Kameras deaktiviert und später wieder aktiviert. Mehr habe ich diesbezüglich nicht verändert.  Kann das etwas damit zu tun haben ?

**Comment by theimo1221** [comment]
Es kommt vor allem auch auf den Speicherort der Aufnahmen an.
Die sollten entweder im von iobroker angedachten Data Verzeichnis sein, oder komplett außerhalb vom ioBroker Ordner sein.

**Comment by gitknd** [comment]
Ich hatte den Fehler auch schon bei einer frischen Adapter Installation ohne das Aufnahmen gespeichert worden sind. Am Pfad habe ich nichts geändert (ist leer in der Instanz), so dass im Datenpunkt "livestream_file" "/opt/iobroker/iobroker-data/files/ring.0/..." steht, aber diese werden auch regelmäßig gelöscht. Von größeren Datenmengen sprechen wir hier somit nicht. Merkwürdig ist wie gesagt, dass es seit der o.g. Änderung (Bewegungsbenachrichtigung) in der App keine Fehler mehr gibt. Aber einen Datenpunkt für diese Option scheint es auch nicht zu geben (sonst hätte ich die Vermutung gehabt, dass es irgendeinen Fehler im Dateninhalt gab).

**Comment by gitknd** [comment]
Ich habe die Ursache gefunden: es lag am Limit des Arbeitsspeichers. Mein Sohn hat zeitgleich die RAM Begrenzung für diesen Container an dem Tag aufgehoben. Das ist damit auch reproduzierbar und für mich das Thema hier erledigt. Das Protokoll von Blacky deutet ja auf eine ähnliche Ursache hin.

**Comment by mcm1957** [comment]
Dann kann man ja schließen.
