### ISSUE TITLE
Probleme Ring Adapter login/Installation

### ISSUE THREAD

**Issue by freak9882** [iobroker-community-adapters/ioBroker.ring#437]
Hi,

ich kann beim Adapter meine Ring Login Daten nicht eingeben. Token kann ich eingeben, aber meine login Daten halt nicht.
Hab den Adapter auch schon neu installiert, keine Besserung.
![Bildschirm­foto 2023-01-11 um 21 01 05](https://user-images.githubusercontent.com/122542990/212090611-3950eed9-ec65-4937-b00f-76d957e8d426.png)

**Comment by theimo1221** [comment]
Hi

Login geht nur per Token.

**Comment by freak9882** [comment]
OK, alles erneut installiert, jetzt läuft es. Keine Ahnung warum vorher nicht.
