### ISSUE TITLE
Modi Umstellen

### ISSUE THREAD

**Issue by FriMatze** [iobroker-community-adapters/ioBroker.ring#45]
Moin,

kann die Möglichkeit geschaffen werden das die Modi der Ring Doorbell geändert, angezeigt werden können?

**Comment by schmupu** [comment]
Welcher Modi?

**Comment by FriMatze** [comment]
Guten Morgen,

seit einiger Zeit kann man in der App unter Einstellungen Modi (Abwesend, Anwesend, inaktiv) einstellen.

Hinter diesen Modi kann man das Verhalten seiner Ring Anlage beeinflussen.

Das geht aktuell nur manuell. Wäre schön das automatisch auslösen zu können mit Script oder wie auch immer.


[Image.jpeg]

________________________________
Von: Thorsten Stueben <notifications@github.com>
Gesendet: Tuesday, November 3, 2020 5:34:06 PM
An: schmupu/ioBroker.ring <ioBroker.ring@noreply.github.com>
Cc: FriMatze <mathias.rother@icloud.com>; Author <author@noreply.github.com>
Betreff: Re: [schmupu/ioBroker.ring] Modi Umstellen (#45)


Welcher Modi?

**Comment by NormanIGB** [comment]
Ja, das wäre alleine schon aus dem Hintergrund sinnvoll, dass man z.B. auf Bewegungserkennung umschaltet wenn man das Haus verlässt.....

**Comment by Sven1008** [comment]
Würde das Thema auch gerne pushen. Wäre ein extrem nützliches Feature!

**Comment by philipp1987** [comment]
oh ja, diese Funktion wäre wirklich ein Traum, da ich sie gerade suche :D

**Comment by DarthPride** [comment]
Ich würde mich auch freuen, wenn man in dem Adapter den aktuellen Modi auslesen und dann auch wechseln könnte.

**Comment by yogiflop** [comment]
wäre cool wenn das funktionieren würde. !!

**Comment by muehle79** [comment]
Da möchte ich mich anschließen. Vielleicht besteht ja noch die Möglichkeit das es implementiert wird. Wäre auch für mich ein Wunsch.

**Comment by theimo1221** [comment]
Ist in `V3.0.2` eingebaut

**Comment by theimo1221** [comment]
@muehle79, @yogiflop , @FriMatze, @philipp1987, @coolerkerl 
Passt die Änderuung soweit für euch, oder fehlt euch da noch etwas?

Vg Thiemo

**Comment by Agria4800** [comment]
@theimo1221: Seit gestern im Einsatz, funktioniert wie geplant, sehr gute Arbeit, danke dir!!! 👍🏻👍🏻👍🏻👍🏻

**Comment by philipp1987** [comment]
Hey @theimo1221, erstmal vielen Dank für deinen Einsatz. Ich dachte man kann mit dem Modi auch gleichzeitig den chime stumm stellen. Das funktioniert leider nicht, warum auch immer. Habe mein Problem jetzt mit ner hue Steckdose am chime gelöst, und ein Skript gemacht, welches bei ausgeschaltetem chime im EG die Lampen 3x blinken lässt. Das war mein Vorhaben. Aber trotzdem großen Dank

**Comment by yogiflop** [comment]
Hallo,
danke erstmal für das einbauen. Ich persönlich würde mir eine Aufteilung wünschen in "currentState" und "targetState" und den nicht als State, sondern als number.

Vorstellung wäre in etwa:
"0": "home",
"1": "away",
"2": "disarmed",
"3": "disabled",
"4": "unset"

Dadurch ist die Integrierung in YAHKA etc etwas geschmeidiger und wir bei anderen Stati-Systemen auch oft so verwendet.
bis denne

**Comment by muehle79** [comment]
Hallo vielen Dank für die schnelle Integrierung hatte ein paar Probleme mit dem ioBroker und kann es jetzt erst testen. Dem Hinweis von yogiflop finde ich aber schonmal sehr gut und wäre ein Vorschlag den ich unterstützen würde :)

Vielen Dank für die Arbeit

**Comment by theimo1221** [comment]
Stale issue

**Comment by LXZ993** [comment]
Hallo,
tut mir leid das ich das alte Thema wieder hochhole, aber gibt es die Change Modi funktion noch? Bei mir ist da leider nichts womit ich meinen Modi auslesen kann bzw. steuern kann.

**Comment by theimo1221** [comment]
Müsste eigentlich noch da sein, schaue ich später mal im Detail

**Comment by LXZ993** [comment]
> Müsste eigentlich noch da sein, schaue ich später mal im Detail

Das wäre super, danke dir.
Falls es hilft, hier siehst du was ich alles als object bekomme:
https://ibb.co/c2y6KvX
Ebenso wird mir mein Chime nicht angezeigt, weißt du dazu was?

**Comment by Holger-Will** [comment]
bei mir tauchen die Chimes auch nicht auf. Gibt’s dazu schon irgendeine Info?
