### ISSUE TITLE
Cant fetch videos anymore

### ISSUE THREAD

**Issue by melzerto** [iobroker-community-adapters/ioBroker.ring#456]
Seems ring.com has changes something. On my smartphone I freshly had to login
Connection to the ring doorbell works fine.
On iobroker I am still receiving alerts but can't fetch videos or snap shots.
I have generated a new token and updated npm install -g npm@9.4.1 

In the error log it shows

<html><body>

ring.0 | 2023-02-06 09:54:48.052 | info | Recieved new Refresh Token. Will use the new one until the token in config gets changed
-- | -- | -- | --
ring.0 | 2023-02-06 09:54:47.644 | info | Initializing Api Client
ring.0 | 2023-02-06 09:54:47.589 | info | starting. Version 3.2.2 in /opt/iobroker/node_modules/iobroker.ring, node: v16.19.0, js-controller: 4.0.24
host.raspberrypi | 2023-02-06 09:54:43.548 | info | instance system.adapter.ring.0 started with pid 173295
host.raspberrypi | 2023-02-06 09:54:13.487 | info | Restart adapter system.adapter.ring.0 because enabled
host.raspberrypi | 2023-02-06 09:54:13.486 | error | instance system.adapter.ring.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
ring.0 | 2023-02-06 09:54:12.908 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
ring.0 | 2023-02-06 09:54:12.906 | info | terminating
ring.0 | 2023-02-06 09:54:12.889 | error | negotiate codecs failed.
ring.0 | 2023-02-06 09:54:12.887 | error | Error: negotiate codecs failed.     at RTCPeerConnection.setRemoteRTP (/opt/iobroker/node_modules/werift/lib/webrtc/src/peerConnection.js:805:19)     at /opt/iobroker/node_modules/werift/lib/webrtc/src/peerConnection.js:700:22     at Array.map (<anonymous>)     at RTCPeerConnection.setRemoteDescription (/opt/iobroker/node_modules/werift/lib/webrtc/src/peerConnection.js:670:42)     at WeriftPeerConnection.createAnswer (/opt/iobroker/node_modules/ring-client-api/lib/streaming/peer-connection.js:116:23)     at WebrtcConnection.handleMessage (/opt/iobroker/node_modules/ring-client-api/lib/streaming/webrtc-connection.js:29:46)     at /opt/iobroker/node_modules/ring-client-api/lib/streaming/streaming-connection-base.js:38:25     at doInnerSub (/opt/iobroker/node_modules/rxjs/dist/cjs/internal/operators/mergeInternals.js:22:31)     at outerNext (/opt/iobroker/node_modules/rxjs/dist/cjs/internal/operators/mergeInternals.js:17:70)     at OperatorSubscriber._this._next (/opt/iobroker/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:33:21)
ring.0 | 2023-02-06 09:54:12.885 | error | uncaught exception: negotiate codecs failed.

</body>
</html>

**Comment by melzerto** [comment]
little correction: videos will not stored anymore in /home/iobroker/ring but snapshots are working.

**Comment by melzerto** [comment]
SOLVED:
To resolve the issue, access your live stream on ring.com and switch to the Legacy format as prompted. This change is necessary because Ring recently updated to the codec HEVC, used in their battery doorbells.

**Comment by tomtaz01** [comment]
i have the same issue with an new added camera. But i can't update the codec. I doesn't find the setting in browser or in the app. Can u help me?

**Comment by mcm1957** [comment]
> SOLVED: To resolve the issue, access your live stream on ring.com and switch to the Legacy format as prompted. This change is necessary because Ring recently updated to the codec HEVC, used in their battery doorbells.
