### ISSUE TITLE
Floodlight v2

### ISSUE THREAD

**Issue by Elmo127** [iobroker-community-adapters/ioBroker.ring#46]
Hallo,

sobald ich die Instanz starte taucht im Log folgenden Meldung auf:
Device floodlight_v2 not supported!

Wäre es möglich die Floodlight Cam mit aufzunehmen?

Danke und Gruß

**Comment by schmupu** [comment]
Stelle bitte die Ring Instanz auf Debug. Dann benötige ich den Output aus dem Logfile (bitte keine abgeschnittenen Zeilen). Ersetze vorher Username durch XXXXXX / Passwort durch YYYYYY und die Ring ID durch ZZZZZZZ

**Comment by HobboRobin** [comment]
Leider scheint der Kollege der den Post erstellt hat nicht mehr zu antworten. Ich habe allerdings großes Interesse daran das die Cam mit eingebunden wird. Nur leider weiß ich nicht wie ich die Instanz auf debug bekomme ?

Wenn du mir das erklärst kann ich diese meldung sonst gerne posten damit es vorwärts geht 👍

**Comment by theimo1221** [comment]
@schmupu Sende dir meinen Log per PN.

**Comment by bergjet** [comment]
Habe die 1.1.5 beta installiert. Aber eine Floodlight Cam scheint bei mir nicht auf. Es scheint eine Doorbell auf, habe aber keine sondern nur die Floodlight.

**Comment by theimo1221** [comment]
Durch Änderungen nun passend behoben

**Comment by Tripartius** [comment]
Ok, den Thread hier hatte ich tatsächlich übersehen. Sorry dafür.

Aber dennoch checke ich nicht so ganz, was ich jetzt tun muss, damit ich die Cam eingebunden bekomme...?! Wo steht denn, was zu tun ist, oder was ich noch installieren muss oder so...

**Comment by theimo1221** [comment]
Installiere die neuste Version dann sollte es gehen

**Comment by Tripartius** [comment]
Mega! 
Wenn man dann auch weiß, wie man eine noch nicht stable Version installiert, geht es ohne Probleme!!! :)

Super, vielen Dank! Freut mich, dass ich wieder dazugelernt habe!
