### ISSUE TITLE
Adapter installiert jedoch erscheint nichts unter den Objekten

### ISSUE THREAD

**Issue by mandragora666** [iobroker-community-adapters/ioBroker.ring#48]
Hallo,

Erstmals vielen Dank für diesen tollen Adapter.
Ich habe mir eine Ring 3 bestellt die diese Tage geliefert werden soll.

In Vorfreude habe ich mir den Ring Adapter installiert und auch den 2FA Token generieren lassen und alles in der Config des Adapters eingetragen.
Soweit sieht alles gut aus jedoch erscheint bei mir unter den Objekten kein Ring Eintrag wie er hier in den Screenshots gezeigt wird.
Benötige ich hier zuerst die Ring 3 damit mir hier was angezeigt wird oder hab ich hier eventuell noch was nicht beachtet.

Bekomme auch diese Fehlermeldung im Log

ring.0 | 2020-11-20 14:03:05.565 | error | (4688) Error: Could not get devices in getAllRingsDevices(). Error: Could not get all doorbell devices in getAllRingsDeviceObjects(). Error: Could not get device instance in method getDevices(). Erro
-- | -- | -- | --

**Versions:**  
 Node.js
v10.16.0 (Es gibt eine neuere Version: v10.23.0 - Empfohlene Version v12.19.1)
NPM 6.9.0

Vielen lieben Dank schon im Voraus für die Hilfe

mandragora

**Comment by Curry1983** [comment]
Hi,
Ich habe das gleiche Problem, wie oben beschrieben. Bei mir im Ring-System ist eine Doorbell Pro, Stick-Up Cam und eine Mini
Aber mehr als die Fehlermeldung oben im LOG bekomme ich auch nicht.....
Was machen wir falsch?

**Comment by Jaschster** [comment]
Hallo,
ich habe auch das gleiche Problem, wie oben beschrieben. Bei mir funktionierte die Video-Doorbell (2. Generation) zunächst. Ich konnte die Doorbell bis circa Ende Januar in ioBroker nutzen. Nach Netzwerkproblemen habe ich dann die Klingel zurückgesetzt und ich meine danach trat der Fehler auf. Ich habe es jetzt schon mit der Stable- und der Beta-Version ausprobiert und hatte - zumindest bisher - keinen Erfolg. Ziemlich zur gleichen Zeit endete auch der Probezeitraum für die Cloud-Services bei ring. Vielleicht hilft diese Info ja weiter. Auch verschiedene Passwörter und ein neuer Account inklusive der Übernahme des Gerätes dorthin brachten keinen Erfolg... Was mache ich falsch?
In der Regel sitzt das Problem ja 40 cm vor dem Bildschirm und ich mache seither irgendetwas falsch. Treten solche Fälle seit kurzem häufiger auf?


Vielen Dank für die Hilfe und für diesen großartigen Adapter, den ich gerne wieder nutzen würde! :-)

Jaschster

**Comment by denzel1994** [comment]
> Hallo,
> ich habe auch das gleiche Problem, wie oben beschrieben. Bei mir funktionierte die Video-Doorbell (2. Generation) zunächst. Ich konnte die Doorbell bis circa Ende Januar in ioBroker nutzen. Nach Netzwerkproblemen habe ich dann die Klingel zurückgesetzt und ich meine danach trat der Fehler auf. Ich habe es jetzt schon mit der Stable- und der Beta-Version ausprobiert und hatte - zumindest bisher - keinen Erfolg. Ziemlich zur gleichen Zeit endete auch der Probezeitraum für die Cloud-Services bei ring. Vielleicht hilft diese Info ja weiter. Auch verschiedene Passwörter und ein neuer Account inklusive der Übernahme des Gerätes dorthin brachten keinen Erfolg... Was mache ich falsch?
> In der Regel sitzt das Problem ja 40 cm vor dem Bildschirm... Treten solche Fälle seit kurzem häufiger auf?
> 
> Vielen Dank für die Hilfe und für diesen großartigen Adapter, den ich gerne wieder nutzen würde! :-)
> 
> Jaschster

Ebenso bei mir.
