### ISSUE TITLE
missing snapshot and livestream_url

### ISSUE THREAD

**Issue by casino0815** [iobroker-community-adapters/ioBroker.ring#495]
Ich habe den Ring Adapter 3.2.2. installiert.
Funktion ist soweit vollständig gegeben. Leider fehlen bei mir die Einträge in der snapshot_url und livestream_url.
Die history_url wird sauber angezeigt und funktioniert auch. Bei manuellem auslösen des request wird auch der entsprechende snapshot oder livestream im Dateisystem livestream_file bzw. snapshot_file hinterlegt und der log bringt keinerlei fehler.

**Comment by EdWaQ** [comment]
Hab genau das selbe Problem

**Comment by mcm1957** [comment]
Tritt das Problem mit auch noch mit der aktuellen (Beta) Version 3.4.0 auf?

**Comment by mcm1957** [comment]
Close due to missing response
