### ISSUE TITLE
Snapshot Ring Stick Up Cam

### ISSUE THREAD

**Issue by actionbyte** [iobroker-community-adapters/ioBroker.ring#51]
Das Speichern vom Livestream funktioniert einwandfrei. 
Die DPs unter meiner Stick Up Cam "Snapshot file" und "Snapshot URL" sind leer.
Wie kann ich
a) einen Snapshot manuell auslösen und speichern und
b) ein Snapshot / Thumbnail nach Montion speichern, ähnlich der Benachrichtigung von Ring in der Pushnachricht (5 Sekunden nach Motion).
Wenn ich den Snapshot manuell auslöse kommt i.M. im Log leider nur: 

ring.0 | 2020-12-07 21:38:43.146 | error | (14318) Error: Error setSanpshot()): Error: Could not create Snapshot  for 4xxxxx0 in getSnapshot(). Error: Snapshot failed to refresh after  40 attempts
-- | -- | -- | --
ring.0 | 2020-12-07 21:38:43.144 | info | (14318) Starting creating snapshot

**Comment by JayRHa** [comment]
+1


ring.0 | 2021-01-13 12:48:40.118 | error | (3489) Error: Error setSanpshot()): Error: Could not create Snapshot for 5443 in getSnapshot(). Error: Snapshot failed to refresh after 40 attempts
-- | -- | -- | --
ring.0 | 2021-01-13 12:48:40.117 | info | (3489) Starting creating snapshot
ring.0 | 2021-01-13 12:48:27.514 | error | (3489) Error: Error setSanpshot()): Error: Could not create Snapshot for 5443 in getSnapshot(). Error: Snapshot failed to refresh after 40 attempts
ring.0 | 2021-01-13 12:48:27.513 | info | (3489) Starting creating snapshot

**Comment by actionbyte** [comment]
Wurde hierzu schon was in den neueren Versionen 1.1.6 gefixt?
Wann werden diese als latest über die Repository verfügabr sein?
