### ISSUE TITLE
BUG ffmpeg livestream friert nach 10 sec aufnahme ein 

### ISSUE THREAD

**Issue by EnricoBaivo** [iobroker-community-adapters/ioBroker.ring#54]
https://user-images.githubusercontent.com/13745823/103457344-c4acdf80-4cfe-11eb-930c-551d04f38099.mp4

**Describe the bug**  
In dem livestream file bleibt der stream ab 10 Sekunden hängen und dann ist nur noch der Ton zu hören. In der Ring app passiert dies bei mir nicht. Liegt das evtl. An der Leistung des raspberry pi 3b+
**To Reproduce**  
1. Go to ring0 settings and set the liveatream length to 50sek
2. Click on 'request a livestream in the objects panel
3. Check the safed video 

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>
All updated
**Additional context**

**Comment by andrewoe** [comment]
Hi folks,
same here... after installing ring adapter and ffmpeg, stream was recorded and stored. Nevertheless, the video (audio is completely available) freeze after a few second. 
screenshot from log enclosed...
best
Andy

<img width="1331" alt="Bildschirmfoto 2021-01-13 um 14 13 34" src="https://user-images.githubusercontent.com/75129561/104456888-a15d1c80-55a9-11eb-9322-bfd7474eca15.png">
