### ISSUE TITLE
Cannot get livestream-video but snapshot works

### ISSUE THREAD

**Issue by tomtaz01** [iobroker-community-adapters/ioBroker.ring#547]
Hi, 

i have added an new ring outdoor cam, but iobroker could get the livestream file. The Log:
<html><body>

ring.0 | 2023-07-07 20:02:02.458 | info | Device 265205615 ("Garten_neu"): Could't create livestream
-- | -- | -- | --
ring.0 | 2023-07-07 20:02:01.493 | debug | Get Livestream request for 265205615 to value true

</body>
</html>

Other devices there be older works fine. 

Any Ideas?

**Comment by mcm1957** [comment]
Please add revision information:

adapter release
admin release
js-controller release
node version

**Comment by tomtaz01** [comment]
Hello, 
adapter release : 3.4.0
admin release: 6.6.0
js-controller release: 5.0.6
node version: 18.16.0

**Comment by JiroMusik** [comment]
I got the same error on some occasions.
Have got many problems getting this adapter to show the livestreams on my vis but cant really troubleshoot since sometimes Livestreams cant be created.
  "hosts":
      "version": "4.0.24",
  "node": "v18.17.0",
  "arch": "arm",
  "docker": true,
    "admin": {
      "version": "6.3.5",
    "ring": {
      "version": "3.2.2",

**Comment by tomtaz01** [comment]
Hello,

It may be related to Ring turning off legacy mode. Look here:
https://github.com/dgreif/ring/issues/1253
There is already a workaround for the Homebridge users. Can this be integrated into the ioBroker adapter?

**Comment by theimo1221** [comment]
Hello @tomtaz01 
under the hood we use the `ring client api` so, as soon as they release a fix I can push a new version as well.
As the PR got merged (https://github.com/dgreif/ring/pull/1278 ) we might see an update soon.

**Comment by tomtaz01** [comment]
Hi @theimo1221,
thanks for your answer. I just checked and found that there is a new version of the ring-client-api (https://github.com/dgreif/ring/releases/tag/ring-client-api%4012.0.0) this one HVEC should now also accept videos. This has already been implemented for the Homebridge. Will this also be integrated for the ioBroker in the near future?

**Comment by theimo1221** [comment]
Good evening @tomtaz01,

please try again with `V4.0.0` 😃

**Comment by SimonFrank14** [comment]
Hi, 

I've just made a quick test and it seems to work again. Thank you very much.

However, the generated recording is only 20 seconds instead of the configured 60s.

**Comment by theimo1221** [comment]
Please open a new issue regarding live stream ignoring configured duration🙂

**Comment by tomtaz01** [comment]
> Good evening @tomtaz01,
> 
> 
> 
> please try again with `V4.0.0` 😃 

Thank u. It works fine!
