### ISSUE TITLE
Please fix errors reportted by adapter checker

### ISSUE THREAD

**Issue by mcm1957** [iobroker-community-adapters/ioBroker.ring#550]
Please fix issues reported by adapter checker and create a new release:

- If you are using adapter-dev 'npm run translate' all should fix words.js

- Solving E512 should fix issue #374. Most likely the rind adapter does not provide a custom config (I dont see why it should) so correct setting at io-package.json. This error causes a confusing error at other adapters so it must be fixed in near future.

- Missing dataSource and connectionType ar less critical but should be solved too as iio-package.json needs editing anyway.

**NOTE: If you do not have time to fix this, please let us know, I can do it in this case too.**

Please run adapter checker again after fixing issues. You can find it i.e. at www.iobroker.dev

McM1957
----------

❗ [E150] No common.connectionType found in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.ring/blob/master/io-package.json)
 ❗ [E152] No common.dataSource found in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.ring/blob/master/io-package.json)
 ❗ [E506] Word "ringdescription" is not translated to german in [admin/words.js](https://github.com/iobroker-community-adapters/ioBroker.ring/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
 ❗ [E506] Word "ringdescription" is not translated to russian in [admin/words.js](https://github.com/iobroker-community-adapters/ioBroker.ring/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
 ❗ [E512] "admin/jsonCustom.json5" not found, but custom support is declared
 👀 [W171] "common.title" is deprecated in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.ring/blob/master/io-package.json)
 👀 [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
 👀 [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
 👀 [W170] "common.keywords" should not contain "iobroker, adapter, smart home" [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.ring/blob/master/io-package.json)
 👀 [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
 👀 [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package

**Comment by theimo1221** [comment]
Only these 2 are left:




[W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
[W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package
