### ISSUE TITLE
Verbindungsprobleme

### ISSUE THREAD

**Issue by philipp1987** [iobroker-community-adapters/ioBroker.ring#552]
Hallo,

ich habe seit einigen Tagen keine Verbindung mehr. Neuinstallation des Adapters und mehrfaches Token vergeben führt nicht zum Erfolg. Der Adapter wird kurz GRÜN und schaltet danach wieder auf ROT. Ich bitte um Hilfe. Version 3.2.2

**Comment by theimo1221** [comment]
Moin @philipp1987, 

hast du dich zwischendurch mal in der App angemeldet?

VG Thiemo

**Comment by philipp1987** [comment]
ja habe ich. das funktioniert tadellos. komischerweise musste ich mich aber erneut anmelden. ich versuche nochmal einen reload von dem token.

**Comment by philipp1987** [comment]
@theimo1221 leider kein erfolg.

TypeError: locs is not iterable at /opt/iobroker/node_modules/iobroker.ring/build/lib/ringApiClient.js:144:35 at processTicksAndRejections (node:internal/process/task_queues:96:5)

Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

Error: Refresh token is not valid. Unable to authenticate with Ring servers. See https://github.com/dgreif/ring/wiki/Refresh-Tokens at RingRestClient.getGrantData (/opt/iobroker/node_modules/ring-client-api/lib/rest-client.js:123:15) at RingRestClient.getAuth (/opt/iobroker/node_modules/ring-client-api/lib/rest-client.js:126:32) at RingRestClient.getAuth (/opt/iobroker/node_modules/ring-client-api/lib/rest-client.js:155:29) at processTicksAndRejections (node:internal/process/task_queues:96:5)

das sind 3 der fehlermeldungen.

**Comment by philipp1987** [comment]
@theimo1221 wenn ich mich über den browser anmelde steht bei "authorisierte Clientgeräte" "Gerätename nicht gefunden - Unbekannte Geräte sind möglicherweise nicht unterstützte Geräte oder weniger häufig verwendete Browser"

**Comment by theimo1221** [comment]
> Error: Refresh token is not valid. Unable to authenticate with Ring servers.

Dies ist der entscheidende Fehler: Beim Einfügen des Token sind da ausversehen Zeilenumbrüche bei?

**Comment by philipp1987** [comment]
@theimo1221 ich werde es morgen nochmal versuchen. Liege schon im bett. Vielen Dank schonmal für deinen Support 🤝
