### ISSUE TITLE
Unsupported Device Info: RingCamera

### ISSUE THREAD

**Issue by werner2000x** [iobroker-community-adapters/ioBroker.ring#553]
My Logs in ioBroker:
info:
Unsupported Device Info: RingCamera { subscriptions: [ [SafeSubscriber] ], initialData: { id: 331847520, kind: 'cocoa_doorbell_v2', description: 'Haustür', location_id: '226564fa-c799-4b4c-8d27-e0205650ffaa', schema_id: null, is_sidewalk_gateway: false, created_at: '2023-07-12T17:02:23Z', deactivated_at: null, owner: [Object], device_id: '90486c645890', time_zone: 'Europe/Berlin', firmware_version: 'Up to Date', latitude: 51.95543, longitude: 7.98705, address: '', owned: true, stolen: false, ring_id: null, shared_at: null, health: [Object], subscribed: true, subscribed_motions: true, battery_life: '100', external_connection: true, ring_net_id: null, active_schedule_uuid: null, alerts: [Object], motion_snooze: null, settings: [Object], features: [Object], ext_power_state: 3 }, isDoorbot: true, restClient: RingRestClient { authOptions: [Object], refreshToken:

error:
Device with Type cocoa_doorbell_v2 not yet supported, please inform dev Team via Github

**Comment by theimo1221** [comment]
Should work with 3.4.1
