### ISSUE TITLE
1.1.3 - Could not get devices in getAllRingsDevices()

### ISSUE THREAD

**Issue by CXylander** [iobroker-community-adapters/ioBroker.ring#56]
ring.0	2021-01-15 23:52:38.022	error	(8184) Error: Error setHistory(): Error: Could noch get Hisotry for xxxxxxxx in getHistory(id).Error: Could not get Doorbell for xxxxxxxx in getAllRingsDeviceObject(id). Error: Could not get all doorb
ring.0	2021-01-15 23:52:38.021	error	(8184) Error: Error setHealth(): Error: Could not get Health for xxxxxxxx in getHealthSummarie(id). Error: Could not get Doorbell for xxxxxxxx in getAllRingsDeviceObject(id). Error: Could not get all
ring.0	2021-01-15 23:52:38.021	error	(8184) Error: Error setInfo(): Error: Could not get Doorbell for xxxxxxxx in etAllRingsDevice(id). Error: Could not get devices in getAllRingsDevices(). Error: Could not get all doorbell devices in ge
ring.0	2021-01-15 23:52:38.020	info	(8184) Starting Ring Device for Id xxxxxxxx
ring.0	2021-01-15 23:52:21.827	error	(8184) Error: Could not get devices in getAllRingsDevices(). Error: Could not get all doorbell devices in getAllRingsDeviceObjects(). Error: Could not get ring instance in method getRing(). TypeError:
ring.0	2021-01-15 23:51:21.827	error	--- property '_parentOrParents' closes the circle
ring.0	2021-01-15 23:51:21.827	error	| index 0 -> object with constructor 'SwitchMapSubscriber'
ring.0	2021-01-15 23:51:21.827	error	| property '_subscriptions' -> object with constructor 'Array'
ring.0	2021-01-15 23:51:21.827	error	--> starting at object with constructor 'Subscriber'
ring.0	2021-01-15 23:51:21.827	error	(8184) Error: Error setHistory(): Error: Could noch get Hisotry for xxxxxxxx in getHistory(id).Error: Could not get Doorbell for xxxxxxxx in getAllRingsDeviceObject(id). Error: Could not get all door
ring.0	2021-01-15 23:51:21.827	error	--- property '_parentOrParents' closes the circle
ring.0	2021-01-15 23:51:21.827	error	| index 0 -> object with constructor 'SwitchMapSubscriber'
ring.0	2021-01-15 23:51:21.827	error	| property '_subscriptions' -> object with constructor 'Array'
ring.0	2021-01-15 23:51:21.827	error	--> starting at object with constructor 'Subscriber'
ring.0	2021-01-15 23:51:21.827	error	(8184) Error: Error setHealth(): Error: Could not get Health for xxxxxxxx in getHealthSummarie(id). Error: Could not get Doorbell for xxxxxxxx in getAllRingsDeviceObject(id). Error: Could not get all
ring.0	2021-01-15 23:51:21.827	error	--- property '_parentOrParents' closes the circle
ring.0	2021-01-15 23:51:21.827	error	| index 0 -> object with constructor 'SwitchMapSubscriber'
ring.0	2021-01-15 23:51:21.827	error	| property '_subscriptions' -> object with constructor 'Array'
ring.0	2021-01-15 23:51:21.827	error	--> starting at object with constructor 'Subscriber'
ring.0	2021-01-15 23:51:21.827	error	(8184) Error: Error setInfo(): Error: Could not get Doorbell for xxxxxxxx in etAllRingsDevice(id). Error: Could not get devices in getAllRingsDevices(). Error: Could not get all doorbell devices in g
ring.0	2021-01-15 23:51:21.826	info	(8184) Starting Ring Device for Id xxxxxxxx

Ring:    1.1.3
Admin:  4.1.11
Node.js  v12.20.1
NPM     6.14.11

**Comment by TbsJah** [comment]
Update 1.1.5
A new token is needed
In my case it was necessary to delete the instance and create it again.
After that it worked
