### ISSUE TITLE
ReOpen #548 Flapping DP on Motion AND/OR Pressing Doorbell

### ISSUE THREAD

**Issue by Hini2001** [iobroker-community-adapters/ioBroker.ring#563]
The Issue #548 is still an actual Issue. Even after the mentioned solution of updating Adapter to 3.4.1

**Comment by mcm1957** [comment]
Please specifiy related releases:
adapter:
admin:
js-controller:
node:
npm:
o/s type:

**Comment by theimo1221** [comment]
Duplicate
