### ISSUE TITLE
HTTPS URLs Domain missing

### ISSUE THREAD

**Issue by crocri** [iobroker-community-adapters/ioBroker.ring#564]
Hi!
URLs without Domain, but with https doesn‘t work.
Please add domain to the Host name ( for example to the snapshot_url field)

Wrong:
https://Hostname:8082/… - no certificate avail.
Correct:
https://Hostname.example.de:8082/…..

**Comment by mcm1957** [comment]
Please specifiy related releases:
adapter:
admin:
js-controller:
node:
npm:
o/s type:

**Comment by theimo1221** [comment]
Good Evening
@crocri I guess you should report this at https://github.com/ioBroker/ioBroker.web as this is not ring adapter specific in my opinion

**Comment by crocri** [comment]
Hello!
For sure it is ring adapter specific!
So far as I know, it‘s related to the definitions of the adapter, but I‘m not a developer. Similar errors were corrected before for Node-red adapter and admin adapter….

Latest adapter direct loaded from github (3.4.1), but for this kind of error it doesn‘t matter.
Nevertheless here the releases:
admin 6.3.5
js-controller 7.0.3
node 18.17.0
npm 9.6.7

br
Crocri

**Comment by crocri** [comment]
After some tests, adapter.host returns only name without domain. But opening ioBroker overview, all the names with https are correct. Here the domain is added to the hostname.
If i change the host name itself to FQDN, url‘s from ring adapter are correct too.
In my opinion this behaviour is not really consistent…

br
Crocri
