### ISSUE TITLE
Timestamp wrong (GMT + 1), but shown as GMT+2

### ISSUE THREAD

**Issue by crocri** [iobroker-community-adapters/ioBroker.ring#567]
Hello!
All ring timestamps differ for one hour.
For example the ring.0.Snapshot.moment is always one hour behind.
If I look into my ios Ring app, the time is shown correctly and also ioBroker time is correct.

 - Adapter version: 4.0.0
 - JS-Controller version: 7.0.3
 - Node version: 18.17.0
 - Operating system: Linux (iobroker docker)

![image](https://github.com/iobroker-community-adapters/ioBroker.ring/assets/55567276/8c0ca68e-8e05-4f17-aa29-f34a995358bc)

Best regards
Crocri

**Comment by mcm1957** [comment]
js-controller 7 is not yet released 🤔

**Comment by mcm1957** [comment]
I do not really believe
Unless you perform timejumps

Current stable js-controller 4.x.x
Current latest js-controller 5.x.x

So js-controller 7 will be implemented 2024/2025

😀

**Comment by mcm1957** [comment]
I dont think so as js-controller 7 is not even started to develop 😉

Maybe your using 5.x.x

**Comment by crocri** [comment]
You're correct, my fault.
I meant the javascript adapter, not the js-controller.
js-controller has version 4.0.24

Looking forward to js-controller 7 ;-)

Best regards
Crocri
