### ISSUE TITLE
Cannot write file 1610959222940.mp4: ring.0 is not an object of type "meta"

### ISSUE THREAD

**Issue by TbsJah** [iobroker-community-adapters/ioBroker.ring#57]
After update of JS Controller no creation of video or screenshot is possible

![image](https://user-images.githubusercontent.com/34193151/104891475-49d7fb80-5971-11eb-9eb0-0c875d407551.png)

Ring: 1.1.5
Admin: 4.1.11
JS 3.2.7
Node.js v12.20.1
NPM 6.14.10

**Comment by schmupu** [comment]
Snapshot & video functionality is a beta version. Unfortunately there is no chance to fix it

**Comment by TbsJah** [comment]
Very sad to hear that.
Then the adapter is currently not usable for me

Is the cause due to the new JS controller?
Until this update it worked without problems

**Comment by TbsJah** [comment]
> Snapshot & vide

I'm sorry to bother you again.
I know it is beta - but what is the current reason why it does not work?
It happens after upgrade from js controller to 3.2. Is the new version the reason?

**Comment by Thomas-Doc** [comment]
Bei mir funktioniert der snapshot bestens (hab allerdings einen anderen Verzeichnispfad erstellen müssen). Absolut zuverlässig! Allerdings hab ich genau dieselbe Fehlermeldung bei jedem Auslösen eines snapshot im log. "ring.0 is not an object of type meta". Glaube, früher war das nur eine Warnung, jetzt ist es ein error. Aber das Bild ist zuverlässig im Verzeichnispfad.

**Comment by theimo1221** [comment]
Müsste mit #64 behoben sein

**Comment by Merexor** [comment]
Hab leider mit der Ring Doorbell View Cam das gleiche Problem...

Error: Error setSanpshot()): Error: Could not create Snapshot for xxxxxxxxxx in getSnapshot(). Error: Snapshot failed to refresh after 40 attempts

Error: Error setSanpshot()): Error: ring.0 is not an object of type "meta"
Cannot write file doorbell_xxxxxxxxxxx/snapshot29170532_1616320185460.jpg: ring.0 is not an object of type "meta"

der Fehler kommt einfach immer wenn ein Snapshot oder ein Video gemacht werden soll, entweder durch "motion" oder "ding".
