### ISSUE TITLE
Device spotlightw_v2 not supported!

### ISSUE THREAD

**Issue by d3aconfrost** [iobroker-community-adapters/ioBroker.ring#60]
Hello,

the adapter worked well for my four Spotlight Wired cameras until last week I received a replacement camera because one was defective. The three "old" cameras continue working with the adapter, they have the "kind" hp_cam_v2. The new one however doesnbt work. The LOG gives me the following:

ring.0 | 2021-02-28 20:50:40.539 | info | (22542) Device spotlightw_v2 not supported!
-- | -- | -- | --

Maybe the newer models have a different "kind". It would be very nice of you if you could add this kind somehow.

Thank you very much for your help!

**Comment by GianfrancoSinistra** [comment]
Hi, bei mir ist das gleiche Problem "Device spotlightw_v2 not supported!"  dabei ist auch die neuste -3 Version des Adapters nicht hilfreich gewesen.
gibt es eine Info was hier passiert ist, warum das alte Modell funktionierte?

Grüße
Gianfranco

**Comment by theimo1221** [comment]
Hi

Was steht bei euren alten Geräten bei Kind?

Sind die neuen Kameras von der Funktionen ansonsten identisch nur die normalen Nachfolger?
Sonst nehme ich die erstmal so auf und ihr probiert bitte ob damit die neuen bisher unbekannten Geräte greifen.

Alternativ brauche ich einmal die json welches euer Gerät bei aktiviertem Debug Log Level ausspucken.
Gerne auch annonymisiert (eure persönlichen Daten entfernt) und per Email.

**Comment by d3aconfrost** [comment]
Hallo theimo1221,

bei den drei anderen "alten" Kameras die ich habe, steht bei kind folgendes:
![1](https://user-images.githubusercontent.com/79809126/114076169-a7ac1d80-98a6-11eb-9820-1d6b62a627ec.JPG)

Die neue Kamera ist vom Model und den Funktionen her identisch zur alten. Sie wird im iobroker natürlich unter Objekten nicht aufgeführt. Mit dem Begriff JSON hatte ich leider bisher nichts am Hut, wenn ich eine Anleitung bekomme aber gerne :)

Beste Grüße

**Comment by d3aconfrost** [comment]
Ich habe nach dem Update  folgendes im Log:


ring.0 | 2021-04-09 10:26:24.565 | error | (11851) Error: Could not get devices in getAllRingsDevices(). Error: Could not get all doorbell devices in getAllRingsDeviceObjects(). Error: Could not get device instance in method getDevices(). Err
-- | -- | -- | --


Die Kamera ist unter den Objekten nicht dazugekommen.

**Comment by theimo1221** [comment]
Stell mal bitte unter Instanzen auf Expertenmodus und dann den Ring Adapter auf "debug" Modus setzen.

Ich hoffe dann erhalten wir ein paar mehr Infos.

**Comment by GianfrancoSinistra** [comment]
Guten Morgen,

ich bekomme dann diese Meldung: (ich habe die ID und Device ID gelöscht,
ich weiß nicht ob die daten relevant sind.)
es handelt sich um die Verkabelte Variante. daher ist "Battery life2 eher
falsch, aber sicher auch nicht tragisch. war nur ein Gedanke, weil
vielleicht eben falsche Cam?
ring.0 2021-04-10 07:11:51.440 debug (8703) Device:
{"id":gelöscht,"description":"Terrasse","device_id":"gelöscht","time_zone":"Europe/Berlin","subscribed":true,"subscribed_motions":true,"battery_life":100,"external_connection":false
ring.0 2021-04-10 07:11:51.438 debug (8703) Ring:
{"options":{"refreshToken":"eyJhbGciOiJIUzUxMiIsImprdSI6Ii9vYXV0aC9pbnRlcm5hbC9qd2tzIiwia2lkIjoiYzEyODEwMGIiLCJ0eXAiOiJKV1QifQ.eyJpYXQiOjE2MTc3OTYzMTQsInJlZnJlc2hfY2lkIjoicmluZ19vZmZpY2lh
ring.0 2021-04-10 07:11:51.436 debug (8703) Ring:
{"options":{"refreshToken":"eyJhbGciOiJIUzUxMiIsImprdSI6Ii9vYXV0aC9pbnRlcm5hbC9qd2tzIiwia2lkIjoiYzEyODEwMGIiLCJ0eXAiOiJKV1QifQ.eyJpYXQiOjE2MTc3OTYzMTQsInJlZnJlc2hfY2lkIjoicmluZ19vZmZpY2lh
ring.0 2021-04-10 07:11:36.435 info (8703) Device spotlightw_v2 not
supported!
hab ihn jetzt eine Weile laufen lassen, es kommen immer diese Meldungen.

Danke dir Vorab für die Unterstützung und ein schönes Wochenende-
Grüße
Gianfranco


Am Fr., 9. Apr. 2021 um 22:10 Uhr schrieb Thiemo Hoffmann <
***@***.***>:

**Comment by GianfrancoSinistra** [comment]
Guten Morgen,

ich bekomme dann diese Meldung: (ich habe die ID und Device ID gelöscht,
ich weiß nicht ob die daten relevant sind.)
es handelt sich um die Verkabelte Variante. daher ist "Battery life2 eher
falsch, aber sicher auch nicht tragisch. war nur ein Gedanke, weil
vielleicht eben falsche Cam?


`ring.0 | 2021-04-10 07:11:51.440 | debug | (8703) Device: {"id":gelöscht,"description":"Terrasse","device_id":"gelöscht","time_zone":"Europe/Berlin","subscribed":true,"subscribed_motions":true,"battery_life":100,"external_connection":false`

`ring.0 | 2021-04-10 07:11:51.438 | debug | (8703) Ring: {"options":{"refreshToken":"eyJhbGciOiJIUzUxMiIsImprdSI6Ii9vYXV0aC9pbnRlcm5hbC9qd2tzIiwia2lkIjoiYzEyODEwMGIiLCJ0eXAiOiJKV1QifQ.eyJpYXQiOjE2MTc3OTYzMTQsInJlZnJlc2hfY2lkIjoicmluZ19vZmZpY2lh`

`ring.0 | 2021-04-10 07:11:51.436 | debug | (8703) Ring: {"options":{"refreshToken":"eyJhbGciOiJIUzUxMiIsImprdSI6Ii9vYXV0aC9pbnRlcm5hbC9qd2tzIiwia2lkIjoiYzEyODEwMGIiLCJ0eXAiOiJKV1QifQ.eyJpYXQiOjE2MTc3OTYzMTQsInJlZnJlc2hfY2lkIjoicmluZ19vZmZpY2lh`

`ring.0 | 2021-04-10 07:11:36.435 | info | (8703) Device spotlightw_v2 not supported!
`

Hab ihn jetzt eine Weile laufen lassen, es kommen immer diese Meldungen.

Danke dir Vorab für die Unterstützung und ein schönes Wochenende-
Grüße
Gianfranco

**Comment by theimo1221** [comment]
Moin, 

`Unsupported Device Info: ...`

Dies müsste direkt nach der `not supported` Meldung kommen
Der Inhalt wäre relevant.

Welche Version ist installiert?

VG Thiemo

**Comment by d3aconfrost** [comment]
Ich erhalte dies:


ring.0 | 2021-04-10 22:30:15.799 | error | (1088) Error: Could not get devices in getAllRingsDevices(). Error: Could not get all doorbell devices in getAllRingsDeviceObjects(). Error: Could not get device instance in method getDevices(). Error
-- | -- | -- | --
ring.0 | 2021-04-10 22:30:01.055 | debug | (1088) system.adapter.admin.0: logging true
ring.0 | 2021-04-10 22:30:00.165 | error | (1088) Error: Could not get devices in getAllRingsDevices(). Error: Could not get all doorbell devices in getAllRingsDeviceObjects(). Error: Could not get device instance in method getDevices(). Erro
ring.0 | 2021-04-10 22:29:59.932 | info | (1088) Starting Adapter ring.0 in version 1.2.1
ring.0 | 2021-04-10 22:29:59.914 | info | (1088) starting. Version 1.2.1 in /opt/iobroker/node_modules/iobroker.ring, node: v12.22.1, js-controller: 3.2.16

**Comment by theimo1221** [comment]
`ring.0 | 2021-04-10 07:11:36.435 | info | (8703) Device spotlightw_v2 not supported!` das hier kommt bei dir nicht?

**Comment by GianfrancoSinistra** [comment]
Hi, die 1.1.3. Allerdings hab ich es mit den Versionen bi 1.1.6-3 auch getestet.  Immer das selbe. 
LG
Gianfranco

**Comment by theimo1221** [comment]
> Hi, die 1.1.3. Allerdings hab ich es mit den Versionen bi 1.1.6-3 auch getestet. Immer das selbe.
> LG
> Gianfranco

Die Debug Nachricht nach `ring.0 | 2021-04-10 07:11:36.435 | info | (8703) Device spotlightw_v2 not supported!`
welche mit  `Unsupported Device Info:` beginnt wäre wichtig. Dann kann ich das nochmal passend anpassen.

**Comment by GianfrancoSinistra** [comment]
> > Hi, die 1.1.3. Allerdings hab ich es mit den Versionen bi 1.1.6-3 auch getestet. Immer das selbe.
> > LG
> > Gianfranco
> 
> Die Debug Nachricht nach `ring.0 | 2021-04-10 07:11:36.435 | info | (8703) Device spotlightw_v2 not supported!`
> welche mit `Unsupported Device Info:` beginnt wäre wichtig. Dann kann ich das nochmal passend anpassen.

Kommt leider nichts. Immer nur die 3 Meldungen, im Takt.
Kann ich irgendwo was umstellen, um es zu sehen?

**Comment by theimo1221** [comment]
Mit der 1.1.6-3 müsstest du es sehen, sobald du auf Debug Log Level unter Instanzen mit Expertenmodus gestellt hast.

**Comment by GianfrancoSinistra** [comment]
Moin. Mit dem 1.2.1 klappt es jetzt.
Sehr guter Job. Danke dir. Mal sehen ob er rund läuft. 

Grüße und Danke nochmal
