### ISSUE TITLE
Zu viele Motion Events

### ISSUE THREAD

**Issue by exaware** [iobroker-community-adapters/ioBroker.ring#602]
Hallo, 
Ich habe das automatische Aufzeichnen von Livestreams bei erkannter Bewegung aktiviert. Ich habe aber das Problem, dass mehr Videos gespeichert werden als die Doorbell erkannt hat, im Schnitt 2 Videos mehr. In der Ring App kann man im Ereignisverlauf die erkannten Bewegungen genau nachvollziehen. Ich hab die Version 5.0.1 drauf. 
Könnt ihr das auch bestätigen? Ist das Problem bereits bekannt?

**Comment by Chris25122** [comment]
Selbes Problem hier seit vielen Versionen. Eine einzelne Bewegung löst bei mir 2-6 Events aus

**Comment by exaware** [comment]
Hallo @theimo1221,
ich möchte wirklich nicht drängen aber es ist wirklich nervig, wenn ich bei einer Bewegungserkennung 6x30s Videos per Telegramm zugeschickt bekomme. In der alten Version (3.2.2) hatte ich dieses Problem nicht. Leider läuft diese Version nicht mehr, da gibt es irgendwie Probleme mit dem Token. Deshalb bin ich auf die Version 5.0.1 gewechselt, welche bis auf den Fehler mit den zu vielen Events super ist. Ist dir irgend etwas darüber bekannt? Wenn nein, könnten wir uns das mal zusammen an meinem System analysieren?

**Comment by theimo1221** [comment]
@exaware Please try 5.0.6 and take a look at the new options regarding event blocking

**Comment by exaware** [comment]
@theimo1221 thank you.
I installed version 5.0.6 and set blocking to 15 seconds.
I will watch an report here.

**Comment by exaware** [comment]
Hello @theimo1221,
I tried with the event blocking option. Now it's much better.
Just for my understanding, if I set the blocking time to 2 minutes, I won't be able to receive any more motion events for two minutes, right?

**Comment by theimo1221** [comment]
Hello @exaware, 

Yes that camera is blocked for motion than. And if you check the box to keep ignoring on rerigger any motion within that 2 minutes blocking frame would restart that 2 minutes timer.

Best Regards

**Comment by exaware** [comment]
Hello @theimo1221,

I was happy too soon. Unfortunately it doesn't work also with blocking time. I tried until 3 Minutes. Today according Ring app I had 8 motion events. The Ring adapter triggered 26 motion events.

**Comment by exaware** [comment]
Hello @theimo1221,

I think I found the reason of the multiple motion events. In my script I react if the url of the livestream changed. Today I recognized that the url changed if motion 'true' and 'false'. Then I added a check and react only if the url changed and motion is 'false'. Since this change I got only one lievstream to much. Than I wanted to check this with v5.0.6 with a blocking time again but now my system get damaged if I update the adapter to v5.0.7 (see issue #614).

**Comment by exaware** [comment]
@theimo1221 
With my new logic the number of wrong movement events was reduced. But sometimes the last movement event is followed by a wrong movement event.
What is the difference of the motion recognition ring app vs. ring adapter? Don't use both the ring api?

**Comment by exaware** [comment]
To get an overview, I disabled all event blocking options (screenshot1) and capture the motion event and also when the file changed (screenshot2).

![image](https://github.com/iobroker-community-adapters/ioBroker.ring/assets/55593493/71ad69b4-e60c-432f-8049-f2e8a4182b4f)

I only save the videos when motion and file change is true. In this case 3 videos was saved but a realy motion was only at video 1. And the ring app recognised also only 1 motion. There was no motion at video 2 and video 3, this triggers was wrong. This behavior I have multiple time a day. 
Can the developers explain me why the ring app recognized only one motion and why the ring adapter recognized 3 motions? Is it not the same api?

![image](https://github.com/iobroker-community-adapters/ioBroker.ring/assets/55593493/032414e9-37b4-41af-9c8f-e4f4bc7b3ad6)

**Comment by theimo1221** [comment]
I'm neither a developer at ring, nor is their code online.

Additionally I don't understand why you look for those file changes, as there is a data point for the event.

**Comment by exaware** [comment]
I also tried it only with the motion events. The only reason why I look for the file changes is because I tried to avoid the wrong recognizes.

**Comment by exaware** [comment]
@theimo1221 
How can I use the motion datapoint if it id so 
crazy like in the screenshot. Which signal I should use to send the file? Which file should send? Sorry but the motion event is verry buggy.

**Comment by exaware** [comment]
I'm closing this ticket because no one seems to care.

**Comment by exaware** [comment]
Update: Ich habe inzwischen herausgefunden, dass die fehlerhaften Ereignisse durch eine schlechte WLAN-Verbindung verursacht werden. Obwohl die Verbindung in der Ring-App grün angezeigt wird, scheint die Verbindung ab und zu schlecht zu sein. In so einem Fall gibt es dann Artefakte bzw. das ganze Bild bewegt sich. Diese Änderungen im Video lösen dann Ereignisse aus.

Meine Lösung: Ich habe mir eine open source offline KI (YOLOv8) installiert, welche die Videos auf Personen scannt. Ich bekomme nun nur dann Nachrichten, wenn auf den Videos eine Person erkannt wurde. Die Erkennung ist sehr gut.
