### ISSUE TITLE
Adapter startet nicht V5.0.6

### ISSUE THREAD

**Issue by niiccooo1** [iobroker-community-adapters/ioBroker.ring#612]
**Describe the bug**  
After updating ring adapter to version 5.0.6 the instance doesn´t start anymore.

Log:
`<html>
<body>

host.iobroker | 2023-11-02 14:51:58.701 | info | Rebuild for adapter system.adapter.ring.0 not successful in 3 tries. Adapter will not be restarted again. Please execute "npm install --production" in adapter directory manually.
-- | -- | -- | --
host.iobroker | 2023-11-02 14:51:58.701 | error | instance system.adapter.ring.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.iobroker | 2023-11-02 14:51:58.701 | error | Caught by controller[0]: Node.js v18.18.2
host.iobroker | 2023-11-02 14:51:58.701 | error | Caught by controller[0]: }
host.iobroker | 2023-11-02 14:51:58.700 | error | Caught by controller[0]: ]
host.iobroker | 2023-11-02 14:51:58.700 | error | Caught by controller[0]: '/opt/iobroker/node_modules/iobroker.ring/build/main.js'
host.iobroker | 2023-11-02 14:51:58.700 | error | Caught by controller[0]: '/opt/iobroker/node_modules/iobroker.ring/build/lib/ringApiClient.js',
host.iobroker | 2023-11-02 14:51:58.700 | error | Caught by controller[0]: '/opt/iobroker/node_modules/iobroker.ring/build/lib/ownRingCamera.js',
host.iobroker | 2023-11-02 14:51:58.700 | error | Caught by controller[0]: requireStack: [
host.iobroker | 2023-11-02 14:51:58.700 | error | Caught by controller[0]: code: 'MODULE_NOT_FOUND',
host.iobroker | 2023-11-02 14:51:58.700 | error | Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1143:19) {
host.iobroker | 2023-11-02 14:51:58.700 | error | Caught by controller[0]: at Module._load (node:internal/modules/cjs/loader:960:12)
host.iobroker | 2023-11-02 14:51:58.700 | error | Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:1119:32)
host.iobroker | 2023-11-02 14:51:58.699 | error | Caught by controller[0]: at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
host.iobroker | 2023-11-02 14:51:58.699 | error | Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1256:14)
host.iobroker | 2023-11-02 14:51:58.699 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.ring/build/lib/ownRingCamera.js:41:25)
host.iobroker | 2023-11-02 14:51:58.699 | error | Caught by controller[0]: at require (node:internal/modules/cjs/helpers:119:18)
host.iobroker | 2023-11-02 14:51:58.699 | error | Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1143:19)
host.iobroker | 2023-11-02 14:51:58.699 | error | Caught by controller[0]: at Module._load (node:internal/modules/cjs/loader:922:27)
host.iobroker | 2023-11-02 14:51:58.699 | error | Caught by controller[0]: at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
host.iobroker | 2023-11-02 14:51:58.699 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.ring/build/main.js
host.iobroker | 2023-11-02 14:51:58.699 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.ring/build/lib/ringApiClient.js
host.iobroker | 2023-11-02 14:51:58.698 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.ring/build/lib/ownRingCamera.js
host.iobroker | 2023-11-02 14:51:58.698 | error | Caught by controller[0]: Require stack:
host.iobroker | 2023-11-02 14:51:58.698 | error | Caught by controller[0]: Error: Cannot find module './services/image-service'
host.iobroker | 2023-11-02 14:51:58.698 | error | Caught by controller[0]: ^
host.iobroker | 2023-11-02 14:51:58.698 | error | Caught by controller[0]: throw err;
host.iobroker | 2023-11-02 14:51:58.698 | error | Caught by controller[0]: node:internal/modules/cjs/loader:1080
host.iobroker | 2023-11-02 14:51:56.247 | info | instance system.adapter.ring.0 started with pid 52035

</body>
</html>`

**Versions:**  
 - Adapter version: v5.0.6
 - JS-Controller version: 5.0.12
 - Node version: v18.18.2
 - Operating system: Linux Mint Docker

**Comment by theimo1221** [comment]
Moin @niiccooo1 

da fehlten noch Aspekte im Release Build, sollte mit 5.0.7 behoben sein. 

Danke für die Meldung 👍

**Comment by theimo1221** [comment]
Moin @niiccooo1 

da fehlten noch Aspekte im Release Build, sollte mit 5.0.7 behoben sein. 

Danke für die Meldung 👍

**Comment by niiccooo1** [comment]
Instanz läuft mit der 5.0.7 wieder
