### ISSUE TITLE
Installation Ring Adapter bringt fehler 

### ISSUE THREAD

**Issue by ManiacKill** [iobroker-community-adapters/ioBroker.ring#613]
Ich bekomme den Adapter nicht mehr installiert, diese Meldung bekomme ich immer,

<html>
<body>

st.raspberrypi | 2023-11-04 10:42:04.159 | error | instance system.adapter.ring.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.raspberrypi | 2023-11-04 10:42:04.159 | error | Caught by controller[0]: Node.js v18.18.2
host.raspberrypi | 2023-11-04 10:42:04.159 | error | Caught by controller[0]: }
host.raspberrypi | 2023-11-04 10:42:04.159 | error | Caught by controller[0]: requestPath: '@homebridge/camera-utils'
host.raspberrypi | 2023-11-04 10:42:04.159 | error | Caught by controller[0]: path: '/opt/iobroker/node_modules/@homebridge/camera-utils/package.json',
host.raspberrypi | 2023-11-04 10:42:04.159 | error | Caught by controller[0]: code: 'MODULE_NOT_FOUND',
host.raspberrypi | 2023-11-04 10:42:04.159 | error | Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:1119:32) {
host.raspberrypi | 2023-11-04 10:42:04.159 | error | Caught by controller[0]: at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
host.raspberrypi | 2023-11-04 10:42:04.159 | error | Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1256:14)
host.raspberrypi | 2023-11-04 10:42:04.159 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/ring-client-api/lib/streaming/streaming-session.js:5:24)
host.raspberrypi | 2023-11-04 10:42:04.159 | error | Caught by controller[0]: at require (node:internal/modules/cjs/helpers:119:18)
host.raspberrypi | 2023-11-04 10:42:04.159 | error | Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1143:19)
host.raspberrypi | 2023-11-04 10:42:04.159 | error | Caught by controller[0]: at Module._load (node:internal/modules/cjs/loader:922:27)
host.raspberrypi | 2023-11-04 10:42:04.159 | error | Caught by controller[0]: at Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
host.raspberrypi | 2023-11-04 10:42:04.159 | error | Caught by controller[0]: at Module._findPath (node:internal/modules/cjs/loader:680:18)
host.raspberrypi | 2023-11-04 10:42:04.159 | error | Caught by controller[0]: at tryPackage (node:internal/modules/cjs/loader:438:19)
host.raspberrypi | 2023-11-04 10:42:04.159 | error | Caught by controller[0]: Error: Cannot find module '/opt/iobroker/node_modules/@homebridge/camera-utils/lib/index.js'. Please verify that the package.json has a valid "main" entry
host.raspberrypi | 2023-11-04 10:42:04.159 | error | Caught by controller[0]: ^
host.raspberrypi | 2023-11-04 10:42:04.159 | error | Caught by controller[0]: throw err;
host.raspberrypi | 2023-11-04 10:42:04.158 | error | Caught by controller[0]: node:internal/modules/cjs/loader:446

</body>
</html>

**Comment by mcm1957** [comment]
Aus dem Forum (https://forum.iobroker.net/topic/59759/ring-doorbell-adapter/34) hier ergänzt:

Node.js: v18.18.2
NPM: 10.2.3
Installiert js-controller:5.0.12

----------

@ManiacKill 
NPM 10.x.x passt nicht zu node 18.x.x 
npm sollte immer nur gemeinsam mit node installiert werden . nie extra aktualisiert werden,

**Comment by ManiacKill** [comment]
Ok Danke, hab jetzt wieder auf 9.8.1 stehen 👍 Der fehler vom Adapter bleibt !

**Comment by mcm1957** [comment]
https://forum.iobroker.net/topic/59759/ring-doorbell-adapter/42

Nach einspielen eines Backups funktioniert lt. Forum wieder alles.

Schätze hier kann geclosed werden.
