### ISSUE TITLE
Datenpunkt doorbell reagiert mehrmals auf ein Klingeln

### ISSUE THREAD

**Issue by Hohenbostler** [iobroker-community-adapters/ioBroker.ring#617]
Hi zusammen. Ich habe eine Doorbell 2 und sobald jemand dort die Klingel betätigt wird der doorbell Datenpunkt mehrfach auf true / false umgeschaltet. Soll dies so sein ? 

`
javascript.0 | 2023-11-23 08:01:50.970 | info | script.js.Systemsteuerung.Ring_Adapter_Klingeln: false
javascript.0 | 2023-11-23 08:01:45.980 | info | script.js.Systemsteuerung.Ring_Adapter_Klingeln: true
javascript.0 | 2023-11-23 08:01:39.280 | info | script.js.Systemsteuerung.Ring_Adapter_Klingeln: false
javascript.0 | 2023-11-23 08:01:34.282 | info | script.js.Systemsteuerung.Ring_Adapter_Klingeln: true
javascript.0 | 2023-11-23 08:01:28.667 | info | script.js.Systemsteuerung.Ring_Adapter_Klingeln: false
javascript.0 | 2023-11-23 08:01:25.712 | info | script.js.Systemsteuerung.Ring_Adapter_Klingeln: true
javascript.0 | 2023-11-23 08:01:24.074 | info | script.js.Systemsteuerung.Ring_Adapter_Klingeln: false
javascript.0 | 2023-11-23 08:01:23.669 | info | script.js.Systemsteuerung.Ring_Adapter_Klingeln: true
javascript.0 | 2023-11-23 08:01:19.820 | info | script.js.Systemsteuerung.Ring_Adapter_Klingeln: false
javascript.0 | 2023-11-23 08:01:19.086 | info | script.js.Systemsteuerung.Ring_Adapter_Klingeln: true
javascript.0 | 2023-11-23 08:01:15.717 | info | script.js.Systemsteuerung.Ring_Adapter_Klingeln: false
javascript.0 | 2023-11-23 08:01:11.623 | info | script.js.Systemsteuerung.Ring_Adapter_Klingeln: true
javascript.0 | 2023-11-23 08:01:11.028 | info | script.js.Systemsteuerung.Ring_Adapter_Klingeln: false
javascript.0 | 2023-11-23 08:01:10.701 | info | script.js.Systemsteuerung.Ring_Adapter_Klingeln: true
javascript.0 | 2023-11-23 08:01:06.544 | info | script.js.Systemsteuerung.Ring_Adapter_Klingeln: false
`

**Comment by mcm1957** [comment]
Looks like duplicate of #548

**Comment by mcm1957** [comment]
@Hohenbostler 
Please aleasy add version knformation

Adapter
Js-controller
Node
O/s

**Comment by Ricox1975** [comment]
Das gleiche Problem hier
Adapter: 5.0.10
JS 5.0.16
Node 18.8.2

Außerdem bleiben die Datenpunkte detectionType und type dauerhaft auf ding
<img width="1394" alt="Bildschirmfoto 2023-11-23 um 17 41 31" src="https://github.com/iobroker-community-adapters/ioBroker.ring/assets/52467622/ff9645f4-6eac-41be-bf69-e54f9d649ae3">

**Comment by theimo1221** [comment]
Wenn keine Events von anderen Typen ankommen, dann wird sich der Zustand auch nicht ändern.
