### ISSUE TITLE
(2593) Error

### ISSUE THREAD

**Issue by Bjoern2006** [iobroker-community-adapters/ioBroker.ring#62]
**Fehlermeldung lautet wie folgt:**
(2593) Error: Could not get devices in getAllRingsDevices(). Error: Could not get all doorbell devices in getAllRingsDeviceObjects(). Error: Could not get device instance in method getDevices(). Erro

**Screenshots & Logfiles**  
![Ring_Adapter_Error](https://user-images.githubusercontent.com/28015256/111501646-73c95680-8745-11eb-87b1-e191cadd65ca.JPG)

**Versions:**  
 - Adapter version: 1.1.3
 - JS-Controller version: 3.2.16
 - Node version: 12.21.0
 - Operating system: Linux

**Additional context**  
Ich habe an meinem System bzw. an Ring Doorbell nichts geändert.
Gibt es hierzu schon einen Fix?

**Comment by Bjoern2006** [comment]
**Nach einem Update auf Version 1.1.5:**

Fehlermeldung wie folgt:
**(6457) Error: Could not get devices in getAllRingsDevices(). Error: Could not get all doorbell devices in getAllRingsDeviceObjects(). Error: Could not get device instance in method getDevices(). Error**

![Ring_Adapter_Error_2](https://user-images.githubusercontent.com/28015256/111502705-62cd1500-8746-11eb-9963-2afd660cc29a.JPG)

**Comment by Thomas-Doc** [comment]
Genau denselben Fehler hatte ich auch (Adapter 1.1.3). Nach Deinstallation und neuem Token war er weg. Vermutlich hätte es auch genügt, einfach ein neues Token anzufordern. Der Adapter funktioniert wieder normal (außer dem blöden Error beim Snapshot, aber immerhin kommt das Bild weiterhin, nur die Fehlermeldung stört etwas). Also versuch mal, das Token neu zu erstellen, grundsätzlich läuft der Adapter.

**Comment by Bjoern2006** [comment]
> Genau denselben Fehler hatte ich auch (Adapter 1.1.3). Nach Deinstallation und neuem Token war er weg. Vermutlich hätte es auch genügt, einfach ein neues Token anzufordern. Der Adapter funktioniert wieder normal (außer dem blöden Error beim Snapshot, aber immerhin kommt das Bild weiterhin, nur die Fehlermeldung stört etwas). Also versuch mal, das Token neu zu erstellen, grundsätzlich läuft der Adapter.

Also ich hab beides gemacht, erst nur den Token neu gesetzt und dann beides - Neuinstallation und dann nochmal neuer Token.
Hat (bei mir) leider keine Besserung gebracht...
Hab den Adapter erstmal wieder pausiert, weil das selbst meinen PI 4 8GB gut auslastet, wenn alle paar Sekunden, die Fehlermeldungen kommen und dann immer und immer wieder der Adapter neu startet...
Trotzdem danke! - Hätte ja funktionieren können.

**Comment by Thomas-Doc** [comment]
> 
> 
> > Genau denselben Fehler hatte ich auch (Adapter 1.1.3). Nach Deinstallation und neuem Token war er weg. Vermutlich hätte es auch genügt, einfach ein neues Token anzufordern. Der Adapter funktioniert wieder normal (außer dem blöden Error beim Snapshot, aber immerhin kommt das Bild weiterhin, nur die Fehlermeldung stört etwas). Also versuch mal, das Token neu zu erstellen, grundsätzlich läuft der Adapter.
> 
> Also ich hab beides gemacht, erst nur den Token neu gesetzt und dann beides - Neuinstallation und dann nochmal neuer Token.
> Hat (bei mir) leider keine Besserung gebracht...
> Hab den Adapter erstmal wieder pausiert, weil das selbst meinen PI 4 8GB gut auslastet, wenn alle paar Sekunden, die Fehlermeldungen kommen und dann immer und immer wieder der Adapter neu startet...
> Trotzdem danke! - Hätte ja funktionieren können.

Deinstall mal den Adapter (ggf. vorher den Token kopieren), dann hol dir von github 1.1.6-1, über "eigene Quelle" "iobroker.ring" installieren.
Nimm nicht die 1.1.5-beta, damit geht es nicht (die finde ich auch gar nicht mehr, auch nicht auf github).
Deine Fehlermeldung hatte ich, als meine Zugangsdaten (oder token oder beides) falsch waren.

1.1.6-1 läuft eigentlich gut. Auch livestreams werden sauber gespeichert. Keinerlei Fehlermeldungen. Aber ein snapshot macht jetzt leider einen Totalcrash, böse Fehlermeldungen. Wird aber sicher bald behoben, denn wenn livestream läuft, so wird ja der snaphot bug auch wegzukriegen sein.
