### ISSUE TITLE
Is not an object of type "meta"

### ISSUE THREAD

**Issue by Bjoern2006** [iobroker-community-adapters/ioBroker.ring#63]
**ERRORMeldung:**
ring.0 | 2021-03-25 17:12:39.034 | error | (21125) Error: Error setSanpshot()): Error: ring.0 is not an object of type "meta"
-- | -- | -- | --
ring.0 | 2021-03-25 17:12:39.032 | error | (21125) Cannot write file doorbell_XXXXXXX/snapshotXXXXXXX_1616688742642.jpg: ring.0 is not an object of type "meta"

Gibt's dazu eine Lösung?

**Comment by theimo1221** [comment]
In 1.1.6 behoben
