### ISSUE TITLE
Device with Type cocoa_doorbell_v3 not yet supported, please inform dev Team via Github

### ISSUE THREAD

**Issue by reutli** [iobroker-community-adapters/ioBroker.ring#685]
it's a new Battery Doorbell Pro.
It still works, but features such as a connected solar panel etc. are not recognized.

Let me know if you need more information, e.g. because there is no hardware to test.

**Comment by NicolasHerzinger** [comment]
Hallo,
hab das gleiche Problem.
LG

**Comment by Wildkaban** [comment]
Hab auch das Problem leider ...

**Comment by reutli** [comment]
cool thx for fixing. let me ask, when the new version finds his way in the repo? or am I forced to install it via github?

**Comment by mcm1957** [comment]
Never ever install a release form github unless asked by dev.

A new release will be abailable at LATEST / BETA after 24h latest - if everything is working normally. Repositories are updated twice a day.

If you want to install a brand new release with betat testing level you can either switch to latest repository or simpy use admin "install from npm" to get latest release. At commandline you can use "iob url iobroker.ring" (note: do nOT use github address her beut simply specifiy the npm pacakt name)
