### ISSUE TITLE
Adapter crash bei snapshotrequest

### ISSUE THREAD

**Issue by Thomas-Doc** [iobroker-community-adapters/ioBroker.ring#71]
Version 1.1.6-1
Es geht wieder voran, richtiger Weg!
behebt viele issues, insbesondere funktioniert der livestream wieder perfekt. Wird sowohl von der Klingel ausgelöst als auch über den Testbutton (livestreamrequest). Der Livestream findet sich (ohne Störungen!) im angegebenen Verzeichnis und kann abgespielt werden.

Auch der Fehler mit dem blöden "meta" ist weg. Die Dateinamen bzw. url können wieder richtig in die Datenpunkte geschrieben werden. 

ABER: snapshotrequest führt zu einem sofortigen Absturz des Adapters mit bösen Fehlermeldungen. Das ist blöd, weil ein Klingeln nicht nur einen Livestream auslöst, sondern auch einen snapshot. Kann man -zu 100 Prozent reproduzieren (snapshotrequest Button auslösen).

`

host.iobroker | 2021-03-27 12:30:07.091 | info | Restart adapter system.adapter.ring.0 because enabled
-- | -- | -- | --
host.iobroker | 2021-03-27 12:30:07.090 | error | instance system.adapter.ring.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.iobroker | 2021-03-27 12:30:07.090 | error | Caught by controller[0]:     at ObjectsInRedisClient.writeFile  (/opt/iobroker/node_modules/@iobroker/db-objects-redis/lib/objects/objectsInRedisClient.js:709:13)
host.iobroker | 2021-03-27 12:30:07.090 | error | Caught by controller[0]:     at ObjectsInRedisClient.validateMetaObject   (/opt/iobroker/node_modules/@iobroker/db-objects-redis/lib/objects/objectsInRedisClient.js:457:39)
host.iobroker | 2021-03-27 12:30:07.089 | error | Caught by controller[0]: Error: /opt/iobroker/snapshot/snapshot29170532_1616844603797.jpg is not an object of type "meta"
host.iobroker | 2021-03-27 12:30:07.089 | error | Caught by controller[0]: This error originated either by throwing  inside of an async function without a catch block, or by rejecting a  promise which was not handled with .catch(). The promise rejecte
ring.0 | 2021-03-27 12:30:06.214 | warn | (4570) Terminated (UNCAUGHT_EXCEPTION): Without reason
ring.0 | 2021-03-27 12:30:06.213 | info | (4570) terminating
ring.0 | 2021-03-27 12:30:06.209 | info | (4570) Closing Adapter
ring.0 | 2021-03-27 12:30:06.191 | error | (4570) /opt/iobroker/snapshot/snapshot29170532_1616844603797.jpg is not an object of type "meta"
ring.0 | 2021-03-27 12:30:06.190 | error | at ObjectsInRedisClient.writeFile  (/opt/iobroker/node_modules/@iobroker/db-objects-redis/lib/objects/objectsInRedisClient.js:709:13)
ring.0 | 2021-03-27 12:30:06.190 | error | at ObjectsInRedisClient.validateMetaObject  (/opt/iobroker/node_modules/@iobroker/db-objects-redis/lib/objects/objectsInRedisClient.js:457:39)
ring.0 | 2021-03-27 12:30:06.190 | error | (4570) Error: /opt/iobroker/snapshot/snapshot29170532_1616844603797.jpg is not an object of type "meta"
ring.0 | 2021-03-27 12:30:06.182 | error | (4570) unhandled promise rejection: /opt/iobroker/snapshot/snapshot29170532_1616844603797.jpg is not an object of type "meta"
ring.0 | 2021-03-27 12:30:06.182 | error | (4570) Unhandled promise rejection. This error originated either by  throwing inside of an async function without a catch block, or by  rejecting a promise which was not handled with .catch().
  |  

`

**Comment by theimo1221** [comment]
Danke für das Feedback, ich hoffe der neue PR behebt auch dieses Problem.

Mit welchem Browser funktionieren bei dir die Livestreams?

**Comment by Thomas-Doc** [comment]
Livestream: Firefox geht einwandfrei.
Google chrome müsste ich mal testen.

**Comment by theimo1221** [comment]
> Livestream: Firefox geht einwandfrei.
> Google chrome müsste ich mal testen.

Mit der neusten Version sollte es gehen und auch die Livestreams nach Bewegung

**Comment by Thomas-Doc** [comment]
Werde ich gleich ausprobieren.
Livestream nach Bewegung hat bei mir eigentlich auch gut aufgezeichnet, konnte am Abend alle Aufzeichnungen vom ganzen Tag abspielen. Allerdings kam es dabei immer zum Crash des Adapters, wobei dieser glaub ich nur durch den snapshot ausgelöst wurde. Der Adapter hat dann nen Neustart gemacht.

**Comment by Thomas-Doc** [comment]
> 
> 
> > Livestream: Firefox geht einwandfrei.
> > Google chrome müsste ich mal testen.
> 
> Mit der neusten Version sollte es gehen und auch die Livestreams nach Bewegung

Ok, sieht gut aus, aber noch ein kleiner bug.
Es gibt im log eine Fehlermeldung:


```
2021-03-30 10:55:29.581  - info: ring.0 (16044) Ding Dong for Id 29170532 (motion, ringing)
2021-03-30 10:55:29.765  - info: ring.0 (16044) Starting creating snapshot
2021-03-30 10:55:29.773  - info: ring.0 (16044) Starting creating livestream with recording time 10 sec.
2021-03-30 10:55:40.641  - info: ring.0 (16044) Done creating livestream
2021-03-30 10:55:40.646  - error: ring.0 (16044) Error: Error setLivetream()): Error: Not exists
2021-03-30 10:55:49.483  - info: ring.0 (16044) Done creating snapshot

```


In dem von mir gewählten Verzeichnis liegen aber sowohl alle livestreams als mp4 und auch alle snapshots als jpg einwandfrei vor.
Man kann dort sowohl die Bilder als auch die Videos korrekt betrachten.

Allerdings verweisen der Wert von ring.0.doorbell_29170532.livestream_file als auch von ring.0.doorbell_29170532.livestream_url beide auf eine alte Aufzeichung. Offensichtlich scheitert die Aktualisierung des Wertes, so dass es auch zu einem Logeintrag kommt. Hingegen funktioniert es beim Schnappschuss mit dem jpg problemlos. Da sind sowohl das Bild vorhanden als auch der jeweils aktuelle Eintrag in ring.0.doorbell_29170532.snapshot_url.

**Comment by theimo1221** [comment]
@Thomas-Doc  Aktuell nutzt du nicht den neusten Stand, weil ich genau diesen Fehler und auch das Log Level angepasst habe:
https://github.com/iobroker-community-adapters/ioBroker.ring/releases/tag/v1.1.6-2

Versuche es bitte damit.

**Comment by Thomas-Doc** [comment]
Ok. Geschafft, bin auf 1.1.6-3. Beim Update hatte ich Probleme: Installation "aus eigener Quelle" lief zwar durch, kam aber immer wieder auf die vorherige Version. Versuch über Installation "aus github" ebenso. Erst nach Deinstallation des alten Adapters und Anwahl von "github" kam ich auf die 1.1.6-3.

Sieht soweit ganz gut aus. Die Fehlermeldungen beim Start hatte ich auch, sind aber vermutlich bedeutungslos. Vermutlich anfängliches Autorisierungsproblem bei ring.com. In ähnlicher Form auch schon früher mal gehabt (z.B. falsches Token, war diesmal aber richtig und lief ja auch beim zweiten Anlauf durch).  Der Adapter beendet sich dann von selbst und startet noch mal, läuft dann. Snapshotrequest und livestreamrequest und motion etc. funktionieren. Es waren plötzlich mal ganz viele DingDongs im Log, aber einfach nur als Info. Hingegen fehlt die Meldung "snapshot erfolgreich". Die jpgs und mp4 sind aber da, die urls werden sauber geschrieben. Herz was begehrst du mehr :)

Der Objektbaum ist etwas anders als in der vorherigen Version. Möglicherweise hatte ich deshalb Probleme vom 1.1.6-2 auf -3 zu kommen. Bin aber erst mal zufrieden und lass den ring.0 die nächsten Tage mal so laufen. 

Hier noch die Fehlermeldung beim ersten Start:

```
ring.0 | 2021-03-30 22:03:49.434 | info | (12415) Starting Ring Device for Id xxxxxxxx
ring.0 | 2021-03-30 22:03:47.107 | info | (12415) Starting Adapter ring.0 in version 1.1.6-3
ring.0 | 2021-03-30 22:03:47.045 | info | (12415) starting. Version 1.1.6-3 in /opt/iobroker/node_modules/iobroker.ring, node: v12.21.0, js-controller: 3.2.16
host.iobroker | 2021-03-30 22:03:43.773 | info | instance system.adapter.ring.0 started with pid 12415
host.iobroker | 2021-03-30 22:03:41.324 | info | instance system.adapter.ring.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
host.iobroker | 2021-03-30 22:03:40.728 | info | stopInstance system.adapter.ring.0 send kill signal
ring.0 | 2021-03-30 22:03:40.725 | info | (12266) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
ring.0 | 2021-03-30 22:03:40.723 | info | (12266) terminating
ring.0 | 2021-03-30 22:03:40.722 | info | (12266) Closing Adapter
ring.0 | 2021-03-30 22:03:40.720 | info | (12266) Got terminate signal TERMINATE_YOURSELF
host.iobroker | 2021-03-30 22:03:40.711 | info | stopInstance system.adapter.ring.0 (force=false, process=true)
ring.0 | 2021-03-30 22:02:51.034 | error | (12266) Error: Could not get devices in getAllRingsDevices(). Error:  Could not get all doorbell devices in getAllRingsDeviceObjects(). Error:  Could not get device instance in method getDevices(). Err
ring.0 | 2021-03-30 22:02:35.803 | error | (12266) Error: Could not get devices in getAllRingsDevices(). Error:  Could not get all doorbell devices in getAllRingsDeviceObjects(). Error:  Could not get device instance in method getDevices(). Err
ring.0 | 2021-03-30 22:02:35.201 | info | (12266) Starting Adapter ring.0 in version 1.1.6-3
ring.0 | 2021-03-30 22:02:35.135 | info | (12266) starting. Version 1.1.6-3 in /opt/iobroker/node_modules/iobroker.ring, node: v12.21.0, js-controller: 3.2.16

```

**Comment by Thomas-Doc** [comment]
So sieht es jetzt im Log aus:
1) manuell request
(angezeigt als on_demand)

```
ring.0 | 2021-03-30 22:11:31.808 | info | (12415) Ding Dong for Id 29170532 (on_demand, ringing)
ring.0 | 2021-03-30 22:11:31.806 | info | (12415) Ding Dong for Id 29170532 (on_demand, ringing)
ring.0 | 2021-03-30 22:10:20.756 | info | (12415) Ding Dong for Id 29170532 (on_demand, ringing)
ring.0 | 2021-03-30 22:10:20.748 | info | (12415) Ding Dong for Id 29170532 (on_demand, ringing)
ring.0 | 2021-03-30 22:10:20.722 | info | (12415) Ding Dong for Id 29170532 (on_demand, ringing)

```
Waren anfangs aber auch schon 20 Einträge, hat sich jetzt etwas beruhigt (solche manuellen Requests sind ja auch eher selten)

und beim echten Klingeln (motion und ding) nur 2 Einträge:

```
ring.0 | 2021-03-30 22:36:54.100 | info | (12415) Ding Dong for Id 29170532 (ding, ringing)
ring.0 | 2021-03-30 22:36:36.045 | info | (12415) Ding Dong for Id 29170532 (motion, ringing)

```
außer beim ersten Start aber keine errors, sieht also gut aus. Das Update muss aber noch überprüft werden, ich glaube nicht dass ich da was doll falsch gemacht hab (auch wenn ich da kein Profi bin).

**Comment by theimo1221** [comment]
Danke für das umfangreiche Feedback, ich schuae mir das morgen nochmal genauer an.
Die Meldung _Done dreating Snapshot_ ist bewusst auf Debug Level gestellt, damit der Standard Log sauberer/leerer bleibt.

**Comment by Thomas-Doc** [comment]
Nach einem Neustart (nach Batterie-Laden) leider wieder kleine (vorzugsweise alte) Probleme. 
1) Eine unendliche Zahl von Infos beim Neustart, so etwa 50, alle mit dem gleichen Zeitstempel (gekürzt):

```
ring.0 | 2021-03-31 17:39:07.364 | info | (29986) Starting Ring Device for Id 29170532
ring.0 | 2021-03-31 17:39:07.364 | info | (29986) Starting Ring Device for Id 29170532
ring.0 | 2021-03-31 17:39:07.364 | info | (29986) Starting Ring Device for Id 29170532
ring.0 | 2021-03-31 17:39:07.364 | info | (29986) Starting Ring Device for Id 29170532
ring.0 | 2021-03-31 17:39:07.364 | info | (29986) Starting Ring Device for Id 29170532
```
wie durch Geisterhand verschwinden die aber dann kurze Zeit später aus dem log.

2) Die Fehlermeldung beim Schnappschuss mit 70 Versuchen (sinngemäß) hatte ich auch schon. Aber jetzt nicht mehr, hat sich irgendwie "eingeschliffen".

3) Dachte erst, dass es gar keine Bilder oder Filme mehr gibt. Aber diese finden sich nun in einem anderen Verzeichnis, nämlich in iobroker-data/ring_0/snapshot  (bis gestern noch direkt in /snaphhot) ABer gut, die Bilder und Filme sind da und einwandfrei.

**Comment by theimo1221** [comment]
Jo an sich sollten iobroker Adapter Daten eben in das Verzeichnis.

Das mit den Lognachrichten beim Aufstarten kann ggf. auch eine Anzeigethematik von der ioBroker Oberfläche sein.


Die Meldung mit den Problemen nach x Versuchen habe ich auch sporadisch. Hier weiß ich aber nicht, ob nicht teilweise einfach die Ring Schnittstelle kurz inaktiv ist, oder uns bremst.
