### ISSUE TITLE
API Error bei Start des Adapters

### ISSUE THREAD

**Issue by bruesche** [iobroker-community-adapters/ioBroker.ring#737]
**Describe the bug**  
Morgen werde ich meinen neuen RING Intercom in Empfang nehmen und habe ein schon mal ein Konto bei Ring erstellt. Zusätzlich habe ich im IOBroker den Ring Adapter in Version 5.1.0 installiert. Token generiert und eingetragen. Gestartet. Der Adapter springt sofort auf Rot zurück und im Protokoll:

ring.0
2024-08-28 18:13:22.747	error	Latitude or Longitude not defined in System

ring.0
2024-08-28 18:13:22.746	warn	Couldn't load data from Ring Server on reconnect, will retry in 5 Minutes...

ring.0
2024-08-28 18:13:22.746	error	Api Call failed

Ich benutze als Betriebssystem Bookworm. Nochmal alles aktualisiert (NODEJS Version 20.17.0) und auch den Adapter mal in der Version 6.0.0 installiert. Keine Verbesserung.
Ist da der Fehler auf meiner Seite, dass das nur mit einem installierten RING Gerät funktioniert oder mache ich etwas falsch.

Über einen Tipp oder Hilfe wäre ich wirklich sehr dankbar.

VG

**Comment by mcm1957** [comment]
Wenn er schreibt das longitude oder latitude nicht definiert ist schau doch mal ob die definiert sind (in den iob Systemeinstellungen)

**Comment by mcm1957** [comment]
Check mal ob longitude und latitude in den iob systemeinstellungen eingetragen sind.

**Comment by bruesche** [comment]
In den Systemeinstellungen war zwar meine Stadt eingetragen aber nicht Längen- und Breitengrad. Das habe ich nun eingetragen. Der Adapter fällt leider immer noch "runter".

ring.0
2024-08-28 18:47:18.449	warn	Couldn't load data from Ring Server on reconnect, will retry in 5 Minutes...

ring.0
2024-08-28 18:47:18.448	error	Api Call failed

Das kann dann aber wirklich daran liegen, dass kein Gerät definiert ist?

**Comment by bruesche** [comment]
oh nee einen Eintrag übersehen:

ring.0
2024-08-28 18:49:26.328	warn	Couldn't Retrieve profile, please make sure your api-token is fresh and correct

Ich generier nochmal einen Token

**Comment by bruesche** [comment]
ok. Der "Fehler" bleibt so. 
Was muss ich denn vom Token eintragen. Habe einfach alles kopiert und dann gespeichert:

"refreshToken": "eyJydCI6ImV5SmhiR2NpT2lKU1V6STF...ZjdhIn0="

Beim Generieren kommt auch kein Fehler. Der 2MFA Code kommt auch auf dem Handy an...

**Comment by bruesche** [comment]
Hab jetzt nochmal etwas experiementiert und das REFRESH TOKEN : weg gelassen.
Der Refresh Token Fehler ist weg. Hab auch nochmal versucht die "" um den Token weg zu lassen. Ändert sich nichts. 

Der Token scheint damit wohl jetzt korrekt zu sein. 

So bleibt das Protokoll dann nun:

ring.0
2024-08-28 19:01:24.998	warn	Couldn't load data from Ring Server on reconnect, will retry in 5 Minutes...

ring.0
2024-08-28 19:01:24.997	error	Api Call failed

**Comment by bruesche** [comment]
Oh man. Ein paar Sekunden gewartet und noch einmal den Adapter neu gestartet und: Der Adapter bleibt grün. 

Danke für die Hilfe und sorry für mein Unvermögen. 

VG

**Comment by bruesche** [comment]
Wenn noch was ist, melde ich mich sicher. Danke!

**Comment by bruesche** [comment]
Doch nicht. Fehler kam wieder. Ich schaue morgen mal mit einem konfigurieren Gerät. 

VG

**Comment by bruesche** [comment]
Wenn die Einrichtung der Ring abgeschlossen ist, klappt es auch mit dem Adapter.
