### ISSUE TITLE
Device with Type stickup_cam_medusa not yet supported, please inform dev Team via Github

### ISSUE THREAD

**Issue by NicolasHerzinger** [iobroker-community-adapters/ioBroker.ring#738]
Device with Type stickup_cam_medusa not yet supported, please inform dev Team via Github

**Comment by fal-ke** [comment]
Me too. (Model Ring Stick Up Cam Pro.)
The device is shown as "unknown_XXX". Sometimes it works, sometimes not (Snapshot requests).
