### ISSUE TITLE
Snapshot Error V1.1.6-3

### ISSUE THREAD

**Issue by Bjoern2006** [iobroker-community-adapters/ioBroker.ring#74]
**Fehlerbeschreibung**  
Der Fehler ist erst neu in der Version 1.1.6-3 aufgetaucht.

**Screenshots & Logfiles**  
![Ring_Adapter_1 1 6-2_Error](https://user-images.githubusercontent.com/28015256/112983253-c2232000-915d-11eb-9fa7-d7316cc9aca9.jpg)

**Versions:**  
 - Adapter version: 1.1.6-3
 - JS-Controller version: 3.2.16
 - Node version: 12.21.0
 - Operating system: Linux

**Comment by theimo1221** [comment]
Der 2. Teil der Logmeldung, trifft der in dem Falle zu (warst du am Streamen/Bewegungsaufzeichnung)?

**Comment by Bjoern2006** [comment]
Die Ring Doorbell macht automatisch bei jeder Bewegung eine kurze Aufzeichnung der Bewegung.

**Comment by funboxbolzer** [comment]
Hi,
ich habe das selbe problem. Ich kann aber auch keine Snapshot mit dem Button erstellen.
Wenn ich den Videobutton drücke, bekomme ich die selbe Logmeldung
