### ISSUE TITLE
Node 18 no longer supported ?

### ISSUE THREAD

**Issue by mcm1957** [iobroker-community-adapters/ioBroker.ring#749]
Sub dependency `push-receiver` requires node 20 now, see
https://github.com/iobroker-community-adapters/ioBroker.ring/blob/a91338b07d775f2c13d35a22a502d980ce2fd8ea/package-lock.json#L742

So either this adapter needs to require node 20 too or the dependencies have to be downgraded.

Currently user installations crash unexpectedly.

**Comment by paginaweb123** [comment]
try this
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
I put the necessary dlls in the archive

**Comment by mcm1957** [comment]
**Habe obigen Comment bereits gemeldet. Sollte ehestens verschwinden. Bitte KEINEFALLS die verlinkte Seite öffnen !**

**Comment by mcm1957** [comment]
@theimo1221 

If I see this correctly, adapter ring currently supports node.js 20 only. Node 18 fails due to this issue, node 22 is not supported by ring dependency Correct ?

**Comment by mcm1957** [comment]
Thanks for fast reaction!
