### ISSUE TITLE
Error after installing the adapter

### ISSUE THREAD

**Issue by JayRHa** [iobroker-community-adapters/ioBroker.ring#75]
22734) Error: Could not get devices in getAllRingsDevices(). Error: Could not get all doorbell devices in getAllRingsDeviceObjects(). Error: Could not get device instance in method getDevices(). Err

**Comment by theimo1221** [comment]
@JayRHa which version are you using?

**Comment by JayRHa** [comment]
i use the version 1.1.6-3 (2021-03-29)

Do you use this adapter for the first time?
no i ise this adapter since a year but with lot if different issues

Have you set up Login information as written in description?
yes
Which devices do you have
rasperry pi 4

**Comment by theimo1221** [comment]
Thanks for the additional details.

My questions regarding the devices where not precise:
Which cameras from ring do you use?

And is this the first time this error occurs?

**Comment by theimo1221** [comment]
Okay, so the object itself is missing within the objects list?
Did you restart the adapter and/or iobroker?

I'm sorry but this error could have many different reasons, so I'm trying to figure out what might went wrong.

**Comment by JayRHa** [comment]
yes the object itself is missing. I have restarted the adapter. I also try a reinstallation. Only an iobroker restart i have not tested yet.

**Comment by Thomas-Doc** [comment]
In my opinion its a problem of authentification. I*ve got the same errors, but the adapter did a restart itself. See 
[(https://github.com/iobroker-community-adapters/ioBroker.ring/issues/71#issuecomment-810557256)](url)
After this restart all the objects were rebuild (I had to uninstall the previous version). And after the rebuild I've got a message from ring (about a new login) too. Did you get any mails from ring?

Try to get a new refreshtoken from ring.

**Comment by JayRHa** [comment]
After refreshing from the toke it works. Many it was an issue with the copy of the toke. But I have an new issue:

1548) Error: Error setSanpshot()): Error: Could not create Snapshot for 54439917 in getSnapshot(). Error: Snapshot for Haustür (cocoa_doorbell - Doorbell Gen 2) failed to refresh after 70 attempts.

Video does work but not the creation of an snapshot

**Comment by Thomas-Doc** [comment]
Same as here:

```
ring.0 | 2021-03-31 17:32:11.614 | info | (25742) Ding Dong for Id xxxx (motion, ringing)
ring.0 | 2021-03-31 17:29:55.452 | error | (25742) Error: Error setSanpshot()): Error: Could not create Snapshot  for xxxxxxxx in getSnapshot(). Error: Snapshot for Klingel (doorbell_v4 -  Doorbell 2) failed to refresh after 70 attempts.  This
ring.0 | 2021-03-31 17:29:08.177 | info | (25742) Ding Dong for Id xxxxxxxxxxxxx (ding, ringing)

```
After restart, I cant see any snapshot nor video file. Nothing.

**Comment by JayRHa** [comment]
@Thomas-Doc: Can you fix this issue?
If you need support i can help

**Comment by souhl** [comment]
Tried to install the adapter several times. It looks like the token issue, but don't know how to fix it. Installed 1.2.1.
Adapter and instances deleted and reinstalled. New Token issues from the login screen. Entered it and saved it again.

```
ring.0 | 2021-05-05 08:56:37.933 | error | (2047004) Error: Could not get devices in getAllRingsDevices(). Error: Could not get all doorbell devices in getAllRingsDeviceObjects(). Error: Could not get device instance in method getDevices(). Er
-- | -- | -- | --
ring.0 | 2021-05-05 08:56:23.947 | debug | (2047004) system.adapter.admin.0: logging true
ring.0 | 2021-05-05 06:56:22.395 | info | (2047004) Starting Adapter ring.0 in version 1.2.1
ring.0 | 2021-05-05 06:56:22.364 | info | (2047004) starting. Version 1.2.1 in /opt/iobroker/node_modules/iobroker.ring, node: v12.20.0, js-controller: 3.2.16
ring.0 | 2021-05-05 06:56:22.216 | debug | (2047004) Plugin sentry Initialize Plugin (enabled=true)
ring.0 | 2021-05-05 06:56:22.025 | debug | (2047004) statesDB connected
ring.0 | 2021-05-05 06:56:22.024 | debug | (2047004) States connected to redis: 127.0.0.1:9000
ring.0 | 2021-05-05 06:56:22.018 | debug | (2047004) States create User PubSub Client
ring.0 | 2021-05-05 06:56:22.017 | debug | (2047004) States create System PubSub Client
ring.0 | 2021-05-05 06:56:22.008 | debug | (2047004) Redis States: Use Redis connection: 127.0.0.1:9000
ring.0 | 2021-05-05 06:56:22.006 | debug | (2047004) objectDB connected
ring.0 | 2021-05-05 06:56:22.001 | debug | (2047004) Objects connected to redis: 127.0.0.1:9001
ring.0 | 2021-05-05 06:56:21.990 | debug | (2047004) Objects client initialize lua scripts
ring.0 | 2021-05-05 06:56:21.990 | debug | (2047004) Objects create User PubSub Client
ring.0 | 2021-05-05 06:56:21.989 | debug | (2047004) Objects create System PubSub Client
ring.0 | 2021-05-05 06:56:21.988 | debug | (2047004) Objects client ready ... initialize now
ring.0 | 2021-05-05 06:56:21.965 | debug | (2047004) Redis Objects: Use Redis connection: 127.0.0.1:9001
```

Jemand noch Ideen?
