### ISSUE TITLE
Beim Klingeln stürzt Adapter ab

### ISSUE THREAD

**Issue by Merexor** [iobroker-community-adapters/ioBroker.ring#92]
Hallo,

Ich habe ein Problem mit meiner Ring Door View:
Sobald es klingt bricht der Adapter zusammen. 
Warum ist das so bzw. wie kann man das beheben?

Log:
![image](https://user-images.githubusercontent.com/68726324/114587477-fe8a6c00-9c85-11eb-8c9b-72a35b3dc4bd.png)

**Comment by styrmirgruenheit** [comment]
Halle Merexor,

ich hatte den gleichen Fehler. In irgendeiner anderen "Issue" habe ich den Hinweis gefunden, dass man ffmpeg installieren muss.
Das habe ich gemacht und das erste Problem war danach weg. Allerdings gab es dann eine andere Fehlermeldung:

![logs-ioBroker](https://user-images.githubusercontent.com/19946417/114874740-e6892880-9dfc-11eb-8fbb-5a245e85e088.png)

**Comment by Thomas-Doc** [comment]
Ihr verwendet vermutlich noch die alte "stable" version. In der Version 1.1.6-3 sind diese Fehler eigentlich behoben. Aus der "stable" 1.1.3 kenn ich diese Fehler auch.

Eventuell auch mal den ganzen Adapter löschen und die 1.1.6.3 neu installieren.
