### ISSUE TITLE
Update stable version in repo from 1.1.3 to 1.1.6-3

### ISSUE THREAD

**Issue by GermanBluefox** [iobroker-community-adapters/ioBroker.ring#93]
# Think about update stable version to 1.1.6-3
**Version**: stable=**1.1.3** (340 days old) => latest=**1.1.6-3** (15 days old)
**Installs**: stable=**1007** (75.26%), latest=**150** (11.21%), total=**1338**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L1351)

**Comment by Thomas-Doc** [comment]
Ihr verwendet vermutlich noch die alte "stable" version. In der Version 1.1.6-3 sind diese Fehler eigentlich behoben. Aus der "stable" 1.1.3 kenn ich diese Fehler auch.

Eventuell auch mal den ganzen Adapter löschen und die 1.1.6.3 neu installieren.
