### ISSUE TITLE
SnapshotURL und SnapshotPfad sind nicht gefüllt.

### ISSUE THREAD

**Issue by funboxbolzer** [iobroker-community-adapters/ioBroker.ring#94]
Snapshot URL und Snapshot Pfad sind leer, daher kann ich keine Snapshot erstellen. Live Video URL und Pfad ist gefüllt.
Der Button ist auch kein "Button" mehr, nur noch ein true/false Feld.

bei meiner StickUp Cam ist beides gefüllt.
Was kann ich hier tun?

Danke Klaus

**Versions:**  
 - Adapter version: 1.2.1 npm Versiom
 - JS-Controller 3.2.16
 - Node version:  14.16.1
 - Operating system: raspberry buster

**Comment by froder1k** [comment]
Bei mir ist der Button noch vorhanden.
Durch klicken konnte ich ein einziges Mal einen Snapshot anfordern. Seit dem schlägt es nach 40 attemps fehl.

`Error: Error setSanpshot()): Error: Could not create Snapshot for xxxxxxxx in getSnapshot(). Error: Snapshot failed to refresh after 40 attempts`
