### ISSUE TITLE
Delete old Snapshot

### ISSUE THREAD

**Issue by bergjet** [iobroker-community-adapters/ioBroker.ring#96]
Adapter 1.2.1
Alte Aufzeichnungen werden bei mir nicht gelöscht. Muss man da was beachten?

**Comment by DickenSerm** [comment]
Bei mir leider auch nicht, kann da jemand helfen?

**Comment by theimo1221** [comment]
Werde ich mir die Tage mal genauer anschauen

**Comment by Yunkie** [comment]
Bei mir und meinem Vater geht es leider auch nicht. Gibt es hierzu schon etwas neues?

**Comment by Tripartius** [comment]
Die Datenmengen haben bei mir auch zu nem Absturz geführt. Alte Aufzeichnungen werden bei mir auch nicht gelöscht.
Wenn man die Snapshots deaktiviert, bezieht sich das auf die Bilder und den Livestream?

Wäre toll, wenn das im Adapter noch berücksichtigt werden könnte, dass die alten Aufzeichnungen automatisch gelöscht werden. Mein Backup war gestern noch knapp 700mb groß...;)

**Comment by theimo1221** [comment]
Es steht noch auf meiner ToDo Liste

**Comment by brunsheinz** [comment]
Ist leider bei mir auch ein Problem . Ich speichere zwar die Snapshot und Lifestream Files auf einem USB Stick , aber über den Ring Adapter wird immer noch ein Ring.o File in Iobroker Bachkup geschrieben . Und jeden Tag wird dieser File größer . Nach 3 Monaten bläht sich das Backup dann auf über 5 GB auf und dauert ewig .
